### ISSUE TITLE
[QUESTION] cpp2 for loops

### ISSUE THREAD

**Issue by dutkalex** [hsutter/cppfront#1063]
Hi! My question is rather simple, but I could not find the answer in the documentation nor in other issues. What is the cpp2 equivalent for:
```cpp
for ( int i = a; i < b; ++i ){
  // loop body
}
```
All the examples in the documentation seem to be range-based for loops, and the closest I could find (which is obviously not the right answer) is:
```cpp
for std::views::iota{ a, b } do ( i ){
  // loop body
}
```
Thanks for the amazing work!
Best regards,
Alex

**Comment by hsutter** [comment]
That's a good question I should cover somewhere. Here's the quick answer:

```cpp
auto old() {
    //  Prints: 0123456789
    for ( int i = 0; i < 10; ++i ){
        std::cout << i;
    }
    std::cout << "\n";
}

main: () = {
    old();

    //  Prints: 0123456789
    (copy i := 0) while i < 10 next i++ {
        std::cout << i;
    }
    std::cout << "\n";

    // Same, just my personal whitespace style
    (copy i := 0)
    while i < 10
    next  i++ {
        std::cout << i;
    }
    std::cout << "\n";
}
```

Line by line (and why I like being able to write the parts on individual lines):

- `(copy i := 0)`: Any statement can have statement-local parameters, so this is just declaring `i` as an `int` that's local to the loop. Parameters default to `const`, so because I want to modify it I use `copy`. (I find that statement-local parameters initially take getting used to the first couple of times, then are easy to remember and use because they work with any statement including blocks.)
- `while i < 10`: The termination condition.
- `next i++": The end-of-loop-iteration statement. Note `++` is always postfix in Cpp2.

I should add an example to the docs... I'll keep this open until I do that. Thanks!

**Comment by hsutter** [comment]
Now added here: https://hsutter.github.io/cppfront/cpp2/functions/#for-while-do-loops

Thanks!

**Comment by dutkalex** [comment]
@hsutter You closed this thread but it turns out that your answer left me with more questions! 😅
1. I understand that one of the goals of cpp2 is simplification of the language through generalization and an overall reduction of the number of concepts. But in this case, having to revert to a while loop is a net loss in expressivity of the language. I we were to follow this principle dogmatically, for loop would have to be eliminated altogether because every for loop is just a special case the more general while loop concept, but as I am sure you will admit, this is not what we want as programmers because having the for loop in our toolbox enables us to better express our intent. For scientific computing purposes (I take this example because this is where I come from as a C++ programmer), not being able to express simply index-based iteration patterns would be a deal-breaker. However, I do not advocate for the error-prone C-syntax either, but IMO a Python-like syntax `for idx_range(a,b) do (i){ ... }` would be a nice thing to have in the language. What do you think of it?
2. I understand how the for loop syntax is built as for <range> do <anonymous_fcn>, which is actually very familiar to me as a HPC-guy because we are used to writing thinks like `hpc_framework::parallel_for( exec_policy, range, [&]( int idx ){ ... } );` in cpp1 syntax. However, the absence of the prefixed colon of the cpp2 lambda syntax in the for loop syntax, combined with the fact that the for loop syntax does not read left to right is a sign that this generalization is not that natural IMO. I would also add on a more personal note that I really don't like the `do` in the current syntax because it does not convey much meaning as a keyword. IMHO it is like having a `then` keyword after an `if` statement, it makes the syntax more verbose and does not provide any additional meaning. Moreover, having a `do` token justifies diverging the syntax from the if and while syntax which require the body to be enclosed by curly braces. It seems to me that having a coherent syntax among these 3 control flow structures should be a higher-priority goal than seeking coherence with the function syntax (but I understand that this is maybe something personal). With this in mind, my question is: why haven't you opted for a more Python-like syntax for the for loop? Something like `<optional label :> for <optional in(default), inout or move> <elm> : <range> {  /* body with mandatory {} */ }` maybe? Wouldn't that be simpler, more familiar, easier to read and more coherent with the rest of the cpp2 syntax? What do you think of it?
Thanks for the quick answer!
Best regards,
Alex

**Comment by dutkalex** [comment]
Other related threads for reference: #432 #834

**Comment by dutkalex** [comment]
Moving this to discussions (see #1073), as it seems more appropriate
