### ISSUE TITLE
[BUG] Cannot value initialise a function argument with equivalent of C++ `{}`

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#1090]
**Describe the bug**
I can't find a Cpp2 syntax to value initialise an argument passed to a function using its default constructor.

**To Reproduce**
Run cppfront on this code:
```cpp
log: (message: std::string_view,
      context: std::string,
      event_id: int) =
{
    std::println("{} {} {}", message, context, event_id);
}

main: () = {
    log("event", (), 123);  // (1) Error in C++ compiler
    log("event", _, 123);   // (2) Error in C++ compiler
    log("event", {}, 123);  // (3) Error in cppfront
}
```

(1) produces this error:
```
main.cpp2:10:19: error: expected expression
   10 |     log("event", (), 123);
      |                   ^
```

(2) produces this error:
```
main.cpp2:10:18: error: use of undeclared identifier '_'
   10 |     log("event", _, 123);
      |                  ^
```

(3) produces a cppfront syntax error.

[Repro](https://cpp2.godbolt.org/z/MM5zcMP56) on Godbolt

**Additional context**
I was [translating](https://cpp2reference.com/algorithm/ranges/find_end/) the `ranges::find_end` [example](https://en.cppreference.com/w/cpp/algorithm/ranges/find_end) from cppreference and have used explicit arguments like this:

```cpp
found4:= std::ranges::find_end(
    secret, "SWORD"sv,
    std::ranges::equal_to(),
    std::identity(),
    :(c: char) std::tolower(c));
```
instead of the original:
```cpp
const auto found4 = std::ranges::find_end(secret, "SWORD"sv,
        {},
        {},
        [](char c) { return std::tolower(c); });
```

**Comment by sookach** [comment]
Hi Neil,
The solution I think might be simplest for this is to use '{}' for default initialized arguments just like c++, and adding it would be pretty straight forward. One approach is to allow brace expressions here:

https://github.com/hsutter/cppfront/blob/130f14952e9400b95dbc055a8d9d97fa66ed5b1e/source/parse.h#L5717

However that approach might not be best one given the comment right above it. I can probably add logic to the parser to grab '{}' only in function calls, but I'd like to hear from our BDFL @hsutter before going down any route.

Thanks.

**Comment by hsutter** [comment]
Thanks! In Cpp2 so far, `{` `}` are used only for scopes.

Hot take: `()` does already mean default construction (e.g., `x : int = ();`) so an empty list argument `()` could be lowered to `{}`.

**Comment by sookach** [comment]
I like that idea, I'll try it out.
