### ISSUE TITLE
[BUG] Assert failed, file to_cpp1.h, line 6722.

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#1123]
**Describe the bug**
File `to_cpp1.h`.
Line `6722`.
Expression `assert(n.initializer);`.

**To Reproduce**
1. Download source code of cppfront.
2. Compile cppfront.
2. Run cppfront on test.cpp2 file.
3. Assert triggers inside cppfront.

**Additional context**
Test.cpp2 file's content is only 3 bytes long and it is: `r:;`.

**Comment by gregmarr** [comment]
Confirmed on cpp2.godbolt.org

**Comment by MaxSagebaum** [comment]
> Confirmed on cpp2.godbolt.org

Why not post the short link?

**Comment by sookach** [comment]
> > Confirmed on cpp2.godbolt.org
> 
> Why not post the short link?

https://cpp2.godbolt.org/z/r9KfYb5jE

**Comment by gregmarr** [comment]
> Why not post the short link?

It's literally three characters in the source, seemed like a waste to have it create and store the short link.
