### ISSUE TITLE
[BUG] Crash.

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#1129]
**Describe the bug**
`Program terminated with signal: SIGSEGV`
`Segmentation fault (core dumped)`

**To Reproduce**
1. Download source code of cppfront.
2. Compile cppfront.
2. Run cppfront on test.cpp2 file.

**Actual result**
 - Crash.

**Expected result**
 - No crash.
 - Maybe nice error message.

**Additional context**
Test.cpp2 file's content is only 5 bytes long and it is: `l:=l*`.

**Comment by hsutter** [comment]
Fixed, thanks!
