### ISSUE TITLE
[BUG] Assert failed, file `lex.h`, line `320`.

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#1130]
**Describe the bug**
File `lex.h`.
Line `320`.
Expression `global_token_order == 0`.

**To Reproduce**
1. Download source code of cppfront.
2. Compile cppfront.
2. Run cppfront on test.cpp2 file.
3. Assert triggers inside cppfront.

**Additional context**
Test.cpp2 file's content is only 24 bytes long and it is: `nI:(Q):floatl:()h:r:~-=:`.

**Comment by DyXel** [comment]
> `nI:(Q):floatl:()h:r:~-=:`

Man, I hate when that happens in my code 😅 

Jokes aside, this made me think we should probably setup some fuzzing at some point.

**Comment by MarekKnapek** [comment]
> > `nI:(Q):floatl:()h:r:~-=:`
> 
> Man, I hate when that happens in my code 😅
> 
> Jokes aside, this made me think we should probably setup some fuzzing at some point.

Yes, issue created: https://github.com/hsutter/cppfront/issues/1131.

**Comment by hsutter** [comment]
Thanks! I was just about to ask whether you were fuzzing. 👍 This is great!
