### ISSUE TITLE
[BUG]  Wrong generation of construction for @struct and clang-15

### ISSUE THREAD

**Issue by MaxSagebaum** [hsutter/cppfront#1146]
**Describe the bug**
While using clang-15 a structure created with `@struct` can not be initialized with values while using clang-15.

This does not seem to be a problem in gcc-10 and upwards.

**To Reproduce**
On compiler explorer: https://cpp2.godbolt.org/z/Me86GzYE8
```
match_return: @struct <Iter> type = {
    matched: bool = false;
    pos: Iter = ();
}

main: () = {
    c: char = 'c';
    v := match_return<*char>(false, c&);
    _ = v;
}
```

Error:
```
/opt/compiler-explorer/clang-15.0.0/bin/clang++ --gcc-toolchain=/opt/compiler-explorer/gcc-12.2.0  -I/app -I/app -std=c++20 -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -Werror=unused-value -Werror=unused-parameter -stdlib=libc++ -Wno-read-modules-implicitly -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c /app/build/main.cpp
warning: unknown warning option '-Wno-read-modules-implicitly'; did you mean '-Wno-module-conflict'? [-Wunknown-warning-option]
main.cpp2:8:13: error: no matching constructor for initialization of 'match_return<char *>'
    auto v {match_return<char*>(false, &c)}; 
            ^                   ~~~~~~~~~
main.cpp2:1:31: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
template<typename Iter> class match_return {
                              ^
main.cpp2:1:31: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
main.cpp2:1:31: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
1 warning and 1 error generated.
```

**Variants**
 - Providing the constructor is not possible with `@struct`: https://cpp2.godbolt.org/z/rWr1s6b8d
 - Changing the generated code to use curly brackets for construction makes it work:  https://cpp2.godbolt.org/z/dj8v15Mnq

**Comment by MaxSagebaum** [comment]
This could be fixed by generating the appropriate constructor. That is a constructor with as many arguments as member in the order of the members.

**Comment by hsutter** [comment]
Thanks! I ran into this in cppfront's own code, notably in the parse.h types, where I had to do the same thing -- write out the constructor. It also happened only in newer/stricter compilers. For aggregates, my untested suspicion is that the problem might go away on its own once the rule change for `()` aggregate initialization is implemented, but there's no reason not to fix it in the meantime anyway...

**Comment by hsutter** [comment]
Oh wait, I forgot to re-run regression, still have bugs to fix...

**Comment by hsutter** [comment]
Now actually fixed...

**Comment by JohelEGP** [comment]
> `v := match_return<*char>(false, c&);`
This is what you wanted:
`v := :match_return<*char> = (false, c&);`.
That would work for a Cpp1-authored aggregate, too.
Hopefully Cpp2-authored aggregates still exist in the `main` branch.

**Comment by JohelEGP** [comment]
For the love of aggregates, I suppose it's time to propose `@cpp1_aggregate`.
