### ISSUE TITLE
[BUG]  Explicit constructor prevents default initialization

### ISSUE THREAD

**Issue by MaxSagebaum** [hsutter/cppfront#1151]
This is a follow up on https://github.com/hsutter/cppfront/issues/1146

Issue https://github.com/hsutter/cppfront/issues/1146 works now, but generates a new issue. We are entering C++ weird country now.
Since now the explicit constructor with no arguments is defined, we can no longer write a construction with ` ... = {}` in cpp1.

```
match_return: @struct <Iter> type = {
    matched: bool = false;
    pos: Iter = ();
}


int main(int nargs, char** args) {

    match_return<char*> v1 {};  // Works, as generated by cppfront
    match_return<char*> v2 = {};  // Does not work, used e.g. by std::array.

    match_return<char*> v3 {true, &c};  // Works, as generated by cppfront
    match_return<char*> v4 = {true, &c};  // Does not work, used e.g. by std::array.
}
```
`v2` can not be initialized, because the constructor with no arguments is marked explicit.
```
main.cpp2:11:25: error: chosen constructor is explicit in copy-initialization
    match_return<char*> v2 = {};  // Does not work, used e.g. by std::array.
                        ^    ~~
main.cpp2:5:18: note: explicit constructor declared here
public: explicit match_return();
                 ^
main.cpp2:14:25: error: chosen constructor is explicit in copy-initialization
    match_return<char*> v4 = {true, &c};  // Does not work, used e.g. by std::array.
                        ^    ~~~~~~~~~~
main.cpp2:4:22: note: explicit constructor declared here
    public: explicit match_return(auto const& matched_, auto const& pos_);
                     ^
```

Compiler Explorer reproducer: https://cpp2.godbolt.org/z/xE1nx3n1j

The "easy" fix is to not mark the constructors for `@struct` es explicit. This would also mean constructors with one argument are not explicit, which would allow implicit conversion.

It seems an initializer list constructor is required for `@struct`. :( Any other ideas?

**Comment by hsutter** [comment]
Thanks! Makes sense, for `@struct` those can be `implicit` (the explicit [sic, no pun intended] opt-in in Cpp2). Good catch, thanks for the repro! The code above now compiles.
