### ISSUE TITLE
[BUG] Parse error with template type and initialiser without white space in between

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#1162]
**Describe the bug**
Cppfront reports an error when parsing the following expression, presumably because of the ambiguity of `>=`.
```cpp
vec: std::vector<int>=(1,2,3);
```

**To Reproduce**
Run cppfront on this code:
```cpp
main: () -> int = {
    v1: std::vector<int> = (1,2,3);  // OK
    v2: std::vector<int> =(1,2,3);   // OK
    v3: std::vector<int>=(1,2,3);    // Error
    v4: std::vector<int>= (1,2,3);   // Error
    return 0;
}
```
The error is:
```
error: missing ';' at end of declaration or '=' at start of initializer (at '<')
error: ill-formed initializer (at '{')
error: unexpected text at end of Cpp2 code section (at 'main')
error: parse failed for section starting here
```
[Repro](https://cpp2.godbolt.org/z/6hdb3KhnW) on Godbolt

**Comment by hsutter** [comment]
Thanks!

> presumably because of the ambiguity of `>=`

Yes it's about `>=`, but it's not ambiguous, it really is a `>=` token because of [max munch](https://en.wikipedia.org/wiki/Maximal_munch). A space is required to make it not be a single token.

I wonder what other left-to-right languages do that case?

I just tried Swift:

```swift
var s: Array<Int> = [1,2,3]; // ok

var s: Array<Int>= [1,2,3];  // error: '=' must have consistent whitespace on both sides

var s: Array<Int>=[1,2,3];   // ok
```

Hmm!

**Comment by hsutter** [comment]
Rust allows it:

```rust
let v: Vec<i32> = vec![1, 2, 3]; // ok
let v: Vec<i32>= vec![1, 2, 3];  // ok
```

Today, for similar reasons, cppfront already doesn't treat `>>` and `>>=` as source tokens... they are synthesized from `>` `>` and `>` `>=` where legal.

I could do the same for `>=`. I'll think about it... I think it's a usability issue probably worth fixing. Thanks for the example!

**Comment by hsutter** [comment]
Done, thanks!
