### ISSUE TITLE
[SUGGESTION] Allow concept type constraints with the `_` wildcard (C++ constrained `auto`)

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#1166]
*(I can't find an issue/discussion about this so apologies if I've missed it.)*

**Suggestion**
Allow concept [placeholder type constraints](https://en.cppreference.com/w/cpp/language/auto) in Cpp2 with the `_` wildcard, as an equivalent of constrained `auto` in C++.

I'd like to write the Cpp2 equivalent of the following C++:
```cpp
void print(std::ranges::forward_range auto const& r) {
  // etc
}

std::vector<int> vi = get_data();
print(vi);
```
This works in Cpp2 (see [example](https://cpp2.godbolt.org/z/5d6deEYnY)):
```cpp
print: <Rng>(r: Rng) requires (std::ranges::forward_range<Rng>) = {

}
```
But it reads quite verbose to me compared to the original C++. Something like the following would be closer to the original, I think:
```cpp
print: (r: std::ranges::forward_range _) = {

}
```

**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?**
No

**Will your feature suggestion _automate or eliminate_ X% of current C++ guidance literature?**
No

**Comment by hsutter** [comment]
Thanks, good catch! I see there isn't a similar `forward` algorithm so I just need to adjust this for `move`...

**Comment by hsutter** [comment]
Thanks! I've added `is` constraints on wildcarded parameters and locals.

With the above commit, the following now works (and the last line would be an error if not commented out):

```cpp
print: (r: _ is std::regular) = {
    std::cout << "satisfies std::regular\n";
}

print: (_) = {
    std::cout << "fallback\n";
}

irregular: type = {}

main: () = {
    print(42);
    print(irregular());

    ok : _ is std::regular = 42;
    //err: _ is std::regular = irregular();
}
```

**Comment by bluetarpmedia** [comment]
Nice work Herb!
