### ISSUE TITLE
[BUG] Assertion `!n.declaration->is_function()' failed.

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#1169]
Steps to reproduce:
 - Get latest `cppfront` source code.
 - Compile `cppfront`, `g++ -std=c++20 -o cppfront cppfront.cpp`.
 - Run `cppfront` on this test file:

```cpp
vz:(r:(r))z--
```

Expected result:
 - Compilation success, or nice error message printed.

Actual result:
 - ```cppfront: to_cpp1.h:4278: void cpp2::cppfront::emit(const cpp2::parameter_declaration_node&, bool, bool, bool): Assertion `!n.declaration->is_function()' failed.```
 - `Aborted (core dumped)`

Found by fuzzing, https://github.com/hsutter/cppfront/issues/1131.

**Comment by hsutter** [comment]
Thanks! Please paste the source code directly into the issue, it's better to avoid a pattern of clicking on links to zipfiles (malware potential).
