### ISSUE TITLE
[BUG] Infinite loop with malformed input

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#117]
- Run the tool on file containing malformed data.
 - No command line switches or parameters.
 - The tool is stuck in infinite loop.
 - The input `P:"P` is also available as attachment.

[infinite-loop.txt](https://github.com/hsutter/cppfront/files/10003036/infinite-loop.txt)

**Comment by filipsajdak** [comment]
I love it.

**Comment by filipsajdak** [comment]
I have prepared a fix.
