### ISSUE TITLE
[BUG] Assertion `std::ssize(preprocessor) > 1' failed.

### ISSUE THREAD

**Issue by MarekKnapek** [hsutter/cppfront#1170]
Steps to reproduce:
 - Get latest `cppfront` source code.
 - Compile `cppfront`, `g++ -std=c++20 -o cppfront cppfront.cpp`.
 - Run `cppfront` on this test file:

```cpp
#else#Xt:=private:E##)$##$
```

Expected result:
 - Compilation success, or nice error message printed.

Actual result:
 - ```cppfront: io.h:471: void cpp2::braces_tracker::found_pre_else(): Assertion `std::ssize(preprocessor) > 1' failed.```
 - `Aborted (core dumped)`

Found by fuzzing, https://github.com/hsutter/cppfront/issues/1131.

**Comment by hsutter** [comment]
Thanks! I've also edited this one to paste the source code directly into the issue, to avoid clicking on links to zipfiles (malware potential).
