### ISSUE TITLE
Container `end` dereference check required

### ISSUE THREAD

**Issue by nullicist-aakash** [hsutter/cppfront#1171]
Hi,

Consider the following code:
```
main: () = {
	vec: std::vector = (1, 2, 3);
	p := vec.end();
	p* = 5;
}
```

This code is clearly writing to a memory location which is not allocated to us, but this code compiles in both cpp2 and there is no runtime error in generated cpp code, because it only checks for null pointer:
```
*cpp2::impl::assert_not_null(p) = 5;
```

Is it possible to add a runtime check for dereferencing `end()` in C++?

I'm struggling to think of a runtime check for this situation. We can't determine if it's valid to dereference a container’s iterator (particularly `end()`) without actually performing the dereference. And if we attempt to dereference it to check, the code is already broken if the dereference is invalid.

**Comment by hsutter** [comment]
Thanks! There is no easy way to do this without the iterator knowing which container it came from, and in general we'd want to check more things (such as not incrementing past the end or decrementing before the beginning).

There is active good work in this area though... a prominent example is @ldionne's [libcxx STL hardening](https://lists.llvm.org/pipermail/libcxx-commits/2024-June/084412.html), which I think is being submitted for standardization and then would benefit all STL iterator range safety. My plan is to rely on that work by Louis and friends (thanks again Louis!).
