### ISSUE TITLE
[BUG] Absolute paths no longer work as input

### ISSUE THREAD

**Issue by alexreinking** [hsutter/cppfront#1174]
**Describe the bug**
After the following commit, absolute paths are misinterpreted as unrecognized flags.

https://github.com/hsutter/cppfront/commit/16686c1ce15df4efb0802e96865e39c86be877cb

**To Reproduce**

```
~$ git clone https://github.com/hsutter/cppfront
~$ cd cppfront
~/cppfront$ clang++-19 -o cppfront -O2 -std=c++20 source/cppfront.cpp
~/cppfront$ ./cppfront "$PWD/regression-tests/pure2-enum.cpp2"
/home/alex/cppfront/regression-tests/pure2-enum.cpp2 - unknown compiler flag name (try /help)
```

**Additional context**
N/A

**Comment by sookach** [comment]
I'll have a look

**Comment by sookach** [comment]
Thanks for the bug report! My commit fixes the issue for mac sonoma. Fairly certain it should work on all other platforms, but let me know if you run into any issues.
