### ISSUE TITLE
Pure virtual function with body in documentation?

### ISSUE THREAD

**Issue by roccomoretti** [hsutter/cppfront#1182]
https://github.com/hsutter/cppfront/blob/8060dc42290b16264743d0b9b702d0599d2571bb/docs/cpp2/types.md?plain=1#L83-L84

Is the `{ /*...*/ }` a typo here, or am I missing something which causes it to be "no body"?

**Comment by hsutter** [comment]
Oops, right you are. It should just be `print: (virtual this, msg: std::string);`.

Fixed, thanks!
