### ISSUE TITLE
[BUG] current "exploration" of not allowing default arguments breaks pure mode for functions wanting to use std::source_location

### ISSUE THREAD

**Issue by farmerpiki** [hsutter/cppfront#1189]
Just a sample cpp1 function that can no longer be represented in cpp2 syntax due to lack of default arguments.
If I'm wrong about this and there's a way around this please reply and close the bug, thanks!

void debug_function_name(char const *fn = std::source_location::current().function_name())
{
	std::println(stderr, "calling: {}", fn);
}

**Comment by sookach** [comment]
As far as I'm aware cppfront currently does not support default arguments (sorry), although I don't think it should be too difficult to implement.

**Comment by gregmarr** [comment]
See #75 for discussion of almost this exact case.

**Comment by farmerpiki** [comment]
thanks for the link @gregmarr ... I guess based on that I have to stick to standard cpp syntax for source_location where I need it... guess it's the only good use of default arguments

**Comment by DyXel** [comment]
As a workaround, you can probably use a macro that expands to your arguments + `std::source_location`.

**Comment by hsutter** [comment]
Thanks! When it's time, it's time... default arguments are now supported, and your `source_location` example works (on Cpp1 compilers that have `source_location`):

```cpp
my_function_name: (
    fn: *const char = std::source_location::current().function_name()
    )
= {
    std::cout << "calling: (fn)$\n";
}

main: (args) = {
    my_function_name();
}
//  On MSVC 2022, prints:
//      calling: int __cdecl main(const int,char **)
//  On GCC 14, prints:
//      calling: int main(int, char**)
```
