### ISSUE TITLE
[BUG] Cannot use `as` cast followed by multiplication operator without parens

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#1194]
**Describe the bug**
I'm not sure if this is intended or not, but currently cppfront does not allow an `as` cast followed by a multiplication operator in an expression, since it interprets the `*` for a pointer or prefix dereference.

**To Reproduce**
Run cppfront on this code:
```cpp
main: () -> int = {
    i: int = 1;
    s1:= i as size_t;       // ok
    s2:= i as size_t + 1;   // ok
    s3:= i as size_t - 1;   // ok
    s4:= i as size_t / 1;   // ok
    s5:= i as size_t % 1;   // ok
    s6:= (i as size_t) * 2; // ok
    s7:= i as size_t * 2;   // error: 'T*' is not a valid Cpp2 type; use '*T' for a pointer instead
    return 0;
}
```
[Repro](https://cpp2.godbolt.org/z/q9xsMzahd)

**Comment by hsutter** [comment]
Thanks! Fixing... I think it's just time to retire that 'helpful for Cpp1 coders' error since I'm not sure it comes up that often and it does tend to reject code that's actually okay...
