### ISSUE TITLE
[BUG] ICE when putting a ; after a type definition when there is a newline in the type body

### ISSUE THREAD

**Issue by gregmarr** [hsutter/cppfront#1202]
**Describe the bug**
```
<Compilation failed: cpp2-cppfront: trying to pop an empty stack in rule: (unknown)>
```

**To Reproduce**
```
match_content: type = {
    
};
```

**Additional context**
These produce an error message as expected:
```
match_content: type = {};
```
```
match_content: type = 
{ };
```
```
example.cpp2(1,25): error: Cpp2 does not allow a semicolon after the closing brace of a type definition (at ';')
```

**Comment by gregmarr** [comment]
I found it on CE, maybe it has been resolved now.

**Comment by hsutter** [comment]
Thanks! So far I haven't been able to repro it with current `main`...

**Comment by gregmarr** [comment]
Based on when the issue was filed, CE would have been running [Add usage notes to the docs for ..< and ..=](https://github.com/hsutter/cppfront/commit/e7f4bea3180b20bd37ec4613e827c2daa3135318) e7f4bea3180b20bd37ec4613e827c2daa3135318.

**Comment by gregmarr** [comment]
I just tried locally with that commit, and it works as expected, so it may have been something weird with CE.

**Comment by gregmarr** [comment]
Looks like this might actually be a Compiler Explorer issue.  I found the same error string reported in the Monaco editor repo.  https://github.com/microsoft/monaco-editor/issues/134
