### ISSUE TITLE
[BUG] New clone of repo shows modification to `pure2-regex_10_escapes.cpp.execution`

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#1223]
Tested on Windows 11 and Ubuntu 22.04:

A new, fresh clone of the cppfront repo shows a change to `pure2-regex_10_escapes.cpp.execution`.

Repro:
```
$ git clone https://github.com/hsutter/cppfront.git
$ cd cppfront
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   regression-tests/test-results/msvc-2022-c++latest/pure2-regex_10_escapes.cpp.execution

no changes added to commit (use "git add" and/or "git commit -a")
```

This message also appears in CI regarding the file:
```
warning: in the working copy of 'regression-tests/test-results/gcc-14-c++2b/pure2-regex_10_escapes.cpp.execution', CRLF will be replaced by LF the next time Git touches it
```

However, I'm not convinced the problem is with the line endings because other `.execution` files appear to have CRLF endings.

Instead I'm wondering if there's something in the file itself which is causing a problem. The GitHub preview stops printing the line numbers after [line 38](https://github.com/hsutter/cppfront/blob/main/regression-tests/test-results/msvc-2022-c%2B%2Blatest/pure2-regex_10_escapes.cpp.execution):

![image](https://github.com/user-attachments/assets/1a890b70-91c7-4f56-bc34-303bf0c05052)

I had a look in Notepad++ and it shows the `\f` Form Feed, `\a` Bell and `\e` Esc characters, so maybe that confuses the GitHub preview.

![image](https://github.com/user-attachments/assets/423eaf5f-c0ec-4754-beb3-60c7e71ce71a)

**Comment by MaxSagebaum** [comment]
This regex tests if escapes for special characters are  handled properly. The main problem is the automatic change of the line ending of github. I updated the result file now several times and also got a bug report via mail. 

I think I should just simple remove this test.

**Comment by DyXel** [comment]
For those tests you should probably not output what is being matched but rather if it was matched, and integer ranges.

**Comment by MaxSagebaum** [comment]
I got the idea that I can just sanitize the outputs. I created a branch. https://github.com/hsutter/cppfront/pull/1224

**Comment by hsutter** [comment]
I've been having problems with this file too and I thought my local git was corrupt -- it would not let me discard the "changes" and as a workaround I had to re-commit the file, otherwise I couldn't even change branches.

Whew! It's just the file content, that's good news.

Yes if we could fix this that would be grand. 🙏

**Comment by MaxSagebaum** [comment]
The bugfix branch is ready to merge.
