### ISSUE TITLE
[BUG] Reference docs not visible on mobile devices

### ISSUE THREAD

**Issue by jamadagni** [hsutter/cppfront#1233]
Hello. If I go to https://hsutter.github.io/cppfront/ on my laptop (whether Firefox or Chrome), on the left side pane I see the entries for Cpp2 Reference. However, if I visit the same on either my phone or tablet (whether Firefox or Chrome), I see only the first three entries under Getting Started and not the reference.

![Screenshot_20240818_163516](https://github.com/user-attachments/assets/33122dea-4d67-4829-8bee-43afe7bebae0)
![Screenshot_20240818-163624](https://github.com/user-attachments/assets/446111ba-7b2a-457f-9f40-7f06194903cc)

This had initially led me to think that the documentation contains only the Getting Started section when I first checked on my phone and tablet before trying the same on my laptop. It would be good to fix this soon so others don't get the same wrong impression.

Thanks!

**Comment by farmerpiki** [comment]
I doubt anyone is developing on a phone or tablet... but good point nonetheless if someone is checking the documentation first on a phone or tablet.

**Comment by filipsajdak** [comment]
It works on the iPhone & Safari

![image](https://github.com/user-attachments/assets/3035ea86-91d7-42c8-80aa-9d417d4e83e3)

![image](https://github.com/user-attachments/assets/970b3a00-7ba0-4eb7-acd4-9c62d929a4ce)

![image](https://github.com/user-attachments/assets/d21c8284-5e2d-40e9-bf2d-5484fd25eab6)

**Comment by jamadagni** [comment]
> It works on the iPhone & Safari

Still doesn't seem to show the reference documentation and shows only the Getting Started 3 articles?

**Comment by jamadagni** [comment]
> I doubt anyone is developing on a phone or tablet... but good point nonetheless if someone is checking the documentation first on a phone or tablet.

Somebody who hears about CPP2 and wants to know what it provides should be able to access the full documentation (within reasonable screen size limitations) on mobile devices too. Document is also to attract people, and not just for development time alone.

**Comment by DyXel** [comment]
It's kinda obfuscated, but if you click the "Back" arrow, it goes back to a list where it shows the rest of the documentation.
![image](https://github.com/user-attachments/assets/d9b47bc6-cbab-40a1-a617-466c86122747)
![Screenshot_20240818_183207](https://github.com/user-attachments/assets/93aa281c-53a7-4a93-bad5-f6c83932a336)
![Screenshot_20240818_183223](https://github.com/user-attachments/assets/205f5d4b-175d-4d21-945a-320b8eec7dd5)

**Comment by hsutter** [comment]
Thanks!

Right, there is the back-arrow. I agree it's subtle but I don't know how to make it more visible unfortunately, this is part of the Material for MkDocs experience. It seems related to this issue: https://github.com/squidfunk/mkdocs-material/issues/4938

However, if the main issue is the home page you see when you go to the root of `hsutter.github.io/cppfront`, I could just duplicate the navigation as the home page, instead of starting with the "welcome" sub-page which is currently the home page.

I just pushed this commit (but forgot to mention this bug, sorry): aaa5b72b4bf22dea1486d06017188a4f81fdd31a

Does that help?

(BTW, even on desktop browsers, when the zoom level hides the lhs nav structure a similar problem happens. So this could help also non-mobile users.)

**Comment by jamadagni** [comment]
> I just pushed this commit (but forgot to mention this bug, sorry): [aaa5b72](https://github.com/hsutter/cppfront/commit/aaa5b72b4bf22dea1486d06017188a4f81fdd31a)
> 
> Does that help?

I am not sure I understand that part about the home page and navigation. Anyhow…

My request was for the navigation to link to the full tree structure (whether via submenus or back arrow) no matter what page we are on. Even y'day morning, visiting https://hsutter.github.io/cppfront/ on a mobile device did not show the full navigation but now it does. Thanks!

But I am not sure if this means that for each additional page you create you have to link it in two places. At any rate pl ensure that all pages are accessible from all devices even with future updates. Thanks again!
