### ISSUE TITLE
[SUGGESTION] Two more videos to link in README.md

### ISSUE THREAD

**Issue by jamadagni** [hsutter/cppfront#1237]
It might be worth to link the following two videos in README.md:

“Keynote: The Evolution of C++ - A Typescript for C++” from CppNow 2023 May (which contains some updates after the CppCon 2022 video):
https://www.youtube.com/watch?v=fJvPBHErF2U

“Update on CppFront” from Accu Conference 2024, esp starting from 1:24:26
https://youtu.be/EB7yR-1317k?si=GS3vE6jl6YcJl2F-&t=3866

**Comment by hsutter** [comment]
Thanks!

I think the first one is covered, because the README links to the CppCon 2023 talk which is an updated version  of the CppNow 2023 talk.

I'll go add the second, good suggestion!
