### ISSUE TITLE
[BUG] cppfont 0.7.4 still showing 0.7.3 as version number

### ISSUE THREAD

**Issue by yann64** [hsutter/cppfront#1265]
**Describe the bug**

**To Reproduce**
compile cppfront from released **0.7.4** source package
run : 

> ~> cppfront -version
> 
> cppfront compiler **v0.7.3**   Build 9825:1501
> Copyright(c) Herb Sutter   All rights reserved
> 
> SPDX-License-Identifier: CC-BY-NC-ND-4.0
>   No commercial use
>   No forks/derivatives
>   Note: This license emphasizes that this is a personal
>         experiment; it will be upgraded if that changes

**Comment by hsutter** [comment]
Thanks! Now fixed in `main`.
