### ISSUE TITLE
[BUG] When trying to manually initialize std::array it's considered "use before initialization"

### ISSUE THREAD

**Issue by feature-engineer** [hsutter/cppfront#1282]
**Describe the bug**

assignment to an uninitialized array is considered "use before initialization", Even though nothing is read from the uninitialized array.

**To Reproduce**
The following code fails:
```
    cost: std::array<double, 6>;
    i := 0;
    tmp := v1.data();
    cost[i++] = tmp[0];
    cost[i++] = tmp[1];
    cost[i++] = tmp[2];
    tmp := v2.data();
    cost[i++] = tmp[0];
    cost[i++] = tmp[1];
    cost[i++] = tmp[2];
```
error: local variable cost is used before it was initialized

I would have expected it to be fine to assign values since it's what is initializing the array.

**Comment by DyXel** [comment]
> [!NOTE]
> In your original code there's a double definition of `tmp`, I'll assume you meant 2 differently named variables.

The detection for "use before initialization" is based on local analysis. Cppfront has no way of knowing that calling `cost[]` would only be writing to it, not reading. Plus, its really hard for both compilers and humans to reason about partial initialization.

Is there any constraint that prevents you from writing this? (assuming `v1` and `v2` are subscriptable):
```
cost: std::array<double, 6> = (
    v1[0], v1[1], v1[2],
    v2[0], v2[1], v2[2],
);
```
There are no dead reads or writes here, no uninitialized array, no temporaries. And to top it all off, you get bounds checking for free (you can opt out for performance of course).

If that is not possible, the simplest fix would be to just initialize the array. This will do some dead writes, sure, but any compiler worth its salt will optimize that out.

**Comment by MaxSagebaum** [comment]
The other option is to initialize the array:
```
cost: std::array<double, 6> = ();
```
