### ISSUE TITLE
[BUG] Links to the website in the README don't work

### ISSUE THREAD

**Issue by dffdff2423** [hsutter/cppfront#1331]
**Describe the bug**
The links in the README to the documentation/website do not work.

**To Reproduce**
1. Click on the "Documentation: Available Here" link in the README.
2. Get shown an error 404

**Comment by JohelEGP** [comment]
Seems solved, maybe after commit 6cce2c5b5efd23aa980493e1dc18fe604a3efe7d.

**Comment by dffdff2423** [comment]
yes, that fixed it
