### ISSUE TITLE
[QUESTION] how would we handle cross platform abstractions with out macros?

### ISSUE THREAD

**Issue by pheonixfirewingz** [hsutter/cppfront#136]
Hay I'm I love the new syntax for c++2 but how would we handle cross platform without the pre-processor. For example #if WIN32 > use this, and #if LINUX > use this. Without a mechanism like the pre-processor this would as far as I'm aware make it impossible to write cross platform code. unless there is a newer c++ 20/23/... feature I don't know about? What could be implemented into CPP2 to cater for this area of development projects?

**Comment by SebastianTroy** [comment]
Those defines are defined somewhere in files, either generated by the compiler, shipped with it, or set as arguments to the compile call. All of these cases can use constexpr constants, allowing you to write if constexpr statements in your code for cross platform compatibility.

I believe Herb has also mentioned that he wants expressions to be writable in global scope, allowing such constant evaluated ifs to block out global definitions etc


On 24 November 2022 14:12:35 Luke Shore ***@***.***> wrote:

Hay I'm I love the new syntax for c++2 but how would we handle cross platform without the pre-processor. For example #if WIN32 > use this, and #if LINUX > use this. Without a mechanism like the pre-processor this would as far as I'm aware make it impossible to write cross platform code. unless there is a newer c++ 20/23/... feature I don't know about? What could be implemented into CPP2 to cater for this area of development projects?

**Comment by hsutter** [comment]
@pheonixfirewingz Good question. Further along the lines @SebastianTroy mentioned, my aim is to embrace reflection and generation, the latter meaning generative programming equivalent to (disciplined) source code generation that is part of the language, not a preprocessor outside the language.

I've now added a new design note for this:

- [Design note: Replacing the preprocessor with reflection and generation](https://github.com/hsutter/cppfront/wiki/Design-note:-Replacing-the-preprocessor-with-reflection-and-generation)

Thanks for the question!
