### ISSUE TITLE
[SUGGESTION] Discard the colon opperator ':' after variables and function names

### ISSUE THREAD

**Issue by dmicsa** [hsutter/cppfront#137]
I'm not sure why we need that colon after variables and function.

**Comment by hsutter** [comment]
Thanks for the feedback... I realize not everyone will like `:`, but the goal here is to use a declaration syntax that's unambiguously different from today's as a way to avoid backward source compatibility constraints, and then we should make that syntax simple and consistent (IMO ideal is a single declaration syntax that works consistently everywhere).

Here are two 1-min clips from the talk:
- [Why a distinct second syntax to make a bubble of new code](https://youtube.com/clip/Ugkx62NAxs3v0i7j3fG6dCkWsOShB5hORgOw)
- [Why a single declaration syntax using `:`](https://youtube.com/clip/UgkxB5tOLkJLGwGtTHYnB3F0KMn2zKdHxDq7)
