### ISSUE TITLE
[SUGGESTION] dogfooding taxonomy

### ISSUE THREAD

**Issue by jnorthrup** [hsutter/cppfront#138]
![image](https://user-images.githubusercontent.com/73514/203960233-07537fe3-ab6c-4e75-8d2f-d34dd93b60dc.png)

Dogfooding cpp-front doesn't seem as much tangental as planning and strategy.

Can the project benefit from a punchlist of modules to-be dogfooded  to [im]prove the modular viability of the experiment?

Is there a subsumption hierarchy of things in cpp-front experiment bullets?

Is it reasonable to break out such subsumptions and module concepts for crowd-sourced commentaries individually where the maestro is ambivalent or undecided? 

Does this topic belong in a "discussion" or wiki and not in an issue?

All the best intentions here. cheers!

**Comment by hsutter** [comment]
Thanks! I'm not sure what the request is here... I have a full language design that's partway through implementation, and I welcome people trying out the subset that's implemented (as that continues to grow over the winter) and giving usability feedback on those parts.
