### ISSUE TITLE
[SUGGESTION] Default noexcept and explicit throws statement

### ISSUE THREAD

**Issue by Krzmbrzl** [hsutter/cppfront#144]
**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?**
No

**Will your feature suggestion eliminate X% of current C++ guidance literature?"**
Don't think so. Maybe some parts that deal with where it is important to use `noexcept`.

But, you also stated that you would like to improve toolability for cpp2. And that's where this suggestion is aiming at.

My suggestion comes down to two things
1. Make every function, constructor and destructor `noexcept` by default
2. Add support for a `throws` clause in the function definition. This clause can be used as a simple `throws` keyword, simply to indicate that the function should not be noexcept. Optionally, users can then list concrete exception types that their function may throw

In contrast to what cpp1 does, when given a `throws` declaration, I don't want the compiler to generate code that checks the type of actually thrown exceptions and abort, if that doesn't match the specified exceptions. As far as code generation is concerned, only the fact that a `throws` clause is present or not present is of relevance (deciding whether or not to add a `noexcept` to the generated code). The optional list of exceptions is for tools and documentation only.

So, why not just state which exception types can be thrown in the function's documentation and/or in a comment? Simply, because by the nature of regular text, there will be no uniform format for specifying what kind of exception can be thrown. Therefore, tools can't properly parse this documentation to extract this information.
Having a fixed syntax in the language itself however, forces everyone to use the same syntax to document this information and therefore, tools will be able to pick this information up.

#### What will be gained?

By making functions and constructors `noexcept` by default, I believe that the possible performance of C++ code written by programmers who are not initiated in the gory details of C++, may get a (small) performance boost for free. If for instance they write classes with a move-constructor, they might not immediately think about marking it as noexcept. That however, leads to some (all?) standard library containers to use copy instead of move in many places, which - depending on the actual type - can cause a significant overhead compared to move operations.

The second thing that could be gained via the **opt-in** in-code documentation of what exceptions your function may throw, tools could be used to ensure that every exception that is declared as potentially thrown is also handled, _somewhere_ up the call-tree.
This could effectively be turned into an optional compiler warning that can be enabled based on personal preferences. But if enabled, it could warn you about unhandled exceptions or about you throwing exceptions that are not part of the set of exceptions that you have declared your function may throw.

If we ignore legacy code (that obviously doesn't come with exception specifications) for a moment, assume you are writing a program that does some important work in a production system. Inside your program, you are e.g. calling some library function to do some work for you, but this library function may potentially throw under some circumstances. However, because you didn't read the entire documentation top-to-bottom, you overlooked this and the situation for the throw is rare enough, that you did not catch this in your unit tests. Then the program goes live and some time during the production run that unlikely scenario actually happens and your library function throws. However, you did not expect this and therefore don't handle the error, causing the entire program to abort. Depending on what exactly this program is doing, this could be fatal.

If, on the other hand, the library function explicitly contained this potential exception in its function signature, then your compiler (or some static analyzer) could have warned you about this problem and you could act on that.

Based on the discussion in #111, a few additional comments:
- Not everyone agrees that a function's signature should contain the exception types that it may throw. That is an argument in and of itself, but the main point for the suggestion at hand is: it'd be optional. The only madatory thing, is to declare whether a function may throw _at all_. And I think the latter is always useful (important, actually) to know.
- The suggestion works easily with generic code, too. If you don't know what kind of exceptions may be thrown, just add the plain `throws` keyword (or not, if you know that _no_ exceptions will throw).

----

Potentially a version `throws(constexpr bool)`  might be useful for generic code (exactly how we have `noexcept(constexpr bool)` in cpp1).

----

**Describe alternatives you've considered.**
- Keeping info about what exceptions may be thrown in the function's documentation. The problem with that is illustrated above
- Don't create an explicit list of exceptions at all. This essentially requires access to the source code of all used functions in order to write safe code (which will be tedious) or you'd need some generic catch-it-all blocks, which will mostly be useless in terms of actual error _handling_ as typically those can only log that such an error appeared and (depending on the program architecture) they might get the program back into a valid state (e.g. by discarding the error inducing input). The latter may be sufficient, but probably not in the general case.

**Comment by hsutter** [comment]
Thanks! Yes, I'm a big fan of default `noexcept` -- you'll see that state a few months ago in the commit history, and I [commented it out here for now](https://github.com/hsutter/cppfront/blob/7a8bc1e222c67e70b749ff29e1beb4580682bd3b/source/cppfront.cpp#L2323-L2328) with the intent of bringing it back once I implement EH so it can be a full feature. Right now it would be noisy because we'd emit `noexcept` on a bunch of functions that call Cpp1 code that isn't properly `noexcept`, and I want to eliminate that noisiness before turning this `noexcept` default emission on again.

**Comment by Krzmbrzl** [comment]
That is great to hear!

Looking at how the `throws` keyword is currently handled, it appears as if there is currently no way to allow an optional list of possible exception types after that (for documentation and - more importantly - tooling purposes).
What is your take on my proposal to allow for an explicit exception-type list after `throws`?

**Comment by hsutter** [comment]
> What is your take on my proposal to allow for an explicit exception-type list after `throws`?

The design is as proposed in [P0709](https://wg21.link/p0709), to throw by value of a single well-known small trivially copyable type.

You can find more discussion in #111, my comments are these two:
- https://github.com/hsutter/cppfront/issues/111#issuecomment-1320954300
- https://github.com/hsutter/cppfront/issues/111#issuecomment-1327941638
