### ISSUE TITLE
[SUGGESTION] Make default behaviour for variables const

### ISSUE THREAD

**Issue by dmicsa** [hsutter/cppfront#153]
I know it sounds like heresy, but I feel someone should ask for this too.

I feel that the language will be much easier to understand and less verbose.

**Comment by JohelEGP** [comment]
See https://github.com/hsutter/cppfront/wiki/Design-note:-const-objects-by-default, and https://github.com/hsutter/cppfront/issues/25#issuecomment-1264512921.

**Comment by dmicsa** [comment]
Thx [JohelEGP](https://github.com/JohelEGP)
