### ISSUE TITLE
[SUGGESTION] Review Nim move/reference semantics & macro/pragma features 

### ISSUE THREAD

**Issue by ct-clmsn** [hsutter/cppfront#157]
I'd like to suggest assessing the appropriateness of the Nim reference, move, and heap allocated lifetime semantics for cppfront. Also the macro/pragma system offered by Nim for cppfront.

Looking at the stated goal of cppfront, it seemed appropriate to do a lit review of the current space of systems level languages that aim to provide Python syntactic simplicity, integration with C/C++, performance on par with C/C++, and memory safety. Given what's available in the systems language space, Nim offers a variety of features that overlap with the stated objectives for cppfront.

Nim offers Python adjacent syntax and generates C/C++ code compiled into a library or executable. Users can generate C/C++ on the fly and import generated C/C++ back into the language at compile time.

The language offers Rust style memory semantics (variables are 'const' unless stated mutable) along with non-GC and GC memory management that can conduct lifetime checking on heap allocated data types during compilation (another Rust-like feature or approximation of that feature).

Below are reference materials that show how Nim maps references, pointers/addresses onto the existing C/C++ language semantics.

https://nim-lang.org/docs/manual.html#types-reference-and-pointer-types

https://nim-lang.org/docs/destructors.html

The pragma/macro features maybe useful for experimentation. Users define macros (Nim functions that accept an AST node as the first parameter) and macros are invoked at compile time as a pragma.

https://nim-lang.org/docs/manual.html#pragmas

https://nim-lang.org/docs/macros.html

Hope this is helpful information to the cppfront effort! Also hope this didnt come across as a sale pitch for a particular language - just references to a suite of features that could help with the cppfront effort. Cheers!

**Comment by hsutter** [comment]
Thanks!
