### ISSUE TITLE
[SUGGESTION] Expand on ABI wiki

### ISSUE THREAD

**Issue by rconde01** [hsutter/cppfront#160]
The wiki says:
`Cpp2 is ABI-neutral, but its immunity from backward compatibility constraints presents an opportunity for link-level improvements, not just source-level improvements.`

Can you expand on that? Maybe with some examples for clarity?

**Comment by JohelEGP** [comment]
One might be a different Windows ABI for Cpp2 functions when passing `std::span`. See https://www.reddit.com/r/cpp/comments/p0pkcv/stdspan_is_not_zerocost_on_microsoft_abi/.

**Comment by hsutter** [comment]
@rconde01 Thanks! I've added another short paragraph and used @JohelEGP's example.
