### ISSUE TITLE
[SUGGESTION] Does Cpp2 provide a solution for ABI evolution?

### ISSUE THREAD

**Issue by rconde01** [hsutter/cppfront#161]
"Cpp2 is ABI-neutral, but its immunity from backward compatibility constraints presents an opportunity for link-level improvements, not just source-level improvements."

That's true for Cpp2 wrt to Cpp, but not Cpp2 wrt to itself....right? In other words, you get to make some choices when introducing Cpp2, but are you then locked into those choices and in the same situation we have today? Is there something that could/should be done? I think this is one of the goals of Carbon IIRC.

**Comment by JohelEGP** [comment]
The last paragraph of https://github.com/hsutter/cppfront/issues/145#issuecomment-1329784757 touches on this.

**Comment by hsutter** [comment]
@rconde01 Yes, I aim to tackle versioning, including for things like deprecation and ABI compatible/incompatible (minor/major) changes, and not just for functions but also for types.

@JohelEGP Thanks for pointing to that, and I really should add that also to [Design note: ABI](https://github.com/hsutter/cppfront/wiki/Design-note:-ABI)... done. Thanks for the ping!
