### ISSUE TITLE
[BUG] Cpp2 to Cpp1 lambdas: Using brackets changes the code, explicit void return type is ingored.   

### ISSUE THREAD

**Issue by HALL9kv0** [hsutter/cppfront#162]
**Describe the bug**
I am not sure if this behavior is intended or it is a bug. I would consider it a bug of the cppfront compiler, since it generates cpp1 code which is not expected for the given cpp2 code.

a)The generated cpp1 code is different depending on whether brackets are used in cpp2 lambdas for implicit return types.
b)The generated cpp1 code does not follow the explicitly stated void return type in cpp2 lambdas when brackets are omitted.

**To Reproduce**

**cpp2 code**

```
     // cpp2 without brackets, implicit return - cpp1 is as expected
    f1 := :(inout x: _)=x+=1;


    // cpp2 with brackets, implicit return - cpp1 has no return
    f2 := :(inout x: _)={ 
       x+=1;
    };

    // cpp2 without brackets, exlpicit no return - cpp1 has return
    f3 := :(inout x: _)-> void= x+=1;
    

    // cpp2 with brackets, explicit no return - cpp1 is as expected
    f4 := :(inout x: _)-> void={ 
       x+=1;
    };

```

**cppfront output**

```
    // cpp2 without brackets, implicit return - cpp1 is as expected
    auto f1 { [](auto& x) { return x += 1; } }; 


    // cpp2 with brackets, implicit return - cpp1 has no return
    auto f2 { [](auto& x){
       x += 1;
    } }; 

    // cpp2 without brackets, exlpicit no return - cpp1 has return
    auto f3 { [](auto& x) { return x += 1; } }; 


    // cpp2 with brackets, explicit no return - cpp1 is as expected
    auto f4 { [](auto& x){
       x += 1;
    } }; 
```
Example code: https://godbolt.org/z/9hTEoWdYs
1. Command lines including which C++ compiler you are using

cppfront compiled with gcc -std=c++20
cpp2 example compiled with cppfront  -p -s -a

2. Expected result - what you expected to happen

a) f1 and f2 in cpp2 should compile to the same cpp1 syntax of f1. 
b) f3 and f4 in cpp2 should compile to the same cpp1 syntax of f4. 

3. Actual result/error

a) Using brackets completely changes the generated lambda function. Similarly to cpp1 syntax (i.e for, if) in which omitting brackets doesn’t have any effect in “one-liners”, in cpp2 syntax omitting them should not change the expected output code.

b) When the user explicitly declares void as the return type, he expects the lambda to not return. Currently, when omitting the brackets, the compiler ignores the explicit void return type.

4. Additional context

In the case of a), even though this difference on the generated cpp1 lambdas might be intentional, it is not intuitive for cpp programmers. If so, then this is not a bug, but it can be used as a suggestion.
In the case of b), ignoring an explicitly declared void return type, should be treated as a bug. When explicit, using brackets or not should not change the generated cpp1 lambda return type.

P.S Amazing work, cpp2 syntax is the future of cpp! No need for a new language, let's build on the amazing tools of cpp.

**Comment by hsutter** [comment]
Thanks for the kind words, and for the bug report!

Yes you've found a bug, fixing now... when the return type is stated explicitly, we should use it!

As for the design intent, there are two parts of the current design in play here:

1) The default function return type, when not specified explicitly, is:
    - `-> void` for a named function (briefly: because deduced exposes implementation detail and would not allow order-independence) and
    - a deduced return type for a local function (briefly: because local uses don't need to worry about exposing implementation detail and don't need to worry about order-independence, and they usually naturally want a deduced return type)

2) A non-braced return expression (e.g., a function defined as `= expr;`) means:
    - `= { expr; }` if the return type is `void`
    - `= { return expr; }` otherwise (if the return type is specified or deduced) ((yes, I know, insert the usual comment about "if `void` was regular..." here :) ))
