### ISSUE TITLE
[SUGGESTION] Remove/mark unsafe raw-pointer/unique_ptr conversions (safety, optimizability)

### ISSUE THREAD

**Issue by fknauf** [hsutter/cppfront#163]
Since in C++2 there is no raw new/delete and all heap memory is associated with an RAII anchor from the moment it is allocated, the ability to convert raw pointers to unique_ptr (or shared_ptrs) is unnecessary and fraught with danger. Consider the following piece of C++2 code that currently compiles without warning and crashes at runtime:

```
main: () -> int = {
    f := new<int>(0);
    g := new<int>(1);

    g.reset(f.get());
}
```

or the following memory leak:

```
main: () -> int = {
    f := new<int>(0);
    g := f.release();
}
```

Relevant guidance R.23 could be eliminated if raw-pointer constructors, assignments, `reset`, and (especially) `release` were removed / gated behind an "unsafe" designation (I'm referring here to the pie-in-the-sky idea of https://github.com/hsutter/cppfront/wiki/Design-note:-Unsafe-code ). In general this affects all guidance that tells us to avoid raw owning pointers because it removes the ability to get them from unique_ptrs.

It would also improve optimizability by compilers because the inability to construct a unique_ptr from a raw pointer would guarantee that the raw pointers in two distinct unique_ptrs can never alias, that they can never overlap with the range managed by a `std::vector`, and many others. These are all things that are true in reasonably-written C++ code today, but compilers cannot assume that all code they encounter is reasonable. Data independence is therefore desirable to enforce at a language level where it is reasonably possible, and I believe this is the case here. Granted that this reward will only be reaped by native C++2 compilers down the line iff they know that all involved code respects this guarantee, so it could in the worst case only apply to pure C++2 projects without unsafe components. 

Would this change remove options to express ourselves that we actually want to be there?

I do not believe this to be the case, since all reasonable use of unique_ptrs raw-pointer constructors, assignments, and raw-pointer `reset` require an owning raw pointer, and we would like to eliminate those anyway. If we consider anything that gives us a raw owning pointer unsafe, then these functions are only ever required in an unsafe context. `release` in particular has "DO NOT USE THIS" in bright red letters written all over it precisely because it turns a nice unique_ptr object into a not-nice owning raw pointer.

**Comment by switch-blade-stuff** [comment]
I think this should be the end-goal, although it would require either additional support from the STL to identify these features as unsafe (via an extension attribute perhaps?), or additional C++ compiler tooling (ex. static analysis to detect owning eaw pointers, etc.), which I think is a bit out of scope for the current state of cppfront as a cross-compiler/translator.

**Comment by hsutter** [comment]
Thanks, this is a good point but part of two other things that are later in the project for Cpp2:
- the Lifetime static analysis (see [README.md > Lifetime safety](https://github.com/hsutter/cppfront#2015-lifetime-safety) for details and links)
- recognizing certain functions in the standard library as unsafe or problematic

So I plan to address things like this, but not at this stage. Thanks!

**Comment by fknauf** [comment]
Makes sense. For now I'm happy if this is on your radar. :)

My broader hope here is that language safety features can enhance optimizability because guarantees for the programmer are also guarantees for the compiler. I'd not compromise safety for optimizability, but I suspect there's more bang for our collective buck to be had if optimization is kept in mind as a second-class citizen.

Also, I'm working on a way to estimate what performance gains one could expect if this source of aliasing could be eliminated. Once I have something to show and if you're interested, I'll come back with an update.
