### ISSUE TITLE
[QUESTION] All by default are pointers and passed by reference?

### ISSUE THREAD

**Issue by PaTiToMaSteR** [hsutter/cppfront#167]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/3490937/208442822-a390894c-5667-4a8a-857c-a959ec926131.png">

Thanks god and @hsutter for this! My background is 20 years of video game development creating engines and currently using UE5. 

Straight to the point, I saw what I marked in the image (pointers and reference everywhere) as default behavior from his coding. I think one of the things C# made right was: all is a pointer, always is passed by reference (but basic types int, bool, etc.), JavaScript kind of too. Should be the default behavior in cpp2 also?

in<T> in cpp2util.h as far I understand is passing all by value so copying in every call if unless "is big" and it's T const&
<img width="673" alt="image" src="https://user-images.githubusercontent.com/3490937/208445884-f4dbe811-488a-4f41-8422-590c96f75459.png">

I think a core value of C++ is that is fast, so IMO should be the default, If not we fall again in "is like this unless; 1,2,3,4,5,6..."

Thanks for the answer in advance.

**Comment by leejy12** [comment]
I'm not sure what you're suggesting here. `cpp2::in<T>` already achieves what you're suggesting: the default behavior is pass by reference (`T const&`), but is pass by value (`T const`) for "trivial" types.

And as for the demo code, it seems to be about bounds checking and pointer/iterator safety, hence the numerous usages of `*` and `&`.

**Comment by PaTiToMaSteR** [comment]
Thanks for the clarification, however I think my explanation might be better to show the case. For clarity I really don't think we need to be adding "*" and "&" everywhere. I bet the problem that makes the writing less clear is the print_and_decorate or we need the parser to do some work for us to make the code cleaner for the end user.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3490937/208487360-cc90291a-7f35-4802-8690-9ffcab24b13b.png">
first


SLIDES
```
...
{
	first: *std::string = words.front()&;
	second: *std::string = words.front()&;

	print_and_decorate(first*);
}

print_and_decorate: (thing:_) =
	std:cout << ">> " << thing << '\n';
```

I THINK IS CLEARER for the end user
```
...
{
	first: std::string = words.front();
	second: std::string = words.front();

	print_and_decorate(first);
}

```

**Comment by PaTiToMaSteR** [comment]
Thanks for the clarification, however I think my explanation might be better to show the case. For clarity I really don't think we need to be adding "*" and "&" everywhere. I bet the problem that makes the writing less clear is the print_and_decorate or we need the parser to do some work for us to make the code cleaner for the end user.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3490937/208487360-cc90291a-7f35-4802-8690-9ffcab24b13b.png">
first


SLIDES
```
...
{
	first: *std::string = words.front()&;
	second: *std::string = words.front()&;

	print_and_decorate(first*);
}

print_and_decorate: (thing:_) =
	std:cout << ">> " << thing << '\n';
```

I THINK IS CLEARER for the end user
```
...
{
	first: std::string = words.front();
	second: std::string = words.front();

	print_and_decorate(first);
}

```

**Comment by PaTiToMaSteR** [comment]
Actually, **my bad**, now using it at compile explorer that example shown something that is forbidden to do :)
great, coz I thought was terrible idea xD apologies for the confusion!
