### ISSUE TITLE
[SUGGESTION] Can the type information be captured implicitly in the as-is inspect expression when a clause is matched?

### ISSUE THREAD

**Issue by fecjanky** [hsutter/cppfront#168]
Hey,

From example:
https://github.com/hsutter/cppfront/blob/main/regression-tests/pure2-inspect-expression-in-generic-function-multiple-types.cpp2#L26

```cpp
inspect x -> std::string {
            is int = "integer " + std::to_string(x as int);
            is std::string = '"' + x as std::string + '"';
            is _   = "not an int or string";
        };
```

Can this be simplified to snippet below with an implicit `as <matching T from is expression> ` attached to all occurrence of the variable name ? E.g: snippet below should generate the same C++ code as the one above

```cpp
inspect x -> std::string {
            is int = "integer " + std::to_string(x as int);
            is std::string = '"' + x + '"';  // <<< should be equivalent to  '"' + x as std::string + '"' in this scope;
            is _   = "not an int or string";
        };
```

Thanks & BR,

Ferenc

**Comment by JohelEGP** [comment]
The paper has something like that:
```C++
inspect (x) {
  [a,_] is [_,0] || // top-level || sugar
  [_,a] is [0,_] => result(a);
  // ...
}
```

See 3.3.1 from https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2392r2.pdf:
> names1 is Foo => result
> names2 if Cond => result
>   ... => result
> namesN as Bar => result

**Comment by hsutter** [comment]
Yes, but you would say `as` not `is` which makes it clear you're requesting a type conversion (note this is not yet implemented in cppfront), and you'd declare a new name for the result. For example, in the paper @JohelEGP linked, section 3.4.6 has examples like this (as a proposed extension to Cpp1 syntax):

```
void f1(variant<int,string> const& x) {
    inspect (x) {
        s as string => cout << "string \"" + s + "\"";
          is _      => cout << "not a string";
    }
}
```

In Cpp2 syntax it would look more like this (again, note `as` in that position is not yet implemented):

```
f1: (x: variant<int,string>) = {
    inspect x {
        s: as string = cout << "string \"" + s + "\"";
           is _      = cout << "not a string";
    }
}
```

The name `x` itself wouldn't change type. I considered (but disliked) implicitly invoking a conversion and getting a different type in the `inspect` alternative; that was suggested but it would be implicitly injecting a shadowing declaration.
