### ISSUE TITLE
[BUG] Compilation fails on current master branch

### ISSUE THREAD

**Issue by userxfce** [hsutter/cppfront#173]
command:

mkdir -p /temp/cppfront-git && cd /temp/cppfront-git && git clone https://github.com/hsutter/cppfront.git && cd cppfront/source && g++ cppfront.cpp -std=c++20 -o cppfront

results in:

Cloning into 'cppfront'...
cppfront.cpp:656:23: error: declaration of 'const cpp2::token* cpp2::cppfront::arg_info::token' changes meaning of 'token' [-fpermissive]
656 |         token const*  token = nullptr;
       |                       ^~~~~
 In file included from parse.h:21,
                  from sema.h:21,
                  from cppfront.cpp:18:
 lex.h:191:7: note: 'token' declared here as 'class cpp2::token'
   191 | class token
       |       ^~~~~

**Comment by filipsajdak** [comment]
What compiler are you using?

**Comment by hsutter** [comment]
@userxfce Thanks! You must be compiling with gcc or Clang with `-Wall -Wextra` plus turning warnings into errors with `-Werror`, which should be fine but this week I added some code that triggers the above warning.

Fixed by the commit above, it now compiles cleanly again under `-Wall -Wextra`.

**Comment by userxfce** [comment]
@filipsajdak fixed already, but for reference:

$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

@hsutter fix confirmed & thanks!
