### ISSUE TITLE
operator as implementation restricted unnecessarily

### ISSUE THREAD

**Issue by kelbon** [hsutter/cppfront#174]
https://github.com/hsutter/cppfront/blob/2f37277d3d4844ef5a904213409ac4c657f6a858/include/cpp2util.h#L695

https://godbolt.org/z/7vqj7fnvb

```c++
template<typename... Ts, typename T>
requires (std::equality_comparable_with<Ts&, T&&> || ...)
constexpr bool operator==(std::variant<Ts...>& v, T&& val) {
  auto vtor = [&]<typename U>(U& v) {
      if constexpr(std::equality_comparable_with<T&&, U&>)
        return v == std::forward<T>(val);
      else
        return false;
  };
  return std::visit(vtor, v);
}
```
Anyway it is ambiguous how to compare variant and value:
type + value or just value? what if different Ts... is variant compatible with value and have different results? Etc

**Comment by switch-blade-stuff** [comment]
> type + value or just value? what if different Ts... is variant compatible with value and have different results? Etc

Since variant always stores only 1 of its types, we just need to compare with the stored value (and check if they are equality comparable).

**Comment by kelbon** [comment]
> > type + value or just value? what if different Ts... is variant compatible with value and have different results? Etc
> 
> Since variant always stores only 1 of its types, we just need to compare with the stored value (and check if they are equality comparable).

variant<MyString, MyStringNoCaseSensitive> var;
var == "hello world";
Ambiguity, what type with must compare with ?

**Comment by switch-blade-stuff** [comment]
> what type with must compare with

The type currently stored by the variant.
If it is `MyString`, compare with `MyString`, if it is `MyStringNoCaseSensitive`, compare with `MyStringNoCaseSensitive`.

**Comment by kelbon** [comment]
> > what type with must compare with
> 
> The type currently stored by the variant. If it is `MyString`, compare with `MyString`, if it is `MyStringNoCaseSensitive`, compare with `MyStringNoCaseSensitive`.
As i think its not an intuitive code
var is "hello world"
Better to explicitly var is String and var as String == "hello world"

**Comment by hsutter** [comment]
@switch-blade-stuff is correct about the current intent and rationale. If the question is "does the variant hold this value?" then my thinking is that the answer should be the same as `==` would report.

I understand not everyone may have the same mental model, but it's an experiment and we'll see what the feedback is -- including this feedback as a data point toward that, thanks!
