### ISSUE TITLE
c_raii undefined behavior in dtor after move

### ISSUE THREAD

**Issue by kelbon** [hsutter/cppfront#176]
https://github.com/hsutter/cppfront/blob/2f37277d3d4844ef5a904213409ac4c657f6a858/include/cpp2util.h#L1007

Dctor invokes nullptr if c_raii object was moved.
Also its inefficient to store function pointer and not functional object + [[no_unqiue_address]]

**Comment by hsutter** [comment]
Good point, simplest is to make it not movable. Thanks!
