### ISSUE TITLE
[BUG] Build break - std::strlen include missing

### ISSUE THREAD

**Issue by mattgodbolt** [hsutter/cppfront#180]
Building the code as of 4f7e8b2b42dd58c8071513804ab40a90bc05be84 yields:

```
  + /opt/compiler-explorer/gcc-12.1.0/bin/g++ -O2 -std=c++20 -static -o /opt/compiler-explorer/cppfront-trunk-20221228/cppfront source/cppfront.cpp
  In file included from source/parse.h:21,
                   from source/sema.h:21,
                   from source/cppfront.cpp:18:
  source/lex.h: In constructor 'cpp2::token::token(const char*, cpp2::source_position, cpp2::lexeme)':
  source/lex.h:214:35: error: 'strlen' is not a member of 'std'; did you mean 'mbrlen'?
    214 |       , count   {as<int16_t>(std::strlen(sz))}
        |                                   ^~~~~~
        |                                   mbrlen
  source/lex.h:214:9: error: cannot convert '<brace-enclosed initializer list>' to 'int16_t' {aka 'short int'} in initialization
    214 |       , count   {as<int16_t>(std::strlen(sz))}
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

when building on Linux ( https://github.com/compiler-explorer/compiler-workflows/actions/runs/3790711271/jobs/6445543324 )

**Comment by hsutter** [comment]
Thanks! Fixed.

I can't tell you how much I'm looking forward to self-hosting cppfront in Cpp2 next year, and never again have to think about the "did I remember all the right std:: #includes so what happens to compile on this compiler will still work portably even if I forget to check because the std:: include graph is nonportable" whack-a-mole.

**Comment by mattgodbolt** [comment]
Thanks @hsutter :) And Happy Holidays to you! :) Hope to catch you in 2023 sometime (maybe Cpp2 will be self-hosting then too!)
