### ISSUE TITLE
[SUGGESTION] The equal symbol at the beginning of all assignment operators

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#182]
Currently, C++ has the following assignment operators:

```
a = b
a += b
a -= b
a *= b
a /= b
a %= b
a &= b
a |= b
a ^= b
a <<= b
a >>= b
```

If we move the equal symbol from the end to the beginning of all assignment operators, then we will have:

```
a = b
a =+ b
a =- b
a =* b
a =/ b
a =% b
a =& b
a =| b
a =^ b
a =<< b
a =>> b
```

It will increase readability (the first symbol is important), reading from left to right, `a =* b` means `a` is equal to the result of `*` operation on itself and `b`. This definition is consistent with relational operators, `a >= b` means `a` is greater-than or equal to `b`, but `a =>> b` means `a` is equal to the result of `>>` operation on itself and `b`. Simply if `=` is the first symbol, then the operation is assignment except `==`. In addition, `<<=` and `>>=` **relational operators** can be introduced in the future.

On the other hand, C++ programmers are not familiar with these new operators (for example `=<<` operator), but it's easy to learn.

**Comment by leejy12** [comment]
How will you disambiguate `a =+ b` and `a = +b`? Similarly, `a =- b` and `a = -b`.

With your proposal, disambiguating code like `a=-b` will require whitespace around the operators. And TBH, I don't think the operators we currently have (`+=`, `>>=` etc.) aren't that confusing to read.

**Comment by msadeqhe** [comment]
> How will you disambiguate `a =+ b` and `a = +b`? Similarly, `a =- b` and `a = -b`.

Let me answer your question with a question: How will you disambiguate `a *= b` and `a* = b` in C++ syntax 2? Anyway, if there is a whitespace between `=` and `+` then they are two operators otherwise, which means `=+` is an assignment operator but `= +` are two different operators.

**Comment by switch-blade-stuff** [comment]
I am not a fan of mandatory whitespace around operators, but there is a different solution that is already in use, which is operator precedence.

Although, IMO the assignment operators are not really in any way confusing, and considering that most other languages use the `+=`, `-=`, etc. form, changing the syntax might create further confusion.

Also, `a += b` can be read as "sum of a and b assigned to a".

**Comment by msadeqhe** [comment]
Yes, that's right, and `+=` operator is good enough, and most other languages use prefix unary operators, but C++ Syntax 2 uses postfix unary operators, and if `=+` is a more consistent operator, C++ Syntax 2 can use it instead of `+=`. I mean if there is a choice, it can be explored and experimented in C++ Syntax 2?

**Comment by hsutter** [comment]
I'm not sure the `@=` order is inconsistent now, and changing it to `=@` doesn't seem to solve a known complexity or usability or toolability problem in today's C++, does it? And I'm trying to be strict with myself to stick to addressing those... see [this 1-min clip from the talk video](https://youtube.com/clip/Ugkx7dQt-fMg4tewc9wtoktrtTIeKMAgCrIT).

So I'm going to close this for now, but if you think it does solve a complexity or usability or toolability problem, please reopen and fill out the full [SUGGESTION template](https://github.com/hsutter/cppfront/issues/new?assignees=&labels=suggestion&template=suggestion.md&title=%5BSUGGESTION%5D+) which asks for additional rationale and information.

Thanks!
