### ISSUE TITLE
[BUG] Duplicate const-qualifiers should be rejected.

### ISSUE THREAD

**Issue by leejy12** [hsutter/cppfront#184]
Cppfront compiles
```
main: () -> int = {
    ccx : const const int = 42;
}
```
into (boilerplate omitted)
```
[[nodiscard]] auto main() -> int{
    int                 const const ccx { 42 }; 
}
```

[[dcl.type.cv]](http://eel.is/c++draft/dcl.type.cv) says each [cv-qualifier](http://eel.is/c++draft/dcl.decl.general#nt:cv-qualifier) shall appear at most once in a [cv-qualifier-seq](http://eel.is/c++draft/dcl.decl.general#nt:cv-qualifier-seq)[.](http://eel.is/c++draft/dcl.type.cv#1.sentence-2)

Interestingly, GCC rejects double const whereas clang and MSVC only give warnings. https://godbolt.org/z/9EbbE9d3n

To be Standards-compliant, I think cppfront should reject this code. The same argument applies to `volatile`, but it's not supported yet.

**Comment by hsutter** [comment]
What timing... I just saw this, about half an hour after checking in commit 9ddc2501d2926fbbec08c62635f11ec63d7b5140 which among other things diagnoses exactly this case... the above code now gives the error message `consecutive 'const' not allowed`.

Thanks!

> The same argument applies to `volatile`, but it's not supported yet.

Cpp2 won't allow `volatile T` using a volatile keyword, it will instead spell it like a type as `alien_memory<T>`. But yes, it's not implemented yet.
