### ISSUE TITLE
[SUGGESTION] optional right-hand typing

### ISSUE THREAD

**Issue by cindRoberta** [hsutter/cppfront#186]
### Example:
```c
sum: (a: int, b: int) -> int = (a: int, b: int) -> int {
  return a + b;
}
```

PS.: like a rustacean, I'd prefer `||` instead `()`

**Comment by hsutter** [comment]
What is it you want to express?

Cpp2 does allow this

```
sum: (a: int, b: int) -> int = {
  return a + b;
}
```

and this

```
sum := :(a: int, b: int) -> int = {
  return a + b;
};
```

I'm going to close this for now, but if this is more than a syntax suggestion please reopen using the [SUGGESTION] template and fill in the sections, that would help me understand what you want to achieve. Thanks!

**Comment by cindRoberta** [comment]
> What is it you want to express?
> 
> Cpp2 does allow this
> 
> ```
> sum: (a: int, b: int) -> int = {
>   return a + b;
> }
> ```
> 
> and this
> 
> ```
> sum := :(a: int, b: int) -> int = {
>   return a + b;
> };
> ```
> 
> I'm going to close this for now, but if this is more than a syntax suggestion please reopen using the [SUGGESTION] template and fill in the sections, that would help me understand what you want to achieve. Thanks!

I think it would be cleaner if the typing was closer to Rust's closure, example in Rust:
```rust
let sum: fn(a: i32, b: i32) -> i32 = |a: i32, b: i32| -> i32 {
  a + b
};
```

**Comment by SebastianTroy** [comment]
I'm not sure cleaner is the right word for rusts syntax. The given example uses more words to say the same thing, and repeats the variable names and types. Cleaner would to my mind imply removing something. Perhaps I'm missing something and there's a benefit not demonstrated in such a simple example?


On 29 December 2022 21:09:51 cindRoberta ***@***.***> wrote:

What is it you want to express?

Cpp2 does allow this

sum: (a: int, b: int) -> int = {
  return a + b;
}


and this

sum := :(a: int, b: int) -> int = {
  return a + b;
};


I'm going to close this for now, but if this is more than a syntax suggestion please reopen using the [SUGGESTION] template and fill in the sections, that would help me understand what you want to achieve. Thanks!

I think it would be cleaner if the typing was closer to Rust's closure, example in Rust:

let sum: fn(a: i32, b: i32) -> i32 = |a: i32, b: i32| -> i32 {
  a + b
};

**Comment by cindRoberta** [comment]
@hsutter  @SebastianTroy in the end, for this case, it's Rust syntax versus Go syntax and both are good, but why, in this case:

```c
sum := :(a: int, b: int) -> int = {
  return a + b;
};
```

there are : and = on value, why not?
```c
sum := (a: int, b: int) -> int {
  return a + b;
};
```
or
```c
sum := :(a: int, b: int) -> int {
  return a + b;
};
```

**Comment by hsutter** [comment]
Because all Cpp2 declarations are of the form `name : kind = statement`. I strongly want to keep that consistency.
