### ISSUE TITLE
[SUGGESTION] ::std:: vs std:: usage questions

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#191]
In C++ writing <code>std::vector</code> produces an error if something like
<pre>
namespace my {
namespace std {
}}
</pre>
is visible. I therefore always write  <code>::std::vector</code> or <code>using namespace ::std</code>.

Experimenting with <code>cppfront</code> I saw that both <code>::std::vector</code> and <code>std::vector</code> are legal pure Cpp2 syntax (and passed through unchanged), but <code>using namespace ::std</code> is Cpp1.

Also  <code>cppfront</code> itself produces e.g. <code>std::move</code> in <code>pure2-stdio.cpp</code>, which will not compile if something like the above is there.

I have the following questions:
- Should I write <code>::std::vector</code> or <code>std::vector</code> in pure Cpp2?
- Will there be something like <code>using namespace ::std</code> in pure Cpp2?
- Should <code>cppfront</code> output <code>::std::move</code> instead of <code>std::move</code>?

**Comment by hsutter** [comment]
Good question. [The standard reserves only top-level namespaces that start with `std` possibly followed by digits.](https://eel.is/c++draft/namespace.future) So technically such code is legal.

That said, there's so much code out there that says `std::vector` and `std::move` (not `::std::vector` or `::std::move`) that making a nested namespace named `std` would be quite unwise.

I just checked:
- the [Microsoft GSL implementation](https://github.com/microsoft/GSL/)
- Scott Meyers' _Effective C++ 3rd ed._, _More Effective C++_, _Effective STL_, and _Effective Modern C++_
- Bjarne Stroustrup's _A Tour of C++_

and all of them have lots of `std::` and not a single hit for `::std`. I think that's fairly typical in my experience. If anyone does have a nested namespace named `std` that causes problems for code that doesn't write `::std`, it will cause problems for all major existing C++ code (and they would likely go change their namespace name).

To answer your questions:
- Unchanged from Cpp1. It's very common to write `std::`, and extremely uncommon to write `::std::`. I wouldn't bother.
- Yes there will be something like `using namespace` in pure Cpp2.
- I could, but I'm inclined not to change this unless we encounter real world code that has a problem with this.

Good question though! So for now I'm going to close this as resolved, but anyone feel free to reopen it if we find real world code that needs the extra `::`.
