### ISSUE TITLE
[BUG] using out parameter in for-loop lambda generates uncompilable code

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#211]
The current implementation of cppfront compiles the below code:
```cpp
main: () -> int = {
    xs : std::vector<std::unique_ptr<int>> = ();
    xs.resize(2);

    for xs do :(out x:_) = {
        x = new<int>(0);
    }
}
```
To (skipping boilerplate):
```cpp
[[nodiscard]] auto main() -> int{
    std::vector<std::unique_ptr<int>> xs {  }; 
    CPP2_UFCS(resize, xs, 2);

    for ( auto&& cpp2_range = xs;  auto& x : cpp2_range ) {
        x.construct(cpp2_new<int>(0));
    }
}
```
And when compiled gives an error:
```
../tests/bug_out_in_for.cpp2:6:11: error: no member named 'construct' in 'std::unique_ptr<int>'
        x.construct(cpp2_new<int>(0));
        ~ ^
1 error generated.
```

Changing it from `out` to `inout` solves the issue.

### Expected

I wonder if such a construct was planned. I wanted to create a for loop that should only write to elements. If that is accidental functionality, it may be forbidden by cppfront with a proper error message. 

If it should work, then it requires a fix to compile correctly.

**Comment by filipsajdak** [comment]
I have been playing with other passing styles in for-loop thinking if there is a use case for each of them:

* `in` - (default) read-only iteration,
* `copy` - making possibility to modify an element without changing the original value, 
* `inout` - read-write iteration, 
* `out` - write-only iteration? 
* `move` - destructing iteration (iterate over elements by moving them out of a container), 
* `forward` - (did not find a use case for that - maybe something in generic functions),

Do you think it makes sense?

**Comment by hsutter** [comment]
Thanks, I should flag that as not yet implemented.

I don't plan to implement this soon, but yes it's intended in the future -- [d0708](https://github.com/hsutter/708/blob/main/708.pdf) mentions this in section 1.4.

**Comment by filipsajdak** [comment]
I need to study all your papers and not ask unnecessary questions.

**Comment by hsutter** [comment]
No worries! We can't read all the papers, and others will also have similar questions and so it's good to write down answers / links to the answers.

This was also a good question because it showed I should give a better diagnostic to reject the unsupported code and not just let it miscompile. Thanks!
