### ISSUE TITLE
[BUG] as casts are all const

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#215]
As-casts take casted variables by const reference that make them return const reference types.

That makes the code below:
```cpp
process: (inout s : std::string) = {
    s += " World!";
}

process: (in s : std::string) = {
    std::cout << "Unable to edit: " << s << std::endl;
}

main: () -> int = {
    v : std::variant<std::string, int, double> = ("Hello");
    v_const : const std::variant<std::string, int, double> = ("Yo!");

    process(v as std::string);              // call on lvalue
    std::cout << "v = '(v)$'" << std::endl;

    process(v as std::string);              // call on rvalue (move on last use)
    std::cout << "v = '(v)$'" << std::endl;

    process(v_const as std::string);        // call on const lvalue
    std::cout << "v_const = '(v_const)$'" << std::endl;

    process(v_const as std::string);        // call on rvalue (move on last use)
    std::cout << "v_const = '(v_const)$'" << std::endl;
}
```
return
```
Unable to edit: Hello
v = 'Hello'
Unable to edit: Hello
v = 'Hello'
Unable to edit: Yo!
v_const = 'Yo!'
Unable to edit: Yo!
v_const = 'Yo!'
```

### Expected

In the case of `std::variant`, I would like to have the possibility to replace calls to `std::get<std::string>(v)` with `v as std::string`, and it should produce:
```
v = 'Hello World!'
v = 'Hello World! World!'
Unable to edit: Yo!
v_const = 'Yo!'
Unable to edit: Yo!
v_const = 'Yo!'
```

This is not possible because as-casts returns const reference.

There is another bug: `as_()` functions return `auto` and should `decltype(auto)`.

**Comment by hsutter** [comment]
Good point. When customizing `as` I've aimed to enable following the API design (and the usability) of the type we're customizing for, in this case `variant`, and its `get` does a four-overload dance: https://en.cppreference.com/w/cpp/utility/variant/get

I've always thought `const&&` is dubious so I'll try skipping that one, and just do the `const&`, `&`, and `&&` ones.
