### ISSUE TITLE
[question] ABI?

### ISSUE THREAD

**Issue by rconde01** [hsutter/cppfront#22]
Not sure if you want these types of discussions here...but here goes nothing. I really like a lot about this effort. However, unless I'm missing something, it does not address the problem of ABI breaks in C++. Now, fixing many problems is better than fixing no problems...but it seems like a solution that will (paraphrasing) "keep C++ relevant for the next 30 years" needs to solve that problem. Will cpp2 introduce anything to address that...or does it ignore it?

**Comment by switch-blade-stuff** [comment]
Technically, C++ already has such feature, albeit it is not widely used and does not solve *all* issues.
`inline namespace` allows you to separate your ABI versions into different "hidden" namespaces, as is already happening with `basic_string` and the deprecated copy-on-write ABI.

**Comment by hsutter** [comment]
Good question. ABI is orthogonal. However, having a "bubble of new code" that doesn't exist today can give the opportunity to make ABI choices.

**Comment by hsutter** [comment]
I should [add this to the design notes... done](https://github.com/hsutter/cppfront/wiki/Design-note%3A-ABI).

**Comment by rconde01** [comment]
That's a good start - would good to expand.

1. Are there language features for specifying an ABI? What do they look like?
2. You mention "link compatibility"...would be good to go over the types of ABI compatibility and what cpp2 could and could not enable. e.g. Can you "fix" unique_ptr in cpp2?
3. Can you do anything re: ABI evolution into the future?

Cpp2 is competing with `Carbon` as the next thing, and since `Carbon` has ideas here - it would be good to see the Cpp2 ideas.
