### ISSUE TITLE
[SUGGESTION] constructor/destructor keyword

### ISSUE THREAD

**Issue by tkielan** [hsutter/cppfront#222]
How about creating constructors/destructors (especially for anonymous classes) like this:
```
struct {
  constructor(const int& rX) : x(rX) {} 
private:
  int x;
} Objects[] = { 1, 2, 3, 4 };

for (const auto& obj: Objects)
{
   // do something on obj
}
```

**Comment by hsutter** [comment]
Thanks for the suggestion! I did consider that and some other alternatives.

My aim is to unify construction, assignment, and possibly destruction. It's definitely desirable to try to unify at least construction and assignment, including to have a single function that can do both -- and that's only possible if they can have the same name, so I'm trying to avoid having a special name like `MyClass::MyClass` or `MyClass::constructor`.

Right now I'm pursuing generalizing `operator=` as the name for all value-setting, including construction and assignment. For details please see [paper d0708, sections 2.5 and 2.6](https://github.com/hsutter/708/blob/main/708.pdf).
