### ISSUE TITLE
[question] Why Cant we use the c# syntax instead of new syntax 

### ISSUE THREAD

**Issue by lakani** [hsutter/cppfront#23]
C# syntax is already a millions of developers familiar with syntax, defiantly there are few differences, but I think it worth that one day millions of c# developers just found that they are able to code in C++

**Comment by orent** [comment]
This is an experiment. The specific syntax is a straw man. The point is showing  C++ semantics can be mapped to a smaller and simpler set of concepts and syntactic 
 constructs.

c# syntax also grew “organically” over time, like c++ syntax. And if it’s old and organic, it smells…

**Comment by jcanizales** [comment]
Even without the smells, I think it's counterproductive to copy another language's syntax for constructs that are _semantically_ different.

**Comment by HookedBehemoth** [comment]
The C# syntax also violates one of the goals. It's not context-free.

**Comment by ntrel** [comment]
Also the current syntax doesn't conflict with syntax1 declarations so both can be mixed in the same file.
