### ISSUE TITLE
[BUG] inout parameter without non-const use of x works

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#230]
In section `1.3.2 inout parameters` of https://github.com/hsutter/708/blob/main/708.pdf you specify that 
```
If the function is nonvirtual, at least one path must contain a non-const use of x (else the parameter should be in).
```

In the current implementation of cppfront the following code compiles:
```cpp
f2: (inout x) -> _ = {
    return x * 2;
}

main: () -> int = {
    x := 21;
    std::cout << f2(x) << std::endl;
    x = 0; // workaround for another bug
}
```
And generate output:
```
42
```

### Expectations

cppfront should end with an error informing to use `in` argument passing instead of `inout`.

**Comment by hsutter** [comment]
Right, I'm not able to detect that right now so it's not possible to issue that diagnostic.

I could probably do this if I required a mutating argument to be qualified with `inout`, which I've thought of and @jbatez suggested in #198.

I see there's a related issue in #231 which might also be solved with an `inout` argument (call-site) requirement...

**Comment by filipsajdak** [comment]
I found that issue while playing with for..do loops. 

I assume that there is no call-site there.
