### ISSUE TITLE
[BUG] string interpolation trigger assertion when there are quotation marks inside `()$`

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#232]
In the current implementation of cppfront, the following code trigger assertion

```cpp
main: () -> int = {
    std::cout << "test: (parens(\"test\"))$" << std::endl; // cause assertion
}

parens: (x : std::string) -> std::string = {
    return "((x)$)";
}
```

The assertion is in `lex.h` file line 1168.

**Comment by hsutter** [comment]
Fixing, thanks!

**Comment by filipsajdak** [comment]
@hsutter I have just checked other cases, and it works as expected!

The following code compiles and runs smoothly. 
```cpp
std::cout << "test: (\"string literal\")$" << std::endl;
std::cout << "test: (std::string(\"standard string\"))$" << std::endl;
std::cout << "test: (std::string_view(\"string view\"))$" << std::endl;
std::cout << "test: (std::variant<int,double,std::string>(\"variant\"))$" << std::endl;
std::cout << "test: (std::tuple(1,1.2,std::string(\"string\")))$" << std::endl;
```

**Comment by jarzec** [comment]
@hsutter When I first saw the "()$" I started to think if this is not going to cause trouble like the bug reported here. My train of though was that allowing expressions themselves to be written inside string literals opens the gates to problems of escaping characters, escaping the escape characters etc.

Have you considered the alternative that has been proven to work e.g. in `std::regex` (and other regex tools outside of C++), [`boost::fmt`](https://www.boost.org/doc/libs/1_81_0/libs/format/doc/format.html), [`QString`](https://doc.qt.io/qt-6/qstring.html#arg) or even other languages like [python](https://doc.qt.io/qt-6/qstring.html#arg)? Setting the exact syntax aside the idea is to allow strings to define very simple and short tokens to be replaced, while the actual replacement expression is provided through a method/operator. Python and some C++ libraries offer quite a range of options for the tokens themselves, but just sticking to an analogue of `"$0"`, `"$1"`, ... (or `"0$"`, `"1$"`, ... in left-to-right) would be enough.

I can see the following advantages:
- The idea is generally known as it is widely used in regexps, different C++ libs (`boost::fmt`, Qt, ...) and even other languages. I see that as an improvement in teaching/guidelines, esp. if the exact syntax from `std::regexp` is reused.
- Automatic formatters would not make a mess out of long literals that include expressions e.g. when line length limits are enforced.
- Code readability would be improved as the altogether string literals would become shorter and simpler.
- The replacement expressions would stay just normal language expressions without escape characters etc. - easier to read and to auto-format.
- The same expression could be evaluated once and used multiple times during replacement very easily without temporary vars.
- The expression evaluation could be deferred.
- Different expressions could be used for the same literal to provide different output strings.
- Syntax highlighting would become simpler as string literals would not require special treatment to be readable esp. if more complex expressions are included. The replacement expressions would simply be highlighted like all the other expressions.
- This should also simplify tooling wrt the expression evaluation feature.

I was thinking of proposing this as a suggestion, but I wasn't sure if this wouldn't classify as a systax suggestion. Although, as I mentioned before, the exact syntax doesn't matter to me. It is more about the general idea of making the feature look like something familiar from in C++ itself (i.e. `std::regex`), popular libraries and other languages. I agree that "()$" (or some syntactic version of it) is also not a new invention, but it just seems to involve more complexity and less flexibility + potentially a new thing to teach.
