### ISSUE TITLE
[BUG] call to `cmp_greater()` cause error: `call to function 'operator>' that is neither visible in the template definition nor found by argument-dependent lookup`

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#238]
After proposing https://github.com/hsutter/cppfront/pull/236 (user-defined literals) I have played with the boost::ut library.

I found the following case:
```cpp
#include "boost/ut.hpp"

using namespace boost::ut;

main: () -> int = {
    expect((2+5) > 4_i);
}
```
Generates:
```cpp
// ----- Cpp2 support -----
#include "cpp2util.h"

#line 1 "tests/html_tests.cpp2"
#include "boost/ut.hpp"

using namespace boost::ut;

[[nodiscard]] auto main() -> int;

//=== Cpp2 definitions ==========================================================

#line 4 "tests/html_tests.cpp2"

[[nodiscard]] auto main() -> int{
    expect(cpp2::cmp_greater((2 + 5),4_i));
}
```
and fail to compile with error:
```
In file included from html_tests.cpp:2:
cppfront/include/cpp2util.h:1504:28: error: call to function 'operator>' that is neither visible in the template definition nor found by argument-dependent lookup
    return CPP2_FORWARD(t) > CPP2_FORWARD(u);
                           ^
tests/html_tests.cpp2:6:18: note: in instantiation of function template specialization 'cpp2::cmp_greater<int, boost::ut::detail::integral_constant<4>>' requested here
    expect(cpp2::cmp_greater((2 + 5),4_i));
                 ^
ut/include/boost/ut.hpp:1831:30: note: 'operator>' should be declared prior to the call site or in namespace 'boost::ut::detail'
[[nodiscard]] constexpr auto operator>(const TLhs& lhs, const TRhs& rhs) {
                             ^
1 error generated.
```

Changing the order of includes fixes the issue (including `cpp2util.h` after all other includes and using namespace clauses). Changing generated code to:
```cpp
#line 1 "tests/html_tests.cpp2"
#include "boost/ut.hpp"

using namespace boost::ut;

// ----- Cpp2 support -----
#include "cpp2util.h"

[[nodiscard]] auto main() -> int;

//=== Cpp2 definitions ==========================================================

#line 4 "tests/html_tests.cpp2"

[[nodiscard]] auto main() -> int{
    expect(cpp2::cmp_greater((2 + 5),4_i));
}
```

Makes the code successfully compile and run.

**Comment by hsutter** [comment]
Hmm. Let me see if I got this right... this affects:
- operator calls we wrap (such as comparison, deref, subscript)
- that require a `using` to be in scope for the ordinary non-wrapped call to work, which means they don't work with normal ADL

In this case the reason ADL isn't enough is that the `operator>` is in namespace `boost::ut`, but the argument appears to be in namespace `boost-ext/v1_1_9/detail` (or something like that), so `operator>` won't be found by ADL and so doesn't work out of the box. You need the `using`. Correct?

Please try the above checkin which moves the `#include "cpp2util.h"` to just before the first Cpp2 line... this gives the user the option to write whatever other `#include` and `using` (and arbitrary Cpp1 code) before it is included.

Can you give it a try and see if it addresses this problem?

**Comment by filipsajdak** [comment]
It solves some of the issues. The change makes the following code work:
```cpp
#include "boost/ut.hpp"

using namespace boost::ut;

main: () -> int = {
    expect((2+5) > 4_i);
}
```
And that is great!

Unfortunately, when I add include with `*.h2` file, it fails again as it will add `cpp2util.h` in place of the `*.h2` file. So, that makes the following code fail:
```cpp
#include "boost/ut.hpp"
#include "html/html.h2" // <--- here will be header that adds cpp2util.h

using namespace boost::ut;

main: () -> int = {
    expect((2+5) > 4_i);
}
```
Moving `using namespace` before the `*.h2` file solves it again. The following code works:
```cpp
#include "boost/ut.hpp"

using namespace boost::ut;

#include "html/html.h2" // <--- that will add cpp2util.h but it is fine at this order

main: () -> int = {
    expect((2+5) > 4_i);
}
```

**Comment by hsutter** [comment]
Yes, the idea was that with this change the programmer now has the option of putting a `using` before `cpp2util.h` is included. It sounds like that gives them enough control to make cases like this work. I'll close this as completed.

I do want all current C++ code to work, even code that's weird, so I'm glad this works.

But I do wonder if this code seems to be weird, that you can't even invoke comparison without writing a `using`. That breaks other examples too (I just tried, see [Godbolt](https://godbolt.org/z/8qWzjKGaE)), including that you can't even put those into a `set` or `map` because the `<` comparison can't be found (those containers go through `std::less` which wraps `<` just like `cpp2::cmp_less` wraps `<`):

    using namespace boost::ut;
    (2 + 5) < 4_i;          // OK, but needs the 'using'

    cmp_less((2 + 5),4_i);  // error

    std::set s = { 4_i };   // error

It doesn't seem right to put the operators that are meant to be used with a type in a different namespace than the type... I would have thought that at least the type author would have `using`'d the names into the type's namespace which should solve the problem for everyone, even if there are reasons to make the primary declarations live in another namespace. Ah well!

**Comment by filipsajdak** [comment]
> It doesn't seem right to put the operators that are meant to be used with a type in a different namespace than the type... I would have thought that at least the type author would have `using`'d the names into the type's namespace which should solve the problem for everyone, even if there are reasons to make the primary declarations live in another namespace. Ah well!

@kris-jusiak if you have any reasoning behind it that we have missed let us know. The good thing is that cppfront is able to use the boost::ut library for unit testing.
