### ISSUE TITLE
[BUG] Some bitwise operators produce Cppfront errors

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#239]
**Describe the bug**
Expressions with some bitwise operators produce Cppfront errors.

**To Reproduce**
Run Cppfront with the following, based on code from [cppreference](https://en.cppreference.com/w/cpp/language/operator_arithmetic):
```
main: () -> int = {
    mask : u32 = 1;
    x0 : u32 = 12345678;
    x1 : u32 = x0 | mask;     // Error
    x2 : u32 = x0 & ~mask;    // Error
    x3 : u32 = x0 & mask;     // OK
    x4 : u32 = x0 ^ mask;     // OK
    x5 : u32 = ~x0;           // Error
}
```

**EDIT: Thanks to @filipsajdak please ignore `x2` and `x5`.**

Cppfront reports these errors:
`error: ill-formed initializer (at '|')` for x1
`error: invalid expression after & (at '~')` for x2
`error: ill-formed initializer (at '~')` for x5

**Comment by filipsajdak** [comment]
Please remember that cppfront uses postfix operators (https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-operators).

`x2` and `x5` should look:
```cpp
    x2 : u32 = x0 & mask~;    // OK
    x5 : u32 = x0~;           // OK
```

**Comment by bluetarpmedia** [comment]
> Please remember that cppfront uses postfix operators

Ah yes, thanks for that!

**Comment by filipsajdak** [comment]
Fixed by https://github.com/hsutter/cppfront/pull/243
