### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by willwray** [hsutter/cppfront#24]
Just a suggestion to consider enabling the GitHub Discussions feature on this cppfront repo.

A stated project aim is to start a discussion, this could be a quick way to kickstart things. It could be convenient for now. The Issues tab has a different connotation and feels a barrier to contributions that aim at a collaborative conversation.

(I don't have much experience of Discussions pros and cons.)

**Comment by Vinodkumar-Karapurath** [comment]
Can put it on open discussion.

**Comment by alexreinking** [comment]
The best thing about Discussions is that it lets you keep Issues restricted to _actual issues_, as in technical problems, bug reports, and the like. Discussions is a good home for Q&A, whereas issues are not.

**Comment by hsutter** [comment]
My aim is to start discussion in the community broadly about what's possible in a major evolution of C++, with this as one potential way to go about it. I don't want to create a new community, all the existing places are the right place.

Plus I don't want to have to manage GitHub Discussions. :) Thanks.

**Comment by willwray** [comment]
Good points; the management and moderation workload  especially.

Please add links to the discussions in other forums, in the readme perhaps
(I'm aware of reddit and cpplang slack, but not aware of more specific fora).

Thanks for considering.
