### ISSUE TITLE
[BUG] Cppfront reports errors when initialising variables with hex & binary integer literals

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#240]
**Describe the bug**
Cppfront reports errors when initialising variables with hex or binary integer literals.

**To Reproduce**
Run Cppfront with the following, based on code from [cppreference](https://en.cppreference.com/w/cpp/language/integer_literal):
```
main: () -> int = {
    d : i32 = 42;         // OK
    o : i32 = 052;        // OK
    x : i32 = 0x2a;       // Error
    X : i32 = 0X2A;       // Error
    b : i32 = 0b101010;   // Error
}
```

Cppfront reports these errors:
`error: ill-formed initializer (at 'a')` for x
`error: ill-formed initializer (at 'A')` for X
`error: ill-formed initializer (at '0')` for b

**Comment by filipsajdak** [comment]
Fixed by https://github.com/hsutter/cppfront/pull/242
