### ISSUE TITLE
[SUGGESTION] Requirements in README?

### ISSUE THREAD

**Issue by vpiotr** [hsutter/cppfront#249]
First of all I love the idea in general, I was looking for such a tool for a long time. Thanks!

I just tested it for the first time and what I found missing (my C++ experience is dusty right now):

1) README does not mention (at least I didn't found) minimum versions of compilers to be used. It would be useful information in case  compilation is failing.

2) I'm not sure what is exactly g++10 (it was missing on my laptop) but g++ works just fine (Ubuntu 11.3.0-1ubuntu1~22.04) 

3) I was not sure from which directory I should execute the build of cppfront, but this script worked for me:

```
g++ source/cppfront.cpp -std=c++20 -o cppfront
./cppfront hello.cpp2
g++ hello.cpp -std=c++20
./a.out
(program output generated)
```

4) Where I can find full syntax 2.0 description? 

5) It could be useful to define syntax in some context-free grammar file and test all matching examples against it so you have always a matching (grammar + samples) pair. Such validation could be executed on request via additional command. Unfortunately I don't know any current tools for that.

**Comment by filipsajdak** [comment]
@vpiotr I will try to answer some of your questions:

Ad 1 & 2) the version of supported compilers is listed in the `regression-tests/test-results` directories. At the moment, there are four directories there:
  1. `apple-clang-14` (I am maintaining that),
  2. `clang-12`,
  3. `gcc-10`,
  4. `msvc-2022`,
If you want to know the exact versions in each directory, there is a file called `clang-version.output` or `gcc-version.output` that has more info. E.g. for GCC, it is:
```
g++-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Ad 3) you did it right. @hsutter keeps it simple to compile. If it compiles, it works. The only thing you need to remember is to add a path to the `cpp2util.h` file when you compile the cpp1 file that was generated by cppfront.

Ad 4) There is no full syntax description - check here for @hsutter explanations: https://github.com/hsutter/cppfront/issues/116#issuecomment-1327838314. You can learn a lot from `regression-tests` that are included in the repo, and I am always happy to help.

Ad 5) I am working on such a tool - hopefully, will share it soon; I am implementing it with cppfront, so it takes me a longer time than I expected, but it allows me to learn cppfront syntax and to contribute to the Herb efforts.

**Comment by vpiotr** [comment]
Thanks you all for clarification!
