### ISSUE TITLE
[SUGGESTION] Removing special handling of return value of main function

### ISSUE THREAD

**Issue by equeim** [hsutter/cppfront#254]
Currently Cpp2 allows this code:
```
main: () -> int = {
    std::cout << "Hello \n";
}
```

I think this code is problematic because it says main function returns an int but it doesn't actually do this. It's especially bad for beginners since one of the first things you would have to explain is why it's allowed here and not in any other place, instead of more substantial things.

Instead I propose allowing to declare main function without return value (and disallowing previous example if it doesn't have return statement):
```
main: () = {
    std::cout << "Hello \n";
}
```
It will generate "auto main() -> int" that will return 0.
This way people who start to learn Cpp2 won't immediately ask "why it doesn't return int" (maybe). And the topic of special properties of main function and what forms it can take can be taught later.

**Comment by MichaelCook** [comment]
Only loosely related to this issue, but cpp2 could also easily allow other variants for main's signature, such as:
```
main: (std::span<char*> args) = {
```

**Comment by SebastianTroy** [comment]
Why stop there, span<string_view>?


On 10 February 2023 13:02:07 Michael Cook ***@***.***> wrote:

Only loosely related to this issue, but cpp2 could also easily allow other variants for main's signature, such as:

main: (std::span<char*> args) = {

**Comment by filipsajdak** [comment]
@MichaelCook & @SebastianTroy it was already discussed here: https://github.com/hsutter/cppfront/pull/63#issuecomment-1272655945 and here https://github.com/hsutter/cppfront/issues/45#issuecomment-1267800958

**Comment by equeim** [comment]
I think this suggestion would be easier to implement than changing main's arguments. You already can't declare `void main()` in C++ so it won't conflict with anything. It's just a simple transformation of return type and possibly an addition of `return 0;` (though it can be omitted since C++ allows it).

**Comment by hsutter** [comment]
Limiting the discussion to the return type: Yes, currently all named functions default to returning `-> void`, and I've had an itch in the back of my mind to allow that to work for `main` too. Done... commit coming...

(I do it by just emitting Cpp2 `-> int` anyway under the covers. But in Cpp2 it's still truly a `-> void` default, because if you use that default you can't write `return` statements in the Cpp2 `main` body. Even though we emit `-> int` to Cpp1 to keep today's compilers happy.)

Thanks!
