### ISSUE TITLE
[BUG] sequential calls to `print_to_string()` functions on the same expression might return different values

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#256]
After 94f07969dfdc7f74bdf1e33e4bf224e1767040ca, the following code:
```cpp
main: () -> int = {
    i := 42;

    l := :() = {
        std::cout << (i&)$* << std::endl;
    };

    l();
}
```
Triggers assertion at `cppfront.cpp` line 2000.
```
assert (found != n.cap_grp->members.cend() && "could not find this postfix-expression in capture group");
```
And the following code is not:
```cpp
main: () -> int = {
    i := 42;

    l := :() = {
        std::cout << i&$* << std::endl; // notice lack of parentheses around `i&`
    };

    l();
}
```

The following code causes the issue in `build_capture_lambda_intro_for()` function:
```cpp
print_to_string(&cap.str, *cap.capture_expr, true);
suppress_move_from_last_use = true;
print_to_string(&cap.str_suppressed_move, *cap.capture_expr, true);
suppress_move_from_last_use = false;
```

The problem is that I assume that calls to these two `print_to_string()` functions that emit `*cap.capture_expr` to the strings happen in the same state of the printer (or in the same context). Unfortunately, it is not the case. For the code that triggers assertion, each of these calls will eventually call `auto emit(expression_list_node const& n) -> void`, which calls `consumed_expression_list_parens();` at the end of its execution. That makes sequential calls to `print_to_string()` functions on the same expression return different values (as they are called in a different cppfront state). 

The quick workaround for this issue is to restore the state after the first call to `print_to_string()`, e.g.:
```cpp
{
    auto state = need_expression_list_parens;
    print_to_string(&cap.str, *cap.capture_expr, true);
    need_expression_list_parens.swap(state); // restore the state of need_expression_list_parens to one before the call to print
}

suppress_move_from_last_use = true;
print_to_string(&cap.str_suppressed_move, *cap.capture_expr, true);
suppress_move_from_last_use = false;
```

Restoring the state of the cppfront might be hidden inside the `print_to_string()` function.

**Comment by hsutter** [comment]
Thanks! I just pushed a commit that does the fix you suggested.

I think this commit does fix the issue and it passes regression, but before I close this issue could you please double-check?

**Comment by filipsajdak** [comment]
@hsutter I confirmed - it is solved!
