### ISSUE TITLE
[SUGGESTION] labeled break and continue as a way to get rid of goto statements altogether

### ISSUE THREAD

**Issue by hypatia-of-sva** [hsutter/cppfront#258]
If we allow labeled breaks and continues for arbitrary enclosing scopes, but especially for nested loops, rule ES.76 from the core guidelines could be abandoned for a complete ban of goto. See here: https://github.com/hypatia-of-sva/documents/blob/main/P230217R0.pdf for a proposal of how it could be done in detail (originally as a suggestion for the language, but since people on the std-proposals mailinglist suggested that it's more of a syntax issue, which is true, it might be better fit here).

**Comment by gregmarr** [comment]
See #228 for a previous discussion of this.

**Comment by hsutter** [comment]
Quick ack: Does [this commit](https://github.com/hsutter/cppfront/commit/860992221bd613e4b72a3cd3b496e0b6b70611d8) achieve what you're looking for?

**Comment by hypatia-of-sva** [comment]
Yes, pretty much, thanks! I probably have to browse the commits more to find this, but this is basically what I suggested (minus the doubling of gsl::finally)

**Comment by hsutter** [comment]
Great!

BTW, if you submit your proposal to WG21, feel free to reference cppfront as an implementation since it's essentially the same as your proposal. For each example you could even add third compilable version of the code in Cpp2 syntax that works today, with a Godbolt link like https://godbolt.org/z/KnxKKvx15 .

**Comment by hypatia-of-sva** [comment]
Good to know that godbolt has cppfront, that will be very useful in finding various things in lieu of a documentation. Sadly, I can't appear in meetings right now because of my personal situation, and this was more of a test to write in proper standardese if anything, but I will try to find something interesting to contribute either to syntax two or SG21 in the future when I can and when it's more precient (since this being in cppfront basically solves the issue for the moment, as it's more a source code maintenance than a compilation / library problem).
