### ISSUE TITLE
[SUGGESTION] Use in-place anonymous types instead of generating __ReservedNamed global scope classes

### ISSUE THREAD

**Issue by janekb04** [hsutter/cppfront#263]
This is purely an implementation suggestion, invisible from the user's perspective.

Currently, `cppfront` generates a `struct` at namespace scope, when it encounters an _anonymous-return-type-definition_. An example of this is shown during the CppCon22 talk. A stripped-down minimal version looks like this (pretty-formatted by hand):
```cpp
f: () -> (i: int, s: std::string) = {
    i = 42;
    s = "Hello World!";
}

int main() {
    const auto [i, s] = f();
    std::cout << i << " " << s << std::endl;
    return 0;
}
```
The `cppfront` compiler turns this into the following Cpp1 code:
```cpp
#include "cpp2util.h"

struct f__ret {
    int i;
    std::string s;
    };

[[nodiscard]] auto f() -> f__ret;

int main() {
    const auto [i, s] = f();
    std::cout << i << " " << s << std::endl;
    return 0;
}

[[nodiscard]] auto f() -> f__ret {
    cpp2::deferred_init<int> i;
    cpp2::deferred_init<std::string> s;

    i.construct(42);
    s.construct("Hello World!");
    return  { std::move(i.value()), std::move(s.value()) };
}
```
[During the talk it was said that](https://youtu.be/ELeZAKCN4tY?t=5012):
> What we're doing is we're generating a return `struct` for the return type. So this is a normal C++ `struct`. 
> [...]
> You can't actually define the return `struct` in the function declaration".

Well, it turns out that since C++20, you actually **can** define the return `struct` in the function declaration ~~[(godbolt)](https://godbolt.org/z/qbxjd6K7b)~~ ~~[(godbolt v2)](https://godbolt.org/z/Y4c8cvb7q)~~ ~~[(godbolt v3)](https://godbolt.org/z/haqcxx11r)~~ [(godbolt v3 /w comments)](https://godbolt.org/z/8jYe7fbac):
```cpp
#include "🪄.h"

[[nodiscard]] auto f() -> struct_(int i; std::string s;);

int main() {
    const auto [i, s] = f();
    std::cout << i << " " << s << std::endl;
    return 0;
}

[[nodiscard]] auto f() -> struct_(int i; std::string s;) {
    cpp2::deferred_init<int> i;
    cpp2::deferred_init<std::string> s;

    i.construct(42);
    s.construct("Hello World!");
    return  { std::move(i.value()), std::move(s.value()) };
}
```
In short, this works by: **Creating an anonymous type** by using `decltype` on a lambda returning a local `struct`. This uses the fact that, since C++20, lambdas are allowed in unevaluated contexts. **The anonymous types are cached** by using [C++ defect 2118](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2118). This has to be done to make sure that the anonymous type is generated only once. Otherwise there would be redeclaration errors because each declaration would declare the function with a unique anonymous type.

~~The two versions (old and new) are nearly identical, including having nearly identical assembly. The only difference between them is that in the new version `f` is implicitly marked `static`. This is because `f` returns a type with no linkage (local `class` inside a lambda) and hence it also cannot have any linkage.~~
**Edit:** in the new versions, `f` does have linkage.

<details>
    <summary>Code copied from godbolt, just in case</summary>

    template <auto>
    struct value_type {}; // get it? poor me...

    // Compile time string hash
    //https://gist.github.com/Lee-R/3839813
    #include <cstdint>
    consteval std::uint32_t fnv1a_32(char const* s, std::size_t count)
    {
        return ((count ? fnv1a_32(s, count - 1) : 2166136261u) ^ s[count]) * 16777619u;
    }
    consteval std::uint32_t operator"" _hash(char const* s, std::size_t count)
    {
        return ((count ? fnv1a_32(s, count - 1) : 2166136261u) ^ s[count]) * 16777619u;
    }

    // Global dynamic state at compile time
    // https://alexpolt.github.io/type-loophole.html
    // https://b.atch.se/posts/non-constant-constant-expressions/
    #include <utility>
    template<typename Key>
    struct tag{
        using type = Key;
    };
    template<typename Key, typename Value>
    struct loophole_t {
    [[nodiscard]] friend auto loophole(tag<Key>) noexcept { return tag<Value>{}; };
    };

    // Anonymous type
    // https://janbielak.com/index.php/2021/01/15/anonymous-types-in-c/
    template <typename T>
    consteval T my_declval(){ return T{}; };
    #define struct_raw(...)                         \
        decltype(                                   \
            []() consteval {                        \
                struct unnamed {                    \
                    __VA_ARGS__                     \
                };                                  \
                return my_declval<unnamed>();       \
            }()                                     \
        )                                           \

    // Type cache
    template <typename T, bool B>
    struct type_bool
    {
        using type = T;
        static constexpr bool boolean = B;
    };

    template <typename Key, typename ForceReinstantiation = decltype([](){})>
    constexpr bool in_cache_v = requires{[]() consteval {
        [[nodiscard]] auto loophole(tag<Key>) noexcept;
        loophole(tag<Key>{});
    }();};

    template <typename Key, typename FallBack, typename ForceReinstantiation = decltype([](){})>
    consteval auto cache_func()
    {
        if constexpr (in_cache_v<Key>)
        {
            [[nodiscard]] auto loophole(tag<Key>) noexcept;
            return my_declval<typename decltype(loophole(tag<Key>()))::type>();
        }
        else
        {
            [[nodiscard]] auto loophole(tag<Key>) noexcept;   
            [[maybe_unused]] auto dummy = sizeof(loophole_t<Key, FallBack>);
            return my_declval<FallBack>();
        }
    }

    #define struct_(...) decltype(cache_func<value_type<#__VA_ARGS__##_hash>, struct_raw(__VA_ARGS__)>())

    // Main program
    #include "https://raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h"

    [[nodiscard]] auto f() -> struct_(int i; std::string s;);

    int main() {
        const auto [i, s] = f();
        std::cout << i << " " << s << std::endl;
        return 0;
    }

    [[nodiscard]] auto f() -> struct_(int i; std::string s;) {
        cpp2::deferred_init<int> i;
        cpp2::deferred_init<std::string> s;

        i.construct(42);
        s.construct("Hello World!");
        return  { std::move(i.value()), std::move(s.value()) };
    }

</details>

**Comment by JohelEGP** [comment]
> In short, this works by: **Creating an anonymous type** by using `decltype` on a lambda returning a local `struct`. This uses the fact that, since C++20, lambdas are allowed in unevaluated contexts.

It seems that makes for worse error messages. Also, Clang complains that
```
<source>:2:12: error: types may not be defined in 'decltype' expressions
    2 |   struct X { };
      |            ^
```
See https://compiler-explorer.com/z/j7qdb58hq. MSVC is not working on CE for now.
Code:
```
auto f() -> decltype([] {
  struct X { };
  return X{};
}) {
  return {};
}

struct g__ret { };
auto g() -> g__ret { return {}; }

auto h = g;

auto a = ++f();
auto b = ++h();
```
Clang output:
```
<source>: In lambda function:
<source>:2:12: error: types may not be defined in 'decltype' expressions
    2 |   struct X { };
      |            ^
<source>: At global scope:
<source>:13:10: error: no match for 'operator++' (operand type is '<lambda()>')
   13 | auto a = ++f();
      |          ^~~~~
<source>:14:10: error: no match for 'operator++' (operand type is 'g__ret')
   14 | auto b = ++h();
      |          ^~~~~
Compiler returned: 1
```
GCC output:
```
<source>:13:10: error: cannot increment value of type 'decltype([] {
    struct X {
    };
    return X{};
})' (aka '(lambda at <source>:1:22)')
auto a = ++f();
         ^ ~~~
<source>:14:10: error: cannot increment value of type 'g__ret'
auto b = ++h();
         ^ ~~~
2 errors generated.
Compiler returned: 1
```

**Comment by janekb04** [comment]
@JohelEGP Hi, currently GCC does complain that types cannot be defined in unevaluated contexts. Clang used to say that, but after an update it no longer does. I don't think that the change was unintentional, so I'd say that it's a bug in GCC (and rather easy to fix). I don't think that the standard disallows type definitions in unevaluated contexts.

You return the `decltype` of the lambda instead of the `decltype` of the call to the lambda, so that's why the type is incorrect.

What is `++f()` supposed to do? The value returned by a function with a non-reference return type is a prvalue and hence, the preincrement operator cannot by applied to it.

**Comment by JohelEGP** [comment]
> currently GCC does complain that types cannot be defined in unevaluated contexts. Clang used to say that, but after an update it no longer does.

Seems like I got the compiler backwards.

> You return the `decltype` of the lambda instead of the `decltype` of the call to the lambda, so that's why the type is incorrect.

You're right. It seems not to make too much of a difference. See https://compiler-explorer.com/z/G885c3fYs.
GCC:
```diff
<source>: At global scope:
-<source>:13:10: error: no match for 'operator++' (operand type is '<lambda()>')
+<source>:13:10: error: no match for 'operator++' (operand type is '<lambda()>::X')
   13 | auto a = ++f();
      |          ^~~~~
```
Clang:
```diff
<source>:13:10: error: cannot increment value of type 'decltype([] {
    struct X {
    };
    return X{};
-})' (aka '(lambda at <source>:1:22)')
+}())' (aka 'X')
auto a = ++f();
         ^ ~~~
```

> What is `++f()` supposed to do? The value returned by a function with a non-reference return type is a prvalue and hence, the preincrement operator cannot by applied to it.

The intention is to have an ill-formed program to compare errors from your suggestion and the current Cppfront's behavior.

See https://compiler-explorer.com/z/3GcjhqKPq for how the mangled names compare.
```ASM
main: # @main
  call h(g__ret, $_0::operator()() const::X)
h(g__ret, $_0::operator()() const::X): # @"h(g__ret, $_0::operator()() const::X)"
```

**Comment by janekb04** [comment]
In [this new version](https://godbolt.org/z/T3616ns3d), the signature is prettier: `g(loophole(tag<value_type<3503686424u>>)::return_type)`. It could be further simplified by removing the `value_type` intermediary, if necessary. More importantly, `f` (and its return type) now has linkage.

**Comment by janekb04** [comment]
BTW, you can nest them: `struct_(struct_(struct_(struct_(struct_(int i;) i;) i;) i;) i;) h();`.

**Comment by janekb04** [comment]
Well, you can further strip down the type [(godbolt)](https://godbolt.org/z/1M6KvxKx5): `g(__lh(v_tag<3503686424u>)::ret):`. For me this looks acceptable. `std::` functions have worse names.

**Comment by janekb04** [comment]
Improved once more [(godbolt)](https://godbolt.org/z/cxYY48xT8): `g(__ret<3503686424u>):`.

**Comment by janekb04** [comment]
Regarding performance, compile time for both versions seems comparable (1s-5s, 3s avg.).

**Comment by hsutter** [comment]
Thanks @janekb04! I appreciate the suggestion.

For now, I think I'll stay with the current implementation. I'm not sure this is fixing a problem in the existing implementation, and while it's definitely cute I think it could cause me to have to answer questions about what the generated code is doing which could be a distraction... I'm aiming to keep the generated code simpler and clear where possible (which also helps me debug it).

But I think this approach is good to know about, and I'll keep it in mind as it could be useful in the future! Thanks again.
