### ISSUE TITLE
[BUG] function that explicitly returns `void` is set as `[[nodiscard]]`

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#278]
The current implementation of cppfront (4c52d2d9c6c4b7ae19ee2eeb584a5a775ba78af3) for the following code:

```cpp
fun: () -> void = {
    // ...
}
```
Generates (skipping boilerplate):
```cpp
[[nodiscard]] auto fun() -> void{
    // ...
}
```

### Expected

After changing the default to `-> void` explicit `void` return shall be blocked, or it should not add `[[nodiscard]]` to the function.

**Comment by hsutter** [comment]
Good catch, thanks. Fixed.
