### ISSUE TITLE
[BUG] Anonymous Namespaces produce bad cpp1 code

### ISSUE THREAD

**Issue by AbhinavK00** [hsutter/cppfront#283]
Writing an anonymous namespace in cpp2 today copies the code as-is to the cpp1 which results in error on cpp1 side.

Example:
```cpp
: namespace = {
   a : i32 = 4;
}
```
produces
```cpp
: namespace = {
   a : i32 = 4;
}
```

Seems like cppfront thinks its pure cpp1 code and therefore does not process it.
Expected behaviour is for cppfront to support anonymous namespaces and produce corresponding correct code.

Also, I guess cpp2 will not support `static` as anonymous namespaces are today's preference over it, can Herb clarify?

**Comment by SebastianTroy** [comment]
AFAIK cpp2 doesn't support namespaces so assumes any code within is cpp1


On 14 March 2023 21:47:26 Abhinav00 ***@***.***> wrote:

Writing an anonymous namespace in cpp2 today copies the code as-is to the cpp1 which results in error in cpp1 side.

Example:

: namespace = {
   a : i32 = 4;
}

produces

: namespace = {
   a : i32 = 4;
}

Seems like cppfront thinks its pure cpp1 code and therefore does not process it.
Expected behviour is for cppfront to support anonymous namespaces and produce corresponding correct code.

Also, I expect cpp2 to not support static as anonymous namespaces are today's preference over it, is that right?

**Comment by JohelEGP** [comment]
> AFAIK cpp2 doesn't support namespaces so assumes any code within is cpp1

It does since 258190ef6df8db8bc31d0eb5d94094da5d800623.

**Comment by hsutter** [comment]
Thanks for pointing this out. Just omitting the name on a declaration is for expression scopes... I think perhaps the right way to support anonymous namespaces is to use `_`, such as:

    _ : namespace = { ... }

**Comment by AbhinavK00** [comment]
While any syntax works, 
``` : namespace = {}```
This would be more consistent with how lambdas are written. Still, your proposed syntax is fine (maybe lambda syntax could be tweaked?)

**Comment by hsutter** [comment]
OK, now the feature exists. Thanks again for spotting the omission.

Yes, at expression scope we omit the name... only at expression scope though. Just omitting the name here would make it feel like a namespace-expression, which isn't what it is... it's a full namespace, just one whose name we don't care to utter. -- Anyway, I'll try this path and see where it leads. Thanks again.
