### ISSUE TITLE
[SUGGESTION] Multiple suffixes for literals, a revisit of Uniform Function Call Syntax

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#284]
In our life, every quantity can have multiple suffixes. For example:
- 1 million dollar
- 1 million euro
- 20% of a bottle of water
- 5,000 grams of apples
- 1 hour of worker

In C++1, optional `'` may be inserted between the digits of integer and floating-point literals as a separator. Therefore I propose that every suffix optionally may start with `'` and mandatory `'` must be inserted between them as a separator for multiple suffixes. Now, let's write the code for the above cases:

```
1'million'dollar
1'million'euro
20'percent'bottle'water
5'000'gram'apple
1'h'worker
```

Also built-in suffixes optionaly may start with `'`. They can be uppercase or lowercase. The built-in integer suffixes are `L`, `LL`, `Z`, `U`, `UL`, `ULL` and `UZ` (if `U` is provided, it must be the first in C++2, but it can be the last in C++1). The built-in floating-point suffixes are `F`, `L`, `F16`, `F32`, `F64`, `F128` and `BF16` as defined in C++23.

```
1'ULL
5'000.0'F
```

Encoding prefixes of character literals and string literals have to be changed to be suffix (similar to C# language), the first suffix have to be without `'`, because the end of character literals and string literals already have a quote:

```
'c'u8'symbol
"UTF-8 string view"u8'sv
R"(raw string)"u8's
```

As an extra feature, boolean literals may have suffixes, but it's really a special case for libraries:

```
false'news
```

In addition, we can write user defined suffixes after built-in suffixes:

```
100'UL'min
1.5'F'ms
```

Now, the question is what does it have common to uniform function call syntax. To answer this question, the following example is useful:

```
// In C++1
apple(gram(5'000))

// In C++2 with Uniform Function Call Syntax
// The above expression can be written as the following expression
5'000.gram().apple()

// In my suggestion, we can go further
5'000'gram'apple
```

So, definitely suffixes are the same as member functions or free functions. We don't need an `operator""` to create user defined literals, each member function with the right signature can be used as suffix. Also free functions with the right signature can be used as suffix. For example:

```
Gram :type = {
    ...

    apple :(this) ->Apple = {
        ...
    }

    ...
}

gram :(value :int) ->Gram = {
    ...
}

x := 5'000'gram'apple;
```

No, suffixes should never get any extra parameter, it will ruin its purpose of being less verbose (being without parenthesis), and they should not modify `this` parameter.

**Will your feature suggestion improve performance or expressiveness?**

Yes, because user defined literals can improve expressivity of the programmer:

```
// store.sell(orange(box(2)));
a := store.sell(2'box'orange);

// price(water(bottle(2)) + juice(glass(0.5)))
b := price(2'bottle'water + 0.5'glass'juice);
```

Maybe it improves performance too, because for built-in suffixes the true type of the literal will be sent to the member function call:

```
hour :(value :float) ->Hour = {
	...
}

x := 1.0'F'hour;
```

If we rewrite the above example with `operator""` in C++1, then the type of `value` parameter must be `long double` instead of `float`, because `operator""` only accepts a parameter of type `unsigned long long int` or `long double`.

Uniform function call syntax will also improve generic programming for suffixes.

**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?**

No.

**Will your feature suggestion _automate or eliminate_ X% of current C++ guidance literature?**

Yes. My feature suggestion will remove unnecessary extra concept `operator""`, and it will integrate its usage with normal member functions or free functions. Also It improves code readability.

The purpose of suffix notation is for units or quantities, member function notation is for object-style behaviors or states, and free function notation is for computing.

**Describe why you've considered this feature request.**

Currently I'm trying to suggest a new string literal for C++2. This suggestion will affect my suggestion about string literals. I hope to read your feedbacks here, therefore I can improve it or I should give up.

**Comment by msadeqhe** [comment]
I've to correct some parts of my suggestion.

> We don't need an `operator""` to create user defined literals, each member function with the right signature can be used as suffix. Also free functions with the right signature can be used as suffix.

If using free functions for defining user defined literals seems too much radical change, we should keep using `operator""` (or in this suggestion can be renamed to `operator'`) and give up about making it a part of uniform function call syntax.

Anyway, the goal of my suggestion is about to allow multiple suffixes on literals (for example `1.0'F'ms` or `1'box'orange`), and the prefix of string literals and character literals should be changed to suffix, in other words, `u8"text"s` should be changed to `"text"u8's`.

**Comment by AbhinavK00** [comment]
Writing `'` to use literal suffix seems extra work, what if we just define 
```
operator gram :(value :int)
```

Why not `,` instead of `'`?

**Comment by SebastianTroy** [comment]
This might be out there, but with unified function call syntax, could we treat literals and built in types the same as user types and call 1.gram() which would be equivalent to gram(1)? Then we don't need to introduce custom operators or new syntax. It would naturally allow chaining too.


On 17 March 2023 09:28:00 Abhinav00 ***@***.***> wrote:

Writing ' to use literal suffix seems extra work, what if we just define

operator gram :(value :int)


Why not , instead of '?

**Comment by msadeqhe** [comment]
> Why not `,` instead of `'`?

Because `,` is already a separator for function parameters:

```
player.buy(2'box'biscuit, 3`banana);
```

**Comment by msadeqhe** [comment]
> This might be out there, but with unified function call syntax, could we treat literals and built in types the same as user types and call 1.gram() which would be equivalent to gram(1)? Then we don't need to introduce custom operators or new syntax. It would naturally allow chaining too.

Yes, you're right. Literals, member functions and free functions do really the same thing, but in a different style (syntax).

**Comment by jcanizales** [comment]
> Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?
> No.

Might! Anything that eases the use of units, indirectly allow the compiler to catch bugs that we all face every so often. Sure, those bugs of ours aren't as glamorous as the space probe that missed Mars because someone wrote code in non-international units. But they might lead to security vulnerabilities.

**Comment by hsutter** [comment]
Thanks @msadeqhe for the suggestion, and thanks @jcanizales for the UFCS idea.

Well, this turned into a fascinating little detour, and I think I like the result!

@jcanizales's intriguing point about UFCS worked today already for string literals... for example, the following already worked:

```
Gram: type = {
    value:     int;
    operator=: (out this, val: int) = { value = val; }
    print:     (this) = std::cout << "(value)$ grams\n";
}

gram: (val: std::string_view) -> Gram
    = :Gram = sv_to_int(val).value; // (*)

main: () = {
    test := "2".gram();
    test.print();   // prints "2 grams"
}
```

But it didn't already work for integers because "1." and "1.f" were valid floating point literals, so that `.` couldn't be parsed as starting a UFCS function call.

I say "were" and "couldn't" because I just changed that... I've long disliked that the C floating point literal syntax allowed omitting the `0` (I find omitting it slightly less readable, though admittedly I've taken advantage of it sometimes just because it was conventional and because, well, laziness).

I've now pushed the above commit that:
- requires that floating point literals have at least one digit after the `.`, so that `.0` be written explicitly, which I think is a small improvement in its own right; and
- therefore unlocks general UFCS on numeric literals, which can be useful generally but also for the purpose of this thread.

With the above commit, the following now works too:

```
Gram: type = {
    value:     int;
    operator=: (out this, val: int) = { value = val; }
    print:     (this) = std::cout << "(value)$ grams\n";
}

gram: (val: int) -> Gram
    = :Gram = val;

main: () = {
    test := 2.gram();
    test.print();   // prints "2 grams"
}
```

I think this is an interesting path to explore... let me know what you think as you play around with using this style for unit-type literals.

---

(*) see sample implementations at https://stackoverflow.com/questions/56634507/safely-convert-stdstring-view-to-int-like-stoi-or-atoi

**Comment by msadeqhe** [comment]
Thanks @hsutter. I have a question, will C++2 support user defined literals? I've tried to overload `operator ""` in C++2, but it doesn't generate any C++1 code:

```
operator ""_w: (v: ulonglong) -> ulonglong = {
    return 0;
}
```

Does it mean we should use _UFCS_ instead of _User-defined Suffixes_?

**Comment by AbhinavK00** [comment]
It's probably a probably with `ulonglong`, try using `u64` instead.

**Comment by msadeqhe** [comment]
Yes, `u64` doesn't work either. `ulonglong` is defined in `cpp2util.h` in the following line:
```
using ulonglong = unsigned long long;
```

**Comment by hsutter** [comment]
> will C++2 support _User-defined Literals_?

For _authoring_ UDLs: I hadn't decided whether or not to support authoring them, and this thread convinces me we should try using UFCS for that first. It's desirable to solve the problem using a more general language feature, if it works well also for this use case, rather than adding a special-purpose language feature.

For _consuming_ existing Cpp1 UDLs: I haven't made any special effort to either support or prevent consuming them, and I generally want things like that to work for compatibility so that Cpp2 can consume existing Cpp1 libraries with high fidelity. I did a quick test using the [cppreference UDL page](https://en.cppreference.com/w/cpp/language/user_literal)'s Coliru [example code for UDLs](https://coliru.stacked-crooked.com/view?id=6f81292636391461), and it works with `main` changed to Cpp2:

```
main: () = {
    x_rad: double = 90.0_deg_to_rad;
    std::cout << std::fixed << x_rad << '\n';

    y: mytype = 123_mytype;
    std::cout << y.m << '\n';

    0x123ABC_print;
    std::cout << "abc"_x2 << '\n';
}
```

**Comment by AbhinavK00** [comment]
>It's desirable to solve the problem using a more general language feature, if it works well also for this use case, rather than adding a special-purpose language feature.

While I agree with that, if we already have literals in the langauge, why not just go ahead and let users define theirs?
Cpp2 is already going to consume literals defined in standard llibrary so it is only natural for cpp2 to support UDLs.
it's not a new feature, literals already exist and it's just operator overloading.

**Comment by filipsajdak** [comment]
@AbhinavK00 you can still define it on the cpp1 side and use it in cpp2. In my project, I have been playing with this interoperability between cpp2 and cpp1 (it is a feature of cpp2). When there will be enough evidence for any solution it can be introduced into the cpp2.

The best way to support that is to write code that uses it (or port some code to cpp2) and show that it works well or badly.

**Comment by jcanizales** [comment]
Just wanted to point out that the idea of using UFCS for this was @SebastianTroy 's, not mine :slightly_smiling_face:

**Comment by hsutter** [comment]
@jcanizales @SebastianTroy Eek, thanks -- corrected, and thanks again for the idea and discussion.

**Comment by SebastianTroy** [comment]
Nae bosh =]


On 22 March 2023 19:40:03 Herb Sutter ***@***.***> wrote:

@jcanizales<https://github.com/jcanizales> @SebastianTroy<https://github.com/SebastianTroy> Eek, thanks -- corrected, and thanks again for the idea and discussion.

**Comment by JohelEGP** [comment]
> With the above commit, the following now works too:
> 
> ```
> Gram: type = {
>     value:     int;
>     operator=: (out this, val: int) = { value = val; }
>     print:     (this) = std::cout << "(value)$ grams\n";
> }
> 
> gram: (val: int) -> Gram
>     = :Gram = val;
> 
> main: () = {
>     test := 2.gram();
>     test.print();   // prints "2 grams"
> }
> ```

Maybe this works by chance, but you can use `Gram` directly, without the `gram` function: <https://cpp2.godbolt.org/z/3qax9WfeM>.

**Comment by msadeqhe** [comment]
I think that's a bug. AFAIK a type is not supposed to be called like a member function with UFCS, and there isn't a C++ style cast in Cpp2:

```cpp
x0: = Type(2); // It's a Cpp1-style cast and object construction.
x1: = 2.Type(); // It's not UFCS.
```

**Comment by JohelEGP** [comment]
> and there isn't a C++ style cast in Cpp2:
> 
> ```c++
> x0: = Type(2); // It's a Cpp1-style cast and object construction.
> ```

I don't think Cpp2 intends to ban `A(B)`, where `A` could name a function, type, or variable.

**Comment by msadeqhe** [comment]
> I don't think Cpp2 intends to ban `A(B)`, where `A` could name a function, type, or variable.

But Cpp2 is context-free. If `A` in `A(B)` is a type, it would allocate memory, but if `A` is a function, it won't do that. Is this behaviour context-free?

**Comment by JohelEGP** [comment]
Grammatically, `A` in `A(B)` is just an identifier. So I guess it's a matter for semantic analysis.

An example where grammar matters is the `t` in `x is t`.
`t` is grammatically a type, so you need parentheses to make it an expression: <https://cpp2.godbolt.org/z/Me1Yh588n>.

**Comment by msadeqhe** [comment]
Thanks for info. I don't have enough knowledge about how compilers and transpilers work, but `2.Gram()` looks strange to access a nested type from literal `2` and call it as if it was a member function, while thinking in UFCS which is about free functions and member functions.

**Comment by JohelEGP** [comment]
It also works with function objects: <https://cpp2.godbolt.org/z/44zGx8TMq>.

**Comment by msadeqhe** [comment]
That's right. Function objects `object(1)` are inherently functions, as how `object[1]` looks like arrays. Although `Type()` in Cpp1 is a function-style way to call constructors, AFAIK it is not valid in Cpp2, therefore UFCS shouldn't work for types in Cpp2.

**Comment by JohelEGP** [comment]
See <https://github.com/hsutter/cppfront/issues/193#issuecomment-1370192319> starting from "Re function-style construction notation:".

**Comment by msadeqhe** [comment]
Thanks. So eventually `Type(...)` will be banned in Cpp2.

**Comment by msadeqhe** [comment]
It's surprising for me, because:

- UFCS is about *Unifying Function Call Syntax*, and suddenly it works with types.
- It doesn't feel expressive enough for a context-free language. `: Type = (args)` creates a variable, but `Type(args)` may create a variable or may call a function (or function object).
- It's like a nested class within literal `2`.
- It's like accessing a base class within multiple inheritance, e.g. `a.Base::call()`.

**Comment by msadeqhe** [comment]
Also it would conflict with multiple inheritance in Cpp2, it depends on how we would access base types:

```cpp
base: type = {
    operator=: (out this) = {}
    operator=: (out this, v: x) = {}
    operator(): () -> int = 0;
}

x: type = {
    this: base = ();
    operator(): () = {
        // Does it call operator()?
        // or calls the default constructor?
        m: = base(); // Ambiguous

        // Does it call operator()?
        // or calls the constructor with `base(this)`?
        n: = this.base(); // Ambiguous
    }
}
```

It would complicate the language, similar to how it has complicated Cpp1 for object construction. It's better to distinguish types and functions/variables.

**Comment by msadeqhe** [comment]
> It's surprising for me, because:
> 
> 1. UFCS is about _Unifying Function Call Syntax_, and suddenly it works with types.
> 2. It doesn't feel expressive enough for a context-free language. `: Type = (args)` creates a variable, but `A(args)` (also `a.A(args)`) may create a variable or may call a function (or function object).
> 3. It's like accessing a base class within multiple inheritance, e.g. `a.Base::call()` in Cpp1.

I couldn't find the real reason that why it's surprising for me. Now I find it:

4. UFCS is about to unify `a.function(args)` (member functions) with `function(a, args)` (non-member functions). It's important to note that both of them are valid syntax. On the other hand, `a.Type(args)` is a syntax sugar to `Type(a, args)`. But the problem with `a.Type(args)` is that itself is not a valid syntax! It's not a nested type! It must be `a::Type(args)` to be a valid syntax. So UFCS on types would unify an invalid syntax `a.Type(args)` (nested type which has to be `a::Type(args)`) with `Type(arg)` (object construction). So UFCS on types are semantically incorrect.

**Comment by SebastianTroy** [comment]
Isn't a constructor just a function that returns an instance of a type?


On 16 May 2023 06:17:52 Sadeq ***@***.***> wrote:

It's surprising for me, because:

  1.  UFCS is about Unifying Function Call Syntax, and suddenly it works with types.
  2.  It doesn't feel expressive enough for a context-free language. : Type = (args) creates a variable, but A(args) (also a.A(args)) may create a variable or may call a function (or function object).
  3.  It's like accessing a base class within multiple inheritance, e.g. a.Base::call() in Cpp1.

I couldn't find the real reason that why it's surprising for me. Now I find it:

  1.  UFCS is about to unify a.function(args) (member functions) with function(a, args) (non-member functions). It's important to note that both of them are valid syntax. On the other hand, a.Type(args) is a syntax sugar to Type(a, args). But the problem with a.Type(args) is that itself is not a valid syntax! It's not a nested type! It must be a::Type(args) to be a valid syntax. So UFCS on types would unify an invalid syntax a.Type(args) (nested type which has to be a::Type(args)) with Type(arg) (object construction). So UFCS on types are semantically incorrect.

**Comment by AbhinavK00** [comment]
`Type(...)` has always been surprising to me (since the first time I saw it way back) because types are not callable but then I always viewed it as functions having the name "Type".

**Comment by msadeqhe** [comment]
> 4. UFCS is syntactically and semantically incorrect for types.
> ...
> 5. It's inconsistent with nested types.
> ...
> 6. Currently in Cpp2, only one of `.` or `::` may be used to access members from an identifier.

7. UFCS on types would make member functions to conflict with `a.SOMETHING(args)`.

```cpp
abc: type = {
    klass: (this) = {}
}

klass: type = {
    operator=: (out this, v: abc) = {}
}

main: () = {
    a: abc = ();

    // It conflicts...
    // Does to call the constructor of `klass`?
    // or it calls the member function `klass`?
    a.klass();
}
```

In this example, the meaning of `a.klass()` would be ambiguous.

> Isn't a constructor just a function that returns an instance of a type?

@SebastianTroy, That's not the whole story. It has side effects especially when UFCS comes in.

I think you read my comments via email, therefore you didn't read my examples because I've edited my comments and added them later.

> `Type(...)` has always been surprising to me (since the first time I saw it way back) because types are not callable but then I always viewed it as functions having the name "Type".

@AbhinavK00, I hope they would be changed to `(...)TYPE` as suggested in [this issue](https://github.com/hsutter/cppfront/issues/455).

**Comment by msadeqhe** [comment]
> 7. UFCS on types would make member functions to conflict with `a.SOMETHING(args)`.

8. Semantically `a.klass()` is inconsistent with `klass(a)`.

Semantically types don't have enough relation to UFCS.

In contrast, `o.func()` and `func(o)` are semantically similar for functions, the first argument is the object.

But `a.klass()` and `klass(a)` are semantically inconsistent for types, the first argument is not the object, it's just an argument which shouldn't be used like an object.

**Comment by JohelEGP** [comment]
There _is_ a difference between `2.Gram()` and actual initialization syntax
(not that `2.gram()`, with a function, performs any better).
The former lowers to copy-initialization, while the latter lowers to list-initialization.

**Comment by msadeqhe** [comment]
@JohelEGP That's an interesting implementation detail.

**Comment by msadeqhe** [comment]
`Type(args)` is Cpp1-style name for constructors, because:

- The name of constructors is the same name of their outer type in Cpp1.
  So it's consistent to write `Type(args)` to call the constructor in Cpp1:
  ```cpp
  class Type {
      Type(/*args*/) { /*statements*/ }
  }
  ```
- But the name of constructors is `operator=` in Cpp2.

@hsutter, there are some discussion about `a.Type(args)` in [this issue][1], I copy a part of my comments from there to here:

Inherently types are not callables, they are block of related declarations. Whereas their constructors are callable, but their `this` parameters don't exist yet. So UFCS is not for them. Briefly, the problems with `a.Type(args)` in Cpp2 are that:

- Syntactically it's _**inconsistent with member access operator**_ (aka _operator dot_).
    - Because `a` doesn't have member `Type`.
- Syntactically it's _**inconsistent with scope resolution operator**_ (aka `::`) for referring to types.
    - Because nested types are not instance members.
- Syntactically it's wrong, because `a` is _**not the first argument**_ of `Type`'s constructor in `operator=: (out this, args)`.
    - For UFCS on functions, `a` is the first argument:
        - `inout this`
        - `in this`
        - `copy this`
        - `move this`
        - `forward this`
    - For UFCS on types, `a` is not the first argument of the constructor:
        - `out this`
- Syntactically it's _**not context-free**_.
    - The compiler (not transpiler) and the programmer must look up for `Type` declaration to see if that's a type or a callable.
- Semantically it's inconsistent with UFCS, because they do _**completely different things**_, in this way:
    - UFCS on functions: `a` is the object to work with it.
    - UFCS on types: `a` is not the object to work with it, `a` and `args` are arguments to construct a new object.
- Semantically it's misleading and meaningless, because `a` has _**always exactly the same behaviour**_ as `args`.
    - That's a useless visual separation.
      ```cpp
      // This separation between `true` and other arguments are meaningless.
      // Using TYPE(...) and UFCS on types for object construction:
      x0: = true.Connection(2000, my::proxy());
      
      // All arguments have the same behaviour on object construction.
      // Using (...)TYPE for object construction:
      x1: = (true, 2000, ()my::proxy)Connection;
      ```

To make this behaviour expressive enough, the syntax for calling constructors have to be different. The most similar concept to constructors are UDLs, therefore constructors can be called like [they are generalized simpler UDLs][1].

On the other hand, `(args)Type` is consistent with left-to-right grammar of Cpp2, because the type is after arguments. Also `(args)A` is context-free as opposite to `A(args)` in which `A` can be either function, function object or type.

[1]: https://github.com/hsutter/cppfront/issues/455

**Comment by msadeqhe** [comment]
C++23 have both `static operator()` and `static operator[]`.

@hsutter, by making the syntax of object creation from `Type(args)` to something else like `(args)Type`, `(args):Type`, `(args).Type` or etc, it would be possible to call static operators `()` and `[]` directly:

```cpp
Ab: type = {
    // static operator()
    operator(): (i: int, j: int) -> bool = i == j;

    // static operator[]
    operator[]: (i: int, j: int) -> bool = i == j;
};

ab: Ab = ();

m: bool = Ab(1, 2); // It calls `static operator()` directly.
n: bool = ab(1, 2); // It calls `static operator()` too.

x: bool = Ab[1, 2]; // It calls `static operator[]` directly.
y: bool = ab[1, 2]; // It calls `static operator[]` too.
```
