### ISSUE TITLE
[SUGGESTION] Avoid gcc old-style-cast warning by using static_cast

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#287]
Transpiling with <kbd>cppfront</kbd> and then compiling with <kbd>gcc -Wold-style-cast</kbd> I get the following warning:

<pre>
cpp2util.h: In Konstruktor »cpp2::args_t::args_t(int, const char* const*)«:
cpp2util.h:1420:58: Warnung: Verwendung einer Typumwandlung nach »size_t« {aka »long unsigned int«} im alten Stil [-Wold-style-cast]
 1420 |     args_t(int c, char const* const* v) : vector{(size_t)c}, argc{c}, argv{v} {}
      |                                                          ^
      |                                                  ---------
      |                                                  static_cast<size_t> (c)
</pre>

Replacing <code>(size_t)c</code> with <code>static_cast<size_t>(c)</code> in <code>cpp2util.h:1420</code> removes the warning.

Compiling <kbd>cppfront</kbd> itself with <kbd>gcc -Wold-style-cast</kbd> gives some more warnings:

<pre>
source/../include/cpp2util.h: In Konstruktor »cpp2::args_t::args_t(int, const char* const*)«:
source/../include/cpp2util.h:1420:58: Warnung: Verwendung einer Typumwandlung nach »size_t« {aka »long unsigned int«} im alten Stil [-Wold-style-cast]
 1420 |     args_t(int c, char const* const* v) : vector{(size_t)c}, argc{c}, argv{v} {}
      |                                                          ^
      |                                                  ---------
      |                                                  static_cast<size_t> (c)
source/common.h: In Funktion »char cpp2::to_upper(char)«:
source/common.h:327:58: Warnung: Verwendung einer Typumwandlung nach »char« im alten Stil [-Wold-style-cast]
  327 |     if (0 <= c && c <= 126) { return (char)std::toupper(c); }
      |                                                          ^
      |                                      ------
      |                                      static_cast<char> (  )
source/lex.h: In Elementfunktion »cpp2::token::operator std::string_view() const«:
source/lex.h:249:34: Warnung: Verwendung einer Typumwandlung nach »unsigned int« im alten Stil [-Wold-style-cast]
  249 |         return {start, (unsigned)count};
      |                                  ^~~~~
      |                        ---------------
      |                        static_cast<unsigned> (count)
source/lex.h: In Elementfunktion »std::string cpp2::token::to_string(bool) const«:
source/lex.h:267:50: Warnung: Verwendung einer Typumwandlung nach »unsigned int« im alten Stil [-Wold-style-cast]
  267 |         auto text = std::string{start, (unsigned)count};
      |                                                  ^~~~~
      |                                        ---------------
      |                                        static_cast<unsigned> (count)
source/lex.h: In Lambda-Funktion:
source/lex.h:861:43: Warnung: Verwendung einer Typumwandlung nach »int« im alten Stil [-Wold-style-cast]
  861 |                 return (int)(m[0].length());
      |                                           ^
      |                        -----
      |                        static_cast<int> (  )
source/cppfront.cpp: In Elementfunktion »void cpp2::cppfront::emit(const cpp2::binary_expression_node<Name, Term>&)«:
source/cppfront.cpp:3068:53: Warnung: Verwendung einer Typumwandlung nach »using string_view = class std::basic_string_view<char>« {aka »class std::basic_string_view<char>«} im alten Stil [-Wold-style-cast]
 3068 |                     || is_digit(((std::string_view)*rhs_tok)[0])
      |                                                     ^~~~~~~
source/cppfront.cpp: In Elementfunktion »void cpp2::cppfront::emit(const cpp2::declaration_node&, const std::string&)«:
source/cppfront.cpp:4589:58: Warnung: Verwendung einer Typumwandlung nach »using string_view = class std::basic_string_view<char>« {aka »class std::basic_string_view<char>«} im alten Stil [-Wold-style-cast]
 4589 |                     loc += ((std::string_view)*decl.name());
      |                                                          ^
      |                             -
      |                             static_cast<     -
      |                                              > (          )

</pre>

**Comment by hsutter** [comment]
Thanks... yes, I think it's worth being `-Wold-style-cast` clean too. It slightly bothered me that I'd resorted to C-style cast syntax, so now I get to stop having that nag my conscience. :)
