### ISSUE TITLE
[SUGGESTION] f? and c? types

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#297]
Currently the following type aliases are defined in `cpp2util.h`:
- `i8`, `i16`, `i32` and `i64` for various signed integer types
- `u8`, `u16`, `u32` and `u64` for various unsigned integer types

I propose to also define the following type aliases:
- `f16`, `f32`, `f64` and `f128` for various floating-point types

Also this can be done for `char?_t` types, but I'm not sure if it is common:
- `c8`, `c16` and `c32` for various character types

**Comment by leejy12** [comment]
I wish to also have `isize` and `usize` types.

`isize` is equal to `std::ptrdiff_t` and `usize` is equal to `std::size_t`.

**Comment by JohelEGP** [comment]
> `isize` is equal to `std::ptrdiff_t` and `usize` is equal to `std::size_t`.

C++23 has `z` and `uz`.

**Comment by JohelEGP** [comment]
> I propose to also define the following type aliases:
> 
>     * `f16`, `f32`, `f64` and `f128` for various floating-point types

C++23 has those, and `bf16` (https://en.cppreference.com/w/cpp/types/floating-point). According to https://en.cppreference.com/w/cpp/compiler_support, GCC and MSVC implement the feature (there are two rows, one in the language and another in the library). MSVC doesn't implement any of the optional types. It's not clear what GCC provides or not.

**Comment by AbhinavK00** [comment]
Cpp has those as literal suffices, I guess the proposal is for types to have those names

**Comment by hsutter** [comment]
For floating point: I've been tempted to add these, but only [GCC currently supports](https://github.com/gcc-mirror/gcc/blob/52672be7d328df50f9a05ce3ab44ebcae50fee1b/libstdc%2B%2B-v3/include/std/stdfloat#L39-L57) `<stdfloat>` (and even then those aliases are optional so I'd have to repeat those feature test macros)... There's value in providing these if it can be done portably though, so when the C++23 things are not available, is there a robust (i.e., well-known and well-used) and reasonably portable fallback to define them?

For characters: I'd rather not wade into the Unicode swamp and have to decide what of several things `c16` would mean... 😬 taking that on right now feels like a distraction...

**Comment by msadeqhe** [comment]
> I'd worry that means wading into the Unicode swamp and having to decide what of several things `c16` would mean... :grin:  taking that on right now feels like a distraction...

Infact I was thinking about `"text"<c8>` (Literal Templates) when I wrote this suggestion :grinning:.

**Comment by hsutter** [comment]
Thanks again... I haven't seen much more discussion since adding the further-info-request label for this question:

> There's value in providing these if it can be done portably though, so when the C++23 things are not available, is there a robust (i.e., well-known and well-used) and reasonably portable fallback to define them?

So I'll close this issue for now, but please reopen **with a PR** when someone can provide a way to do it the above way and enable it to be a robustly portable feature. Thanks!
