### ISSUE TITLE
[BUG] UTF-32 string literals failure

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#298]
Compile failure for `U` prefix (uppercase) on string literals.

I've tried to compile the following code with [godbolt](https://godbolt.org/noscript/cpp2_cppfront):

```
main: () = {
    x := U"text";
}
```

It should generate the following C++1 code:

```
auto main() -> int{
    auto x {U"text"}; 
}
```

But it fails with the following error:

```
# Compilation provided by Compiler Explorer at https://godbolt.org/
<Compilation failed>
# Compiler exited with result code 1
Standard out:
<source>...
Standard error:

example.cpp2(2,11): error: ill-formed initializer (at '"text"')
example.cpp2(1,12): error: ill-formed initializer (at '{')
example.cpp2(1,1): error: unexpected text at end of Cpp2 code section (at 'main')
example.cpp2(1,0): error: parse failed for section starting here
```

Anyway, I hope there was a plan to get rid of all those unicode prefixes :blush:

**Comment by filipsajdak** [comment]
@msadeqhe, thanks for spotting that - fixed in #299
