### ISSUE TITLE
Discussion: class member functions should be const by default

### ISSUE THREAD

**Issue by marzojr** [hsutter/cppfront#30]
I know that class are still not supported on cppfront; but this makes the discussion even more relevant.

One of the things that lambda functions (arguably) get right is making their `operator()` `const` by default and requiring `mutable` if you want to change data from the lambda.

This should be done also for cpp2 classes. This has the advantages of (1) making lambdas less of a special case, and (2) making const-correct code the default.

This is kind of related to issue #25 .

**Comment by hsutter** [comment]
That's the intent, and it just falls out of making `in` parameters the default. Classes will use explicit `this` which, like all parameters, defaults to `in` and therefore `const`.

I've added this to the [Design note: const objects by default](https://github.com/hsutter/cppfront/wiki/Design-note:-const-objects-by-default). Thanks!
