### ISSUE TITLE
[SUGGESTION] Support (some) C++ alternative tokens

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#304]
I prefer writing (`and`, `or`) to (`&&`, `||`). Currently, they're treated as identifiers. So `cppfront` emits an error if used C++1-correctly (`x = y and z;`, 3 identifiers in a row is ill-formed), or emits bad C++1 code (`x = and;`).

https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-unary-operators-vs-binary-operators talks about "alternative tokens". It seems they were supported at some point before this repository was published.

**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?** No (my guess).

**Will your feature suggestion _automate or eliminate_ X% of current C++ guidance literature?** No (my guess).

**Describe alternatives you've considered.**
1. Rejecting the suggestion. It goes against https://github.com/hsutter/cppfront/blob/main/.github/ISSUE_TEMPLATE/suggestion.md?plain=1#L10-L13 (it'd be easier to read the source if https://sembr.org/ was followed).
2. Recognize them and
  - diagnose an use and suggest its alternative, or
  - try to emit valid C++ identifiers in their place (e.g., renaming to `_and`, with no portable way to name them from C++1).

**Comment by AbhinavK00** [comment]
I think having the bitwise operators spelled out would eliminate more ambiguity than spelling out the logical operators. For example:
```cpp

a&&b; //what if a and b are not bool? This is the kind of context cpp2 tries to eliminate ig?
```
That would also reserve `^` for pointer deference(wow!!) and could also eliminate ambiguity between bit shift operators and when writing template template parameters.

**Comment by JohelEGP** [comment]
`not` is another one I use. So much that I have Clang-Format [insert a space after `!`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spaceafterlogicalnot) so that it stands out in case I forget to use it (`! x` -> `not x`).

In Cpp2, they should be keywords, not alternative tokens. Then there's no chance you can use it weirdly, like in Cpp1 (e.g. `x and = y;`).

**Comment by AbhinavK00** [comment]
How would we write ` x != y` with this change? Or is the plan to support both tokens?

**Comment by JohelEGP** [comment]
I did notice that `not_eq` is a thing when checking out https://eel.is/c++draft/lex.digraph.

I'm not proposing banning using operators. So you choose to write it however you like. Including using `std::not_equal(x, y)`.

**Comment by JohelEGP** [comment]
There's some mentions of an `and` keyword and more starting at https://github.com/hsutter/cppfront/issues/152#issuecomment-1332096613.
