### ISSUE TITLE
[QUESTION] Is there any difference between `10 as int` and `:int = 10`?

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#306]
The following `as` and `:type` examples do the same thing:

```
#include <optional>

main :() = {
    number := 10;

    x1 := (number as int);
    y1 := (:int = number);

    x2 := (number as int as long);
    y2 := (:long = :int = number);

    x3 := (number as std::optional<int>);
    y3 := (:std::optional<int> = number);
}
```

I'm thinking can we consider they are the same but in different syntaxes?

**Comment by filipsajdak** [comment]
`number as int`  is casting `number` to `int`.

`:int = number` is creating anonymous `int` and initializes it with the `number` value.

It is just a matter of your intentions. In general, the syntax is as follows:
```cpp
{name}: {type} = {value};
```

1. You can skip the `{name}` (`: {type} = {value};`) and create anonymous `{value}` of `{type}` aka temporary variable.
2. You can skip the `{value}` (`{name}: {type};`) and create the uninitialized variable.
3. You can skip the `{type}` (`{name}:= {value};`)  and create a variable with deduced type.

You cannot mix the above points - you can skip only one part at a time. And this syntax works everywhere (one of the goals of cppfront: is to have context-free syntax).

The cool thing I have discovered in the past is:
* lambda syntax: `:(x) -> int = { return 42; }` is just an anonymous function `fun:(x) -> int = { return 42; }`  (check here: https://github.com/hsutter/cppfront/issues/257),
* for loop also has an anonymous function used: `for container do :(element) = {}`

**Comment by JohelEGP** [comment]
Maybe not for those types. `:type = value` probably compiles to some form of direct-initialization. But `as` can do more than that. See https://wg21.link/P2392 §2.2.

**Comment by AbhinavK00** [comment]
Question: What is the preferred way of declaring variables out of these two ways?
```cpp

number1 := 10 as u64;
number2 : u64 = 10;
```

or for contructor calls
```cpp

vec1 := (1,2) as std::vector;
vec2 : std::vector = (1,2);
```
 Which is the preferred and faster (if any) way?

Plus, how do I create a vector of N elements with each value k? Can't figure that out

**Comment by JohelEGP** [comment]
> Which is the preferred and faster (if any) way?

If `as` performs a direct-initialization, like `T(v)`, they should be the same. If the target type is something more complicated, like a reference type, `as` might do something else (check the linked proposal).

> Plus, how do I create a vector of N elements with each value k? Can't figure that out

I think this was discussed at #193.

**Comment by filipsajdak** [comment]
I cannot check it now but I think that
```cpp
vec1 := (1,2) as std::vector;
```
Might not compile.

**Comment by filipsajdak** [comment]
@AbhinavK00 in the Suggestion template @hsutter emphasise:

> _Please do not suggest syntax changes._ I accept there are hundreds of opinions and everyone will prefer something a little different. Syntax isn't the big thing, fixing semantics is -- reducing concept count, increasing toolability, are the big payoff.

I am not against it but please don't expect them to be included as it is not supporting Herb goals.

**Comment by AbhinavK00** [comment]
I'm sorry but they're actual features not just syntax change. I'm trying a way to do away with initialiser lists, can't think of a full proposal so I just suggest small changes.

**Comment by JohelEGP** [comment]
> Plus, how do I create a vector of N elements with each value k? Can't figure that out

`std::vector(N, k)`, which has the same meaning as in C++1. See https://github.com/hsutter/cppfront/issues/193#issuecomment-1370624659.

**Comment by filipsajdak** [comment]
Do we have initializer lists in cpp2?

**Comment by JohelEGP** [comment]
We have parentheses. With Cpp2 initialization, it compiles down to a _braced-init-list_.

`std::vector(N, k)` is an usual C++1 expression, so it's left alone, and calls a non-`std::initializer_list` constructor.

**Comment by AbhinavK00** [comment]
> std::vector(N, k), which has the same meaning as in C++1.

Yea, but it's the cpp1 way. Cpp2 way would be something like

```y : std::vector = SOMETHING;```

That's how we do it with classes in cpp2, the only one and right way.

**Comment by JohelEGP** [comment]
`std::vector(2, 3) != (: std::vector = (2, 3))`, the former is $(2, 2, 2)$ or $(3, 3)$, and the latter is $(2, 3)$.

**Comment by filipsajdak** [comment]
Mnne

**Comment by msadeqhe** [comment]
> Maybe not for those types. `:type = value` probably compiles to some form of direct-initialization. But `as` can do more than that. See https://wg21.link/P2392 §2.2.

So in a nutshell, `as` is for pattern matching and dynamic cast in addition to static cast similarity with `:type = variable`, right?

**Comment by msadeqhe** [comment]
> `number as int` is casting `number` to `int`.
> 
> `:int = number` is creating anonymous `int` and initializes it with the `number` value.
> 
> It is just a matter of your intentions.

Therefore the result of both is the same but in different approaches for static casting.
