### ISSUE TITLE
Pointless experiment

### ISSUE THREAD

**Issue by smallB007** [hsutter/cppfront#31]
Sorry to be that guy but the whole "experiment" with new c++ syntax is rather pointless.
We already have that: It is called Rust and does everything and more than cppfront2 is trying to poorly mimic and imitate.
Also, one of main selling points for rust like explicit lifetimes controlled by the compiler - this is simply not gonna happen in cpp. So basically Herb is trying to create/promote knock-off technology that is already outdated...

**Comment by JohelEGP** [comment]
Seems like a good issue to keep open. If it's pinned, there will be less duplicates. It also serves as a justification for closing duplicates.

As a remainder, there's an "Unsubscribe" button for this issue:
![1664535235](https://user-images.githubusercontent.com/21071787/193255098-e43474f0-0d87-497c-a777-32ce39d153a1.png)

**Comment by Su5eD** [comment]
Experimenting is completely fine, I'm rather concerned about the non-free license

**Comment by JohelEGP** [comment]
Well, don't let that discussion get buried in this issue. Open it's own well-deserved one.

**Comment by smallB007** [comment]
> Seems like a good issue to keep open

Not to herb... Why I am not surprised...

**Comment by JohelEGP** [comment]
The updated issue templates are a good barrier.

**Comment by suy** [comment]
> Not to herb... Why I am not surprised...

Given the lack of quality of the "reported issue", I am not surprised.

Because comparing Rust with a new syntax for C++ and concluding that one is like the other but worse ("does everything and more than cppfront2 is trying to poorly mimic") is not even missing the point of compatibility, is being dishonest about the whole conversation about it. If you don't care about compatibility at all, and you think a clean break is good for you, great, go do that. But this code is about improving C++, not abandoning it.

**Comment by smallB007** [comment]
Lack of quality, hate, etc etc.
Yeah, right got ya...
It is not about comparing Rust with new syntax for C++, which btw is (making an attempt to create new syntax) actually pointless on its own.
Its about not seeing that C++ as a technology is outdated and no amount of any, even "the best" syntax is not going to bring to the table what Rust is bringing out of the box.
I mean seriously? New syntax?
Herb is trying to find niche for himself as he is trying to do for years. I'm sad to say that he failed with literally every major project of his. Managed C++, that he was so careful not to mention that he was the guy behind it, and only mentioned it long after the time to be honest and decent about it and admit it passed. Another one, strong influence on initial release of C++11 features or rather lack of them in Visual Studio I believe it was VS2010. There was that infamous library (casablanca or something like that) that he I believe was key creator of it and nobody wants to use it because it is awful and literally undebuggable...

**Comment by BenHanson** [comment]
Microsoft should simply hire Sean Baxter and get this project done.

I wish this cppfront all the success in the world, but so far it's looking like an open-source mosh pit to me.
