### ISSUE TITLE
[BUG] variable used in if condition is moved despite it is used in the if statement

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#311]
In the current implementation of cppfront (b370ab880e06110ae477ea0b2545778526deb34d), the following code:

```cpp
main: () = {
    b : bool = true;

    if b {
        std::cout << b << std::endl;
    }
}
```
Generates:
```cpp
auto main() -> int{
    bool b {true}; 

    if (std::move(b)) {
        std::cout << std::move(b) << std::endl;
    }
}
```

The `b` variable is moved in the if condition despite its use in the if statement.

Adding the use of `b` after an if removes the move of `b` in the if condition and if statement which is correct.

**Comment by filipsajdak** [comment]
Adding an `else` with another use of `b` in statement-false also adds move:
```cpp
auto main() -> int{
    bool b {true}; 

    if (std::move(b)) {
        std::cout << std::move(b) << std::endl;
    }else {
        std::cout << !(std::move(b)) << std::endl;
    }
}
```

**Comment by hsutter** [comment]
Thanks! These cases should work now, if not please reopen.

**Comment by filipsajdak** [comment]
Confirmed. Fixed.
