### ISSUE TITLE
[BUG] UFCS doesn't work at namespace scope

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#314]
**Describe the bug**
`error: non-local lambda expression cannot have a capture-default`.

**To Reproduce**
1. Sample code - distilled down to minimal essentials please
```Cpp
f: (x)->int = 0;
y: int = 0.f();
```

<details><summary>Generated code</summary>

```
//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"


//=== Cpp2 type definitions and function declarations ===========================

#line 1 "x.cpp2"
[[nodiscard]] auto f(auto const& x) -> int;
extern int y;
//=== Cpp2 function definitions =================================================

#line 1 "x.cpp2"
[[nodiscard]] auto f(auto const& x) -> int { return 0;  }
int y {CPP2_UFCS_0(f, 0)}; 
```

</details>

2. Command lines including which C++ compiler you are using
```
~/root/bin/cppfront x.cpp2 
~/root/clang/bin/clang++ -std=c++20 -I $CPPFRONT_INCLUDE_DIR x.cpp
```
```
clang version 17.0.0
```

3. Expected result - what you expected to happen
UFCS to work at namespace scope. By using a different macro that doesn't use a _capture-default_.

4. Actual result/error
```
x.cpp2:2:8: error: non-local lambda expression cannot have a capture-default
int y {CPP2_UFCS_0(f, 0)}; 
       ^
/home/johel/Documents/C++/Forks/cppfront/include/cpp2util.h:646:2: note: expanded from macro 'CPP2_UFCS_0'
[&](auto&& obj) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
 ^
1 error generated.
```

**Comment by filipsajdak** [comment]
@JohelEGP I think it would be good to see what cpp1 code is generated (in such issues).

I will generate it by myself but it will give more context than the error message from cpp1 compiler.

**Comment by JohelEGP** [comment]
Good idea. Updated, rebased on main.

**Comment by filipsajdak** [comment]
@JohelEGP your lamda returns void.

Please correct your code to:
```cpp
f: (x) -> _ = 0;
y := 0.f();
```

**Comment by filipsajdak** [comment]
Ah, your updated code is fine.

**Comment by hsutter** [comment]
Thanks! Fixing in next commit...

**Comment by hsutter** [comment]
Incidentally, I think you win the prize for the issue that is resolved by the commit that **exactly doubles** the line count of cppfront from the day I first introduced it at CppCon 2022 about six months ago when it was 9 KLOC... this commit just took us over the 18 KLOC mark. (Still quite svelte! Circle is over 10x as big I think.)

**Comment by JohelEGP** [comment]
> the issue

The first issue so far. ☺

I'm looking forward to the seeing the numbers when `cppfront` self-hosts.
