### ISSUE TITLE
Add operator<< for standard containers. 

### ISSUE THREAD

**Issue by dasfex** [hsutter/cppfront#32]
It is very trivial task which I met every day more than 5 years. And in C++ we should write something like
```cpp
std::vector<int> v;
...
for (auto x : v) {
  std::cout << x << ' ';
}
```

If we can replace this with
```cpp
std::cout << v;
```

it also can reduce language complexity. This is very easy feature which exists in every modern programming language. But C++ does not have that : (

**Comment by JohelEGP** [comment]
Use `fmt::print` from `fmt{}`.

**Comment by marzojr** [comment]
For what is worth, this functionality has also been added to std::format and std::print for c++23.

**Comment by hsutter** [comment]
I agree this should be easy to do and I'm glad C++23 is doing it... Yes, let's rely on `std::format` and `std::print`. Thanks!

**Comment by JohelEGP** [comment]
Support is not there yet (https://en.cppreference.com/w/cpp/compiler_support):
![1664930603](https://user-images.githubusercontent.com/21071787/193955614-ef6af6a6-f8db-4902-b7d3-3d0c24909f91.png)
![1664930610](https://user-images.githubusercontent.com/21071787/193955618-5b28bbae-5f2c-4e43-a1e3-742105e4c9bc.png)
![1664930619](https://user-images.githubusercontent.com/21071787/193955619-805939d9-d84b-4257-b350-725b5724b19a.png)
