### ISSUE TITLE
[QUESTION] C++2 without `void`

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#324]
Function return type is the only safe way to specify `void` type:

```
func: () -> void = { }
```

If we don't specify the function return type in C++2, its going to be `void` by the way:

```
func: () = { }
```

`void` is an incomplete type, also `void*` isn't safe to cast from. I'm thinking that "Can C++2 completely remove `void` from its type system?". I think the problem is C APIs which require `void`... right?

**Comment by JohelEGP** [comment]
> `void*` isn't safe to cast from

It seems that we'll be getting the subset that is safe for C++26 during constant evaluation. See https://github.com/brevzin/cpp_proposals/issues/60.

**Comment by msadeqhe** [comment]
Thanks. Also C++2 has `is void` since [this commit](https://github.com/hsutter/cppfront/commit/98f6dd46957e100f813245241f183c8aedbcb36f). I think because of compatibility with C APIs, it is not possible (at least easily) to eliminate `void` from type system.
