### ISSUE TITLE
Global variable segfaults

### ISSUE THREAD

**Issue by ntrel** [hsutter/cppfront#326]
```c++
g := 4
```
```
nick@nmt-pc:~/git/cppfront$ ~/cppfront ~/old/test.cpp2 
Segmentation fault (core dumped)
```
With git 827ed79d71a8b39f35894019b4dde695a2d83ef5.

**Comment by filipsajdak** [comment]
@ntrel there is missing `;` on the end of the line but it should not crash. If you are willing to try to contribute to cppfront that might be an easy start (look in `parse.h`) - actually you will find the proper line in the debugger.

**Comment by hsutter** [comment]
Fixed. Thanks!
