### ISSUE TITLE
[BUG] `T` data member before `this: T` data member is ambiguous

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#333]
`cpp2::store_as_base<T>` inherits from `T`, which results in ambiguity if a non-`this` data member and a following `this` data member have the same type.

**Minimal reproducer**:
```Cpp2
x: type = { }
z: type = {
  a: x;
  this: x;
}
```

Commands:
```bash
cppfront x.cpp2
clang++17 -std=c++2b -I $CPPFRONT_INCLUDE_DIR -c x.cpp
```

Expected result: Banning this case from Cpp2, or a well-formed program (perhaps by following <https://www.boost.org/doc/libs/release/libs/utility/doc/html/utility/utilities/base_from_member.html>).

Actual result and error:

<details><summary>Generated C++1</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

#line 1 "x.cpp2"
class x;
class z;

//=== Cpp2 type definitions and function declarations ===========================

#line 1 "x.cpp2"
class x {};
class z: private cpp2::store_as_base<x>, public x {

#line 5 "x.cpp2"
};

//=== Cpp2 function definitions =================================================



```

</details>

```output
x.cpp2:2:42: warning: direct base 'x' is inaccessible due to ambiguity:
    class z -> cpp2::store_as_base<x> -> class x
    class z -> x [-Winaccessible-base]
class z: private cpp2::store_as_base<x>, public x {
                                         ^~~~~~~~
1 warning generated.
```

**Comment by hsutter** [comment]
Thanks! D'oh, why did I even use private inheritance (after just railing against it again) 👃🐀
