### ISSUE TITLE
[BUG] `public` non-`this` data member has no effect

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#336]
`public this:` is disallowed. But before a `this` data member, a `public` non-`this` data member is not diagnosed, and has no effect.

**Minimal reproducer**:
```Cpp2
x: type = { }
y: type = { }
z: type = {
  public a: x = x();
  this: y = ();
  operator=: (out this) = { }
}
w: x = z().a;
```

Commands:
```bash
cppfront x.cpp2
clang++17 -std=c++2b -stdlib=libc++ -I $CPPFRONT_INCLUDE_DIR x.cpp
```

Expected result: A well-formed program, or a diagnostic.

Actual result and error:

<details><summary>Generated C++1</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

#line 1 "x.cpp2"
class x;
class y;
class z;

//=== Cpp2 type definitions and function declarations ===========================

#line 1 "x.cpp2"
class x {};
class y {};
class z: private cpp2::store_as_base<"a",x>, public y {

#line 6 "x.cpp2"
  public: z();
};
extern x w;
//=== Cpp2 function definitions =================================================


#line 6 "x.cpp2"
  z::z()
                            : cpp2::store_as_base<"a",x>{ x() }
#line 6 "x.cpp2"
  {}

x w {z().a}; 

```

</details>

```output
x.cpp2:8:10: error: no member named 'a' in 'z'
x w {z().a}; 
     ~~~ ^
1 error generated.
```

**Comment by JohelEGP** [comment]
If the position of a non-`this` data member, with respect to a `this` data member, shouldn't change behavior, perhaps the generation of a base class is the answer:
```C++
struct cpp2_a_for_z {
  x a;
};
class z : public cpp2_a_for_z // ...
```

**Comment by JohelEGP** [comment]
I noticed that `public` does affect the following data member.
```Cpp2
  public a: x = x();
  this: y = ();
```
```C++
class z: private cpp2::store_as_base<"a",x>, public y {
```

**Comment by hsutter** [comment]
Thanks!

> perhaps the generation of a base class is the answer:

Hmm, you may have something there. I thought of several ways but didn't think of that one -- thank you.

> I noticed that public does affect the following data member.

No, that one is just because my current experiment is to require that all base types are public, so `this: y` is implicitly public (and can't be declared with any other accessibility).

**Comment by JohelEGP** [comment]
> On second thought, I wonder if I would then have to echo the constructors the same way again, and that would lead to a lot more generated code.

How about using an aggregate base class that holds a `T`? `cpp2::store_as_base`, as currently specified, introduces an [extra indirection](https://quuxplusone.github.io/blog/2022/06/03/aggregate-parens-init-considered-kinda-bad/#first-aggregate-initialization-i) in the initialization: 
```Cpp2
a: type = {
  b: int = 0;
}
// Directly initializes `b` from `0`.
c: a = ();

// If we could make an aggregate:
// d: type = {
//   public e: int;
// }
// // Directly initializes `e` from `0`.
// f: d = (0);

g: type = {
  h: int;
  operator=: (out this, x: int) = h = x;
}
// Initializes `x` from `0`, then `h` from `x`.
i: g = 0;

j: type = { }
k: type = {
  l: int = 0;
  this: j = ();
  m: int = 0;
  operator=: (out this) = { }
  operator=: (out this, x: int, y: int) = {
    l = x;
    m = y;
  }
}
// Initializes `QoI` from `0`, then `l` from `std::move(QoI)`.
// Directly initializes `m` from `0`.
n: k = ();
// Initializes `x` from `0`, then `QoI` from `x`, then `l` from `std::move(QoI)`.
// Initializes `y` from `1`, then `m` from `y`.
o: k = (0, 1);
```

**Comment by hsutter** [comment]
Thanks @JohelEGP for that aggregate base suggestion, that's nicer -- done in the commit I just pushed
