### ISSUE TITLE
Discussion: Allowing "unsafe" features in explicit contexts

### ISSUE THREAD

**Issue by switch-blade-stuff** [hsutter/cppfront#34]
While I do understand and support the drive to avoid using unsafe features such as raw unions, pointer arithmetic, unsafe casts, etc. It is sometimes necessary to use these features, for example, when interfacing with low-level code, hardware, or simply implementing a higher-level structure (ex. a custom memory allocator or a hash table). For example, you may want to store trivial CPU-specific types in a union for intrinsics. While there are ways to replace unions and pointer arithmetic with `variant` and friends, in these low-level tightly controlled situations they either are not applicable, or will require more overhead than might be necessary.

For these situations, you would have to implement your low-level code in syntax1, then use it in you syntax2 code. This might become very tedious and complicated, especially when you need to use the unsafe code in a header, you'd have to split your implementation in syntax1/syntax2 headers and would have something akin to `my_table.hpp2` and `my_table.hpp`, with the user only being allowed to include the `hpp2` file. Which, i think you'd aggree would just complicate design and maintnance.

As such, why not enable the developer to explicitly allow unsafe code in certain situations, such as via an `unsafe` keyword applied to a structures, functions, variables or code blocks. Code and data tagged as `unsafe` would then be allowed to use unions, pointer arithmetic, and other low-level unsafe features, without having to separate safe/unsafe code among multiple files.

This way you can implement your embeded binary, hardware driver, custom heap allocator and whatever need be in syntax2 files, while using "modern" and safe code, and only drop down to unsafe context in very few situations with surgical precision.

**Comment by hsutter** [comment]
Good question... I've had this question a few times this week, so I've written up my answer here: [Design note: Unsafe code](https://github.com/hsutter/cppfront/wiki/Design-note:-Unsafe-code). Thanks!
