### ISSUE TITLE
[SUGGESTION] Enable `that` for binary operators

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#345]
I naturally want to write `operator==: (this, that) -> bool = true;`.
But I'm met with `x.cpp2(2,22): error: only an operator= function may have a 'that' parameter`.
See https://godbolt.org/z/d6Esh44rs.

`operator=` is already rather special.
This suggestion eliminates future guidance.
`this` and `that` are
- > always the current type
  > -- https://github.com/hsutter/cppfront/wiki/Cpp2:-operator=,-this-&-that#that-is-explicit-used-for-copymove
- and behave specially on `operator=`,
- but only `this` can be used elsewhere with sensible semantics.

I want to use `that` like `this`, too.

**Comment by orent** [comment]
Either enable “that” for all binary operators - or make it less of a special case.

It can be just another identifier. The only special thing about it would be that it has the default type of decltype(this) if used as a method argument with no explicit type.  

It is useful for methods that operate within a closed domain whether or not they are an overloaded operators. 

(Is “This” as decltype(this) a thing in cpp2?)

**Comment by filipsajdak** [comment]
@orent cpp2 `this` is cpp1 `(*this)`

**Comment by orent** [comment]
> @orent cpp2 `this` is cpp1 `(*this)`

Yes, that’s why I wrote decltype(this) rather than decltype(*this)

**Comment by hsutter** [comment]
Indeed, and the machinery was pretty much already there -- when I removed that check, it seems to just work. Done! Commit coming...

Now the only remaining (arbitrary?) requirement is that it's the second parameter.

**Comment by hsutter** [comment]
BTW when I said "seems to just work" I didn't try a lot of test cases, but I did try things like that the right type was generated for `in that` and `move that`, and for `move that` to make sure that `std::move(that).member` was getting generated.

Seems like it Just Works. (As it should, I wrote the `that` code generally and not hardwired into `operator=` only... but it's normal to find a few bugs when using a feature in a new area, so I'm a little surprised me that I didn't yet hit any bugs I had to tweak in other use cases. LMK if/when you find some though, I'm sure there'll be some.)

**Comment by hsutter** [comment]
Re `move that` passing by `&&`: For some reason I commented out the condition, just had to uncomment it. Now things look right as far as I can see...

**Comment by orent** [comment]
Now just add “these” and “those” 😉

**Comment by JohelEGP** [comment]
Another restriction seems to be (<https://cpp2.godbolt.org/z/xsx5eEfWY>):
```output
main.cpp2(2,32): error: a 'that' parameter must be in or move
```
```Cpp2
t: type = {
  swap: (inout this, inout that) = { }
}
main: () = { }
```

**Comment by jcanizales** [comment]
> Now just add “these” and “those” :wink: 

Spanish has, from closest to farthest: "este" (this), "ese" (that), and "aquel" (that one over there). Cppfront not powerful enough smh
