### ISSUE TITLE
[BUG] _expression-statement_ of unnamed templated function is a `template`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#346]
A `template` was generated, not a lambda expression.

**Minimal reproducer** (https://godbolt.org/z/56cecbYMh):
```Cpp2
f: () = :<T> () = {};
```

**Commands**:
```bash
cppfront x.cpp2
clang++17 -std=c++2b -stdlib=libc++ -I $CPPFRONT_INCLUDE_DIR x.cpp
```

**Expected result**: A lambda expression when lowering to C++.

**Actual result and error**:

<details><summary>Generated C++1.</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"


//=== Cpp2 type definitions and function declarations ===========================

#line 1 "x.cpp2"
auto f() -> void;

//=== Cpp2 function definitions =================================================

#line 1 "x.cpp2"
auto f() -> void { template<typename T> []() -> void{};  }

```

</details>

```output
x.cpp2:1:20: error: expected expression
auto f() -> void { template<typename T> []() -> void{};  }
                   ^
1 error generated.
```

**Comment by JohelEGP** [comment]
Is the final `;` necessary? The grammar suggests it isn't, but it doesn't work otherwise.
```Cpp2
f: () = :<T> () = {};
```

**Comment by filipsajdak** [comment]
@JohelEGP I am not sure if I get Your question right.

```cpp
f: () = :<T> () = {};
```

Is similar to the following code:

```cpp
f: () = 42;
```

Where `42` and `:<T> () = {}` are unnamed objects. So, I guess a semicolon is required. 

The `f` function does not return anything - is it intentional? I am asking as by default functions return `void` (if not specified otherwise).

**Comment by JohelEGP** [comment]
Looking closer, both a `template` and a lambda were generated:
```C++
auto f() -> void { template<typename T> []() -> void{};  }
```

**Comment by filipsajdak** [comment]
Generic lambdas with an explicit list of types are not yet supported.

But they should - to have symmetry between named and unnamed functions.

**Comment by JohelEGP** [comment]
You're right. I thought it did work. Turns out I had used non-generic ones, and I tried a generic one as an _expression-statement_, which led me to believe that was the reason.

**Comment by filipsajdak** [comment]
I have a PR that will enable support for them... I will run the last tests and will push it.

**Comment by filipsajdak** [comment]
@JohelEGP I have pushed the PR: #349
