### ISSUE TITLE
[QoI] Improve cryptic error message due to accidental semicolon

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#352]
The source locations are nowhere near the semicolon. The implementation should know when a semicolon is not needed, so the error message can be more to the point.

**Minimal reproducer** (https://godbolt.org/z/5Eovbx4Yb):
```Cpp2
g: () = { }
f: () = {
  for v* | all next log() do :(e) = {
    foo();
    bar*;
  };
  g();
}
```

**Commands**:
```bash
cppfront x.cpp2
```

**Expected result**: A diagnostic indicating to remove accidental semicolon.

**Actual result and error**:

```output
x.cpp2(2,9): error: ill-formed initializer (at '{')
x.cpp2(2,1): error: unexpected text at end of Cpp2 code section (at 'f')
x.cpp2(1,0): error: parse failed for section starting here
```

**Comment by JohelEGP** [comment]
I got curious about how `cppfront` would handle `$` in identifiers: <https://godbolt.org/z/9WaejfYas>.
```C++
int x$x = 0;
main: () = {
  :() = x$x;
}
```
The same error message, `error: unexpected text at end of Cpp2 code section (at 'f')`. In addition to the name of the declaration, if possible, the line's tail of the unexpected text could be printed, e.g. `error: unexpected text at end of Cpp2 code section for 'f' at 'x;'`.

**Comment by JohelEGP** [comment]
With <https://github.com/hsutter/cppfront/issues/358#issuecomment-1504006051> in mind, I think I know what's going on. Copying from the OP:
```Cpp2
g: () = { }
f: () = {
  for v* | all next log() do :(e) = {
    foo();
    bar*;
  };
  g();
}
```
```output
x.cpp2(2,9): error: ill-formed initializer (at '{')
x.cpp2(2,1): error: unexpected text at end of Cpp2 code section (at 'f')
x.cpp2(1,0): error: parse failed for section starting here
```

- `f` doesn't match any _declaration_: `x.cpp2(2,1): error: unexpected text at end of Cpp2 code section (at 'f')`.
- The preceding error is barely closer to the offending `;`: `x.cpp2(2,9): error: ill-formed initializer (at '{')`.

When I watched the talk that unveiled `cppfront` and came to try it out, more than a few times I wished the error messages were more telling. As a C++ programmer, I guessed it wouldn't want to go down the path of template error messages.

Error messages have been improving. But in particular, those with a stack of source locations, like the one above, seemed like they could do better.

Now, I think it should be possible to improve the status-quo. The parser could keep a record of the furthest it got.
For the OP, I think it should generally be possible to additionally diagnose something like this:
```output
x.cpp2(6,4): error: unrecognized statement (at ';')
x.cpp2(3,3): note: previous statement (at 'for').
```

**Comment by filipsajdak** [comment]
@JohelEGP I have made some improvements in diagnostics regarding semicolons. I am running tests - it there will be no impact I will push it.

**Comment by filipsajdak** [comment]
I have pushed the PR: #362

**Comment by filipsajdak** [comment]
After my PR the following code:
```cpp
int x$x = 0;
main: () = {
  :() = x$x;
}
```
produces:
```
bug_352_error_message_semicolon.cpp2...
bug_352_error_message_semicolon.cpp2(3,11): error: bad statement! (at 'x')
```
