### ISSUE TITLE
[BUG] alias: type == _ generates invalid cpp1

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#357]
**Minimal reproduce**
`alias5: type == _;`
passes succssfully cpp2, but generates invalid cpp1:
`using alias5 = auto;`

**Command lines including which C++ compiler you are using**
`cppfront example.cpp2 -p`
(build from latest mai. https://github.com/hsutter/cppfront/commit/f83ca9b727e9c07f60a1933584a49a3d971936f5 with clang++-15)
Then cpp1 compiled with
`clang++-15 -Icppfront/include $1.cpp -std=c++20 -o $1`

**Actual result/error**
Cppfront passes with
`example.cpp2... ok (all Cpp2, passes safety checks)`
But then clang fails with
`error: 'auto' not allowed in type alias using alias5 = auto;`

**Expected result**
Diagnostic at cpp2 side. (I guess that`s strategy, to catch whatever possible cpp2 relateed before relying on cpp1 compiler?)

**Additional context**
This is extreme case, because clang says `auto` is never allowed. 
There is other case
`alias6: type == foo` when `foo` is not defined generates correct
`using alias6 = foo;`
But I guess this can be separate issue, for should cppfront check if alias goes to something undefined.

**Comment by JohelEGP** [comment]
> But I guess this can be separate issue, for should cppfront check if alias goes to something undefined.

This is better left off to the C++1 compiler to diagnose. Otherwise, `cppfront` would have to be a C++1 compiler to know if it's ill-formed.

**Comment by filipsajdak** [comment]
We can diagnose cases like:
```cpp
alias5: type == _;
```

**Comment by filipsajdak** [comment]
Change that provides diagnostics for a wildcard: #360

**Comment by realgdman** [comment]
Great.
BTW what do you think about cases like that? Currently they're passed successfully to cpp1 and fail there.
`alias8: == ();`
`alias9: == (int);`
