### ISSUE TITLE
Discussion: Defer Control Flow

### ISSUE THREAD

**Issue by jdbener** [hsutter/cppfront#36]
The C stdio UFCS example got me thinking about a `defer` control flow construct which would run the statement or block after it when the current scope would be exited. This would allow the the C stdio example to be rewritten as: 
```cpp
main: () -> int = {
    s: std::string = "Fred";
    myfile := fopen("xyzzy", "w");
    defer myfile.fclose(); // Run at the end of the scope
    myfile.fprintf( "Hello %s with UFCS!", s.c_str() );
}
```
Which doesn't do much in this example, but in more complicated cases where error handling gets involved it could become useful. I know RAII wrappers are the "idiomatic" C++ solution to this problem, but there are times (especially while prototyping) where writing a wrapper is unnecessarily clunky. In the past I have used some macro and lambda wizardry along with some scope guard libraries to implement almost this exact functionality in Syntax1. Thus implementing backend support for this type of feature in the cpp2 supplemental library should be straightforward...

But with all of this factors considered, would this sort of feature even be worth including in Syntax2? Or is it just another unnecessary feature to steal from Go for the sake of stealing it?

**Comment by lohika-denis-kotov** [comment]
@jdbener 
> The C stdio UFCS example got me thinking about a `defer` control flow construct which would run the statement or block after it when the current scope would be exited. This would allow the the C stdio example to be rewritten as:
> 
> ```c++
> main: () -> int = {
>     s: std::string = "Fred";
>     myfile := fopen("xyzzy", "w");
>     defer myfile.fclose(); // Run at the end of the scope
>     myfile.fprintf( "Hello %s with UFCS!", s.c_str() );
> }
> ```
> 
> Which doesn't do much in this example, but in more complicated cases where error handling gets involved it could become useful. I know RAII wrappers are the "idiomatic" C++ solution to this problem, but there are times (especially while prototyping) where writing a wrapper is unnecessarily clunky. In the past I have used some macro and lambda wizardry along with some scope guard libraries to implement almost this exact functionality in Syntax1. Thus implementing backend support for this type of feature in the cpp2 supplemental library should be straightforward...
> 
> But with all of this factors considered, would this sort of feature even be worth including in Syntax2? Or is it just another unnecessary feature to steal from Go for the sake of stealing it?

C++ do not need the `defer` keyword, we have a RAII instead

**Comment by hsutter** [comment]
I agree, we have RAII.

We also have LFTS3 `scope_exit` and GSL's `finally`/`final_action` (the latter is partly in `cpp2util.h` already).

I just added a similar `c_raii`, we'll see if people find it useful.
