### ISSUE TITLE
[SUGGESTION] Don't allow unused value inside function body

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#364]
I understand that it may be difficult to implement on cppfront side.

Consider the following, it's easy to write by mistake
`foo: ()->int = 42;`
`bar: ()->int = { 13; } //value discarded; non-void function returns nothing`

`main: () -> int = {`
`  std::cout << foo() << bar();`
`}`

In that case of course cpp1 will  give a warning about `bar` not returning value, but if it's not enforced that would be UB and crash. 
But may be it is possible to track in cppfront if function has return value, return paths etc.

**Comment by filipsajdak** [comment]
We can improve on these examples. General rule of cpp2 is to use `[[nodiscard]]` whenever possible. Here you are "discarding" literal which, most certainly, is a mistake you would like to avoid.

**Comment by filipsajdak** [comment]
Fix pushed: #365
