### ISSUE TITLE
[SUGGESTION] Definite first assignment to return `this`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#368]
At <https://github.com/hsutter/cppfront/pull/366#issuecomment-1506153367>,
we discovered that a definite first assignment has type `void`.

Returning an lvalue reference to the object parameter
is only a convention in [user-provided][] `operator=` (C++𝘕).
That's the language's default,
and what is expected of a [regular][] type.

There should be worth in Cpp2 unifying not only syntax,
but also the semantics of its `operator=`.

This should eliminate future guidance
around a first assignment behaving differently on whether it's definite.

It should be worth noting that
the C++1 methods to [delay object creation][]
return a reference or pointer to the created object.
The C++ standard library follows suit,
and I can't come up with a reason for Cpp2 not to.

[user-provided]: https://eel.is/c++draft/dcl.fct.def.default#def:user-provided
[regular]: https://eel.is/c++draft/concept.assignable#1.4
[delay object creation]: https://eel.is/c++draft/intro.object#1.sentence-2

**Comment by JohelEGP** [comment]
This does mean that,
like assignment,
an initializing `=` expression will have to be discarded.
```Cpp2
s: std::string;
_ = s = "";
```

**Comment by hsutter** [comment]
> There should be worth in Cpp2 unifying not only syntax,
> but also the semantics of its `operator=`.

Thanks. I agree with being consistent.

But (contrarian here) I was actually thinking of going the other way:

**Option 1:** Have assignment return `void` which would disallow chained assignments. I vaguely remember discussing that here in another issue(?) where I think someone came up with an example where `operator=` returning non-void was useful for something other than chaining, but I don't remember it now.

and/or

**Option 2:** Leave assignment alone for Cpp1 compatibility, but disallow writing chained assignments in Cpp2 code.

I think Option 2 is a good thing to do regardless, so I'll do that now...

---

Re this:

> This does mean that, like assignment, an initializing `=` _expression-statement_ will have to be discarded.
> 
> ```
> s: std::string;
> _ = s = "";
> ```

I don't understand? Assignment does not have to be discarded, `s = "";` is fine.

I agree that whatever is done here, we should not require discarding the result of an `=` value-set statement, whether it's a definite first use or not. Having to discard an assignment would be weird. (And Option 2 above would actually ban writing that, which I think is an improvement.)

---

Re this:

> Returning an lvalue reference to the object parameter
> is only a convention in [user-provided](https://eel.is/c++draft/dcl.fct.def.default#def:user-provided) `operator=` (C++𝘕).
> That's the language's default,
> and what is expected of a [regular](https://eel.is/c++draft/concept.assignable#1.4) type.

I see that `std::assignable_from` has a _dynamic_ semantic requirement for that, but that wouldn't break _static_ uses of the concept for concept constraints/overloading?

**Comment by JohelEGP** [comment]
> Re this:
> 
> > This does mean that, like assignment, an initializing `=` _expression-statement_ will have to be discarded.
> > ```
> > s: std::string;
> > _ = s = "";
> > ```
> 
> I don't understand? Assignment does not have to be discarded, `s = "";` is fine.
> 
> I agree that whatever is done here, we should not require discarding the result of an `=` value-set statement, whether it's a definite first use or not. Having to discard an assignment would be weird. (And Option 2 above would actually ban writing that, which I think is an improvement.)

You're right.
I was actually thinking of compound assignment,
which do require discarding: <https://cpp2.godbolt.org/z/rGddsxGcK>.

**Comment by JohelEGP** [comment]
> I vaguely remember discussing that here in another issue(?) where I think someone came up with an example where `operator=` returning non-void was useful for something other than chaining, but I don't remember it now.

I remember <https://github.com/isocpp/CppCoreGuidelines/issues/1988>.
A quick look suggests that's your reference.

**Comment by hsutter** [comment]
> You're right.
> I was actually thinking of compound assignment,

Yes, my commit just now "fixes" that for `?=` too. 😎 So this is a consistency improvement where `=` and `?=` are now treated the same.

**Comment by hsutter** [comment]
> I remember [isocpp/CppCoreGuidelines#1988](https://github.com/isocpp/CppCoreGuidelines/issues/1988).
> A quick look suggests that's your reference.

That was it, thanks! Browsing that, the additional use case mentioned there was using the result as an lvalue, such as `while ((ch=getchar()) != EOF)`.

**Comment by hsutter** [comment]
Adding to the previous comment:

The specific use case of `while ((ch=getchar()) != EOF)` could not be a definite first use anyway, because it's in a loop.

So I think I've come down to that a definite first use initialization should be a whole statement, not a subexpression. **TODO:** I should create a diagnostic for that so that a violation gets a nice readable error message

**Comment by JohelEGP** [comment]
That's certainly consistent with definite first use initialization of data members in `operator=`.
