### ISSUE TITLE
[BUG] Compound assignment chosen over postfix operator

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#388]
**Title**: Compound assignment chosen over postfix operator

This seems at odds with
<https://github.com/hsutter/cppfront/wiki/Design-note:-Unambiguous-parsing>,
<https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-operators>, and
<https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-unary-operators-vs-binary-operators>.

**Minimal reproducer** (<https://godbolt.org/z/PYEnvh6Px>):
```Cpp2
f4: (inout v0: i8, copy v1: *i8) = {
  v0&*= 1;
}
main: () = {
  v0: i8 = 1;
  f4(v0, v0&);
}
```

**Commands**:
```bash
cppfront x.cpp2
clang++17 -std=c++2b -stdlib=libc++ -I $CPPFRONT_INCLUDE_DIR x.cpp
```

**Expected result**:
`*&v0 = 1` to be generated instead of
`&v0 *= 1`,
because `v0&*` can be parsed as a _postfix-expression_
because `v0&` can be parsed as a _postfix-expression_
because `v0` can be parsed as a _postfix-expression_
and those match first,
before `assignment-expression assignment-operator logical-or-expression`
has a chance to use `*=` as an _assignment-operator_,
and because the leftover `= 1` can match that `assignment-operator logical-or-expression`.

**Actual result and error**:

<details><summary>Generated Cpp1.</summary>

```C++
//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"



//=== Cpp2 type definitions and function declarations ===========================

#line 1 "/app/main.cpp2"
auto f4(cpp2::i8& v0, cpp2::i8* v1) -> void;
  

auto main() -> int;
  

//=== Cpp2 function definitions =================================================

#line 1 "/app/main.cpp2"
auto f4(cpp2::i8& v0, cpp2::i8* v1) -> void{
  &v0 *= 1;
}
auto main() -> int{
  cpp2::i8 v0 {1}; 
  f4(v0, &v0);
}
```

</details>

```output
main.cpp2:2:7: error: invalid operands to binary expression ('cpp2::i8 *' (aka 'signed char *') and 'int')
  &v0 *= 1;
  ~~~ ^  ~
1 error generated.
```

**Comment by hsutter** [comment]
Thanks. It's max munch... `*=` is one token.

Distilling even slightly further:

```
p: *i8 = f();
p*= 1;
```

That should clearly be compound assignment even without the whitespace, I think... what do you think?

**Comment by JohelEGP** [comment]
> It's max munch...

Thank you. I'll have to study this.

**Comment by hsutter** [comment]
I should distill even further:

```
i := 42;
i*= 1;
```

**Comment by JohelEGP** [comment]
> > It's max munch...
> 
> Thank you. I'll have to study this.

Maybe later. I remembered what should be the source of this parsing terminology. [Translation phase 3](https://eel.is/c++draft/lex#phases-1.3) tokenizes before [phase 7](https://eel.is/c++draft/lex#phases-1.7.sentence-3) reads the sequence according to the grammar.

**Comment by JohelEGP** [comment]
The max much rule must come from
> [(3.3)](https://eel.is/c++draft/lex#pptoken-3.3)
    Otherwise, the next preprocessing token is the longest sequence of characters that could constitute a preprocessing token, even if that would cause further lexical analysis to fail, except that a [header-name](https://eel.is/c++draft/lex#nt:header-name) ([[lex.header]](https://eel.is/c++draft/lex#header)) is only formed
        [(3.3.1)](https://eel.is/c++draft/lex#pptoken-3.3.1)
        after the include or import preprocessing token in an #include ([[cpp.include]](https://eel.is/c++draft/cpp.include)) or import ([[cpp.import]](https://eel.is/c++draft/cpp.import)) directive, or
        [(3.3.2)](https://eel.is/c++draft/lex#pptoken-3.3.2)
        within a [has-include-expression](https://eel.is/c++draft/cpp.cond#nt:has-include-expression)[.](https://eel.is/c++draft/lex#pptoken-3.3.sentence-1)
> 
> [Example [1](https://eel.is/c++draft/lex#pptoken-example-1): #define R "x"
const char* s = R"y";           // ill-formed raw string, not "x" "y"
— end example]

**Comment by JohelEGP** [comment]
Is it safe to say that https://eel.is/c++draft/lex#digraph doesn't apply to Cpp2, and `v0<:int = 0>` should lower to `v0<int{0}>` and not interpret the `<:` as a `[` (https://godbolt.org/z/oeKs3xad9)? If so, I think we can close this.

**Comment by hsutter** [comment]
Right, Cpp2 doesn't have [all the things on this cppreference page](https://en.cppreference.com/w/c/language/operator_alternative)... no digraphs or trigraphs as they aren't among the specified tokens, and no alternative operator macro names which were reclaimed for normal use in #328.
