### ISSUE TITLE
[BUG] Declaring a type named `struct` or `class`

### ISSUE THREAD

**Issue by msadeqhe** [hsutter/cppfront#394]
### Bug description

`struct` and `class` are not keywords in Cpp2, but I cannot declare a type named `struct` or `class`.

### To Reproduce It

This is the sample code:

```cpp
struct: type = {
    member: int = 0;
}
```

It should generate the following code:

```cpp
//=== Cpp2 type declarations ====================================================

#include "cpp2util.h"

class cpp2_struct;


//=== Cpp2 type definitions and function declarations ===========================

class cpp2_struct {
    private: int member {0}; 
    public: cpp2_struct() = default;
    public: cpp2_struct(cpp2_struct const&) = delete;
    public: auto operator=(cpp2_struct const&) -> void = delete;
};


//=== Cpp2 function definitions =================================================
```

But it leads to compilation faild:

```
example.cpp2(1,7): error: to define a type :, write ': : type = { /*body*/ }'

Compiler returned: 1
```

### Additional context

Also `typename`, `typedef`, `typeid` and other Cpp1-only keywords if used as type name will generate wrong source code.

I think it's related to [this issue](https://github.com/hsutter/cppfront/issues/328) that is fixed by applying prefix `cpp2_` to identifiers which are keywords in Cpp1.

**Comment by JohelEGP** [comment]
`and` works: <https://godbolt.org/z/7ddjd7boK>.
But not as a `@struct`: <https://godbolt.org/z/c6vv9zGxz>.
```output
main.cpp2:3:19: error: 'const' qualifier may not be applied to a reference
  public: and(and const& that);
                  ^
```
It was https://github.com/hsutter/cppfront/commit/1886ed25ae28e10b28660eb70e76bd3e5182b367#diff-e683e1259bbc0d6de7f1fbf797fb772f31a0a1ef2254ec317d15c298102fa3f3R1551-R1552 which made `struct` a reclaimed identifier.

**Comment by hsutter** [comment]
Thanks!

**Comment by JohelEGP** [comment]
<https://godbolt.org/z/c6vv9zGxz> still doesn't work.

**Comment by hsutter** [comment]
Ah, my bad -- fixed.

I had verified it was working, but then temporarily backed out a couple of the fixed places to debug some Cpp1 formatting artifacts, and forgot to re-enable them (including to re-run that test case) before commit. Should be good now with ddd62928799832ab8db028b90e158cdbcd7d72ca.
