### ISSUE TITLE
[BUG] Parameter named after contextual keyword is lost

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#397]
**Title**: Parameter named after contextual keyword is lost.

Such a Cpp2 parameter is lowered to Cpp1 as no parameter at all.

**Minimal reproducer** (<https://cpp2.godbolt.org/z/1exj84Wb4>):
```Cpp2
t: type = {
  f: (in) = { }
}
g: (final) = { }
// h: (out, x) = { } // Error!
main: () = { }
```

**Commands**:
```bash
cppfront -clean-cpp1 main.cpp2
clang++17 -std=c++2b -stdlib=libc++ -lc++abi -I . main.cpp
```

**Expected result**:
A diagnostic,
or the equivalent using `y` as an identifier.

**Actual result and error**:

```C++


#include "cpp2util.h"

class t;
  
class t {
  public: static auto f() -> void;

  public: t() = default;
  public: t(t const&) = delete;
  public: auto operator=(t const&) -> void = delete;
};
auto g() -> void;
// h: (out, x) = { } // Error!
auto main() -> int;

  auto t::f() -> void{}

auto g() -> void{}

auto main() -> int{}
```

**Comment by JohelEGP** [comment]
See also https://github.com/hsutter/cppfront/issues/387#parameter-declaration-list.
I believe `(in: T)` should be a function type with an `in` _parameter-direction_ parameter of type `T`.
That may be relevant in deciding the semantic meaning of `(final)` as a _parameter-declaration-list_.

**Comment by hsutter** [comment]
Thanks, this is a good example.

The linked PR #505 would allow this code:

```
t: type = {
  f: (in) -> _ = in;
}
g: (final) -> _ = final.first;
h: (out, x) -> _ = out(x);
```

I'm inclined to say that these should be interpreted as a missing parameter name, and should get a better diagnostic and be rejected at compile time.

I don't think I want to allow these. Are they ever necessary? They seem confusing (at least visually) and allowing them creates new things to teach and learn that would not be necessary if we disallowed parameters named the same as a parameter qualifier (passing style or virtual qualifier).

**Comment by JohelEGP** [comment]
That makes sense.
I wasn't sure before, but now I'm convinced.
I'll rebase #505 to diagnose as you mentioned.

**Comment by hsutter** [comment]
It's okay, I just made the change and am about to check it in. Thanks again!
