### ISSUE TITLE
[BUG] Can't call pointer-to-member

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#399]
The second comment is the new issue.

<details><summary>Resolved old issue</summary>

**Title**: Can't form pointer-to-member.

**Minimal reproducer** (<https://cpp2.godbolt.org/z/M8sTqsPvz>):
```Cpp2
t: type = {
  f: (this) = { }
}
main: () = {
  // Neither is valid syntax.
  t&::f;
  &t::f;
}
```

**Commands**:
```bash
cppfront -clean-cpp1 main.cpp2
```

**Expected result**:
Some way to form pointer-to-member.

**Actual result and error**:
```output
main.cpp2(4,12): error: ill-formed initializer (at '{')
main.cpp2(4,1): error: unexpected text at end of Cpp2 code section (at 'main')
main.cpp2(1,0): error: parse failed for section starting here
```

</details>

**Comment by zaucy** [comment]
I believe this should be the correct syntax (which does work!)

```cpp2
t::f&;
```

I was curious how to call a member function pointer in cpp2 and I couldn't figure it out without `std::invoke`. This works:

```cpp2
v : t = ();
f_ptr := t::f&;
std::invoke(f_ptr, v);
```

**Comment by JohelEGP** [comment]
Excellent! Thank you.

> I was curious how to call a member function pointer in cpp2 and I couldn't figure it out without `std::invoke`.

No wonder.

The Cpp1 syntax has to literally be
`v.*m` or `p->*m` for pointer to data members, and
`(v.*f)()` or `(p->*f)()` for pointer to member functions.

In Cpp2,
there's no arrow operator,
postfix `-` is an error,
`>` is interpreted as comparison and lowers to a function call, and
`*` is interpreted as indirection and lowers to a function call.

**Comment by realgdman** [comment]
I have tried `v.f_ptr*` but of course that emitted cpp1 `*(v.f_ptr)` (sans moves and nonnull asserts) and not `v.*f_ptr`
And `v.(f_ptr*)` doesnt make sense not in cpp1 nor cpp2, anyway `v.(f_ptr*)()` doesn't look pleasing.

**Comment by JohelEGP** [comment]
Cpp1 `v.*m`, `p->*m`, `(v.*f)()`, and `(p->*f)()` could be
Cpp2 `v.*m`, `p*.*m`, `v.*f()`, and `p*.*f()`, respectively,
by lowering `.*` to Cpp1 unchanged
and extending the grammar:
```diff
 //G member-name-specifier:
+//G     unqualified-id '.' '*'
 //G     unqualified-id '.'
```
`(v).*m` should also work:
```diff
 //G postfix-expression:
 //G     primary-expression
 //G     postfix-expression postfix-operator     [Note: without whitespace before the operator]
 //G     postfix-expression '[' expression-list ']'
 //G     postfix-expression '(' expression-list? ')'
+//G     postfix-expression '.' '*' id-expression
 //G     postfix-expression '.' id-expression
```

**Comment by jcanizales** [comment]
> And v.(f_ptr*) doesnt make sense not in cpp1 nor cpp2, anyway v.(f_ptr*)() doesn't look pleasing.

I would say this is the only one that makes sense and "looks like what it does"!

Calling the member function without dot syntax would be:

```swift
f(v)
```

If we had a pointer to the function instead, we'd have to do:

```swift
f_ptr*(v)
```

So its equivalent dot-syntax version is:

```swift
v.(f_ptr*)()
```

**Comment by hsutter** [comment]
Quick rationale: I intentionally didn't implement pointer to members, because I haven't seen the demand for it or seen it used much, so leaving it out would let us see whether there was actually a strong need.

Please reopen if there's data showing the feature is really needed. Thanks!

**Comment by jcanizales** [comment]
Within the last 6 months, using a pointer to member variable was key in reducing 8x duplication in one part of our codebase.

[GitHub search](https://github.com/search?q=%2F%5Ba-z%5D%5C.%5C*%5Ba-z%5D%2F+language%3AC%2B%2B&type=code&l=C%2B%2B) on its first page shows hits on C++ code from projects like Swift and Tensorflow.

(Btw whoever in the last few months made GitHub this good deserves a raise.)

**Comment by jcanizales** [comment]
Refined the search query to exclude forks: https://github.com/search?q=%2F%5Ba-z%5D%5C.%5C*%5Ba-z%5D%5B%5E%22%5D%2F+language%3AC%2B%2B+NOT+is%3Afork&type=code&l=C%2B%2B&p=1

Within the first three pages of results are additional projects of high pedigree: Chromium, V8, ProtocolBuffers, Clang, libfmt, Node, PyTorch, Abseil, GMock, and Ninja.
