### ISSUE TITLE
[BUG] ident.() crashing compiler with segfault

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#403]
**Minimal reproduction**
`f: () = {`
`	ident.();`
`}`

**Expected result**
Diagnostic, if that syntax doesn't have any meaning.

**Actual result**
Compiler crashed with segfault

**Additional info**
Basic debugging leads to this line
https://github.com/hsutter/cppfront/blob/768f1252fad9f4912b7c58c8073054c1e6b6401a/source/cppfront.cpp#L2895

As I understand, It is assuming this is UFCS call, and expecting func name to be there like `ident.foo()` but getting `null` because name is not provided.

**Comment by HALL9kv0** [comment]
Please check if you are using the latest version of cppfront.

In compiler explorer there is an error message : example.cpp2(3,10): error: '.' must be followed by a valid member name (at '(')
https://godbolt.org/z/GWbE4zKxc


```
fout: () = {
	  ident.();
  }    
main: () = {
  fin: () = {
	  ident.();
  }    
}
```

**Comment by realgdman** [comment]
You're right, this example doesn't crash now, something messed on my side, i'll try to recheck.
