### ISSUE TITLE
[BUG] Can't declare virtual destructor

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#412]
**Title**: Can't declare virtual destructor.

**Minimal reproducer** (<https://cpp2.godbolt.org/z/ad3e6ez8E>):
```Cpp2
base: type = {
  operator=: (virtual out this) = { }
}
main: () = { }
```

**Commands**:
```bash
cppfront -clean-cpp1 main.cpp2
```

**Expected result**:
A well-formed Cpp2 program.

**Actual result and error**:
```output
main.cpp2(2,3): error: a constructor may not be declared virtual, override, or final
```

**Comment by DyXel** [comment]
If you want to declare a destructor you use `move this` on `operator=`, no? Changing that in the example provided makes it generate what you would expect. cppfront believes here that you are trying to declare a constructor and as such, it errors out. (Maybe the diagnosis could be improved?)

**Comment by AbhinavK00** [comment]
Either the code example is wrong or the bug title is wrong. You are trying to declare a constructor not a destructor in the given example

**Comment by JohelEGP** [comment]
The comment above yours is correct.
I meant to declare a destructor,
but inadvertently declared a constructor.
So, I'm leaving it open in case an improvement in diagnostics is desirable.

**Comment by HALL9kv0** [comment]
I fixed the message locally.
File sema.h line 1125, I changed the message to:
                    "a constructor may not be declared virtual, override, or final. For declaring a virtual destructor, use 'move' instead i.e. operator=: (virtual move this)= {}"

```
  if ((*func->parameters)[0]->is_polymorphic()) {
                errors.emplace_back(
                    n.position(),
                    "a constructor may not be declared virtual, override, or final. For declaring a virtual destructor, use 'move' instead i.e. operator=: (virtual move this)= {}"
                );
                return false;
```

**Comment by JohelEGP** [comment]
I have convinced myself that the diagnostic wouldn't bring much value.
