### ISSUE TITLE
[BUG] Parameter direction for template parameter is ignored

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#425]
**Title**: Parameter direction for template parameter is ignored.

**Minimal reproducer** (<https://cpp2.godbolt.org/z/M1jxGdeqe>):

```Cpp2
a: <in T> type = { }
b: <in V: _> type = { }
main: () = { }
```

**Commands**:

```bash
cppfront -clean-cpp1 main.cpp2
clang++17 -std=c++2b -stdlib=libc++ -lc++abi -I . main.cpp
```

**Expected result**:

For the `: type` case, a diagnostic.
For the `: _` case, adherence to the specified parameter direction.

```C++
template<typename T> class a; // A Cpp2 diagnostic here.
template<const auto& V> class b;
```

**Actual result and error**:

```C++
template<typename T> class a;
template<auto V> class b;
```

```output
Program returned: 0
```

<details><summary>Cpp2 lowered to Cpp1.</summary>

```C++


#include "cpp2util.h"

template<typename T> class a;
template<auto V> class b;

template<typename T> class a {
      public: a() = default;
      public: a(a const&) = delete; /* No 'that' constructor, suppress copy */
      public: auto operator=(a const&) -> void = delete;

};
template<auto V> class b {
      public: b() = default;
      public: b(b const&) = delete; /* No 'that' constructor, suppress copy */
      public: auto operator=(b const&) -> void = delete;

};
auto main() -> int;

auto main() -> int{}
```

</details>

**Comment by realgdman** [comment]
Possibly related: I'm using library (flecs) with API like
```	
ecs.system<Position, const Velocity>()
    .each([] some lambda
```
And haven't found way to specify that `const` in template call to  system()
Which, I believe, cannot be deduced from parameters of lambda
```
	foo<int>();
	foo<const int>(); //error
	foo<int const>(); //error
	foo<in int>(); //error
```
https://cpp2.godbolt.org/z/sjMWTq3b7

**Comment by JohelEGP** [comment]
Seems like a bug: <https://cpp2.godbolt.org/z/Tx8e9KfKc>.
I suggest you open a new issue, since this one is about template parameters, not template arguments.

**Comment by realgdman** [comment]
Ok, I do later, what I mean by related is, should I be able to put `in` in <> in that case.

**Comment by JohelEGP** [comment]
I don't think that can work.
In a subexpression, a parameter direction operates on an expression, not a type.
`cppfront` doesn't have enough semantic information for `f<in int>()` to work.

**Comment by hsutter** [comment]
> Parameter direction for template parameter is ignored.

Yes, this is by design -- I don't know what it would mean.

I should probably emit a diagnostic for it though. Thanks!
