### ISSUE TITLE
[Wiki] Add related project Clang Format fork JohelEGP/llvm-project

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#429]
**Title**: Add related project Clang Format fork JohelEGP/llvm-project.

```md
- <https://github.com/JohelEGP/llvm-project/wiki/Format-Cpp2>. A Clang Format fork with support for Cpp2 syntax.
```

**Comment by hsutter** [comment]
Nice, thank you @JohelEGP! Added to the wiki.

Also, since this just missed being included the update I blogged a few days ago, I've added a slide to mention it in my talk tomorrow.

**Comment by hsutter** [comment]
Wow, that's a lot of tests. Now I see where some of your bug reports came from... thank you everyone, please keep telling me what's not working. I'm distracted with C++Now right now but I hope to start catching up on them again next weekend...

**Comment by JohelEGP** [comment]
Thank you very much for the acknowledgements.
I'm looking forward to watching your C++Now 2023 talk on Cpp2.

**Comment by JohelEGP** [comment]
"Keynote: The Evolution of C++ - A Typescript for C++ - Herb Sutter - CppNow 2023"
[![Keynote: The Evolution of C++ - A Typescript for C++ - Herb Sutter - CppNow 2023](https://img.youtube.com/vi/fJvPBHErF2U/0.jpg)](https://www.youtube.com/watch?v=fJvPBHErF2U)
Premieres in 43 hours
August 11 at 14:00 UTC
