### ISSUE TITLE
[BUG] Function expression can't be the left argument to `is`/`as`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#435]
**Title**: Function expression can't be the left argument to `is`/`as`.

**Minimal reproducer** (<https://cpp2.godbolt.org/z/K53erj1fh>):

```Cpp2
main: () = {
  :() = 0; is int;
}
```

**Commands**:

```bash
cppfront -clean-cpp1 main.cpp2
```

**Expected result**:

Same as (<https://cpp2.godbolt.org/z/8nszP1Wo4>):
```Cpp2
main: () = {
  cp := :(x) -> _ = x;
  cp(:() = 0) is int;
}
```

**Actual result and error**:

```output
main.cpp2(1,12): error: ill-formed initializer (at '{')
main.cpp2(1,1): error: unexpected text at end of Cpp2 code section (at 'main')
main.cpp2(1,0): error: parse failed for section starting here
```

**Comment by msadeqhe** [comment]
I think your example code is wrong, because:

- If the return type of an unnamed function is omitted, it will be `void`.
- Use parenthesis instead of `;`, otherwise the statement will be ended before `is`.

This is the correct example code:

```cpp
main: () = {
    x: = (: () -> int = 0) is int; \\ true
}
```

**Comment by filipsajdak** [comment]
I have a fix for that. @JohelEGP found an actual bug.

At the same time, I agree with you, @msadeqhe, that this code should rise an error as it discards the result of the `is` expression.

**Comment by filipsajdak** [comment]
Just in case you would like to test the fix by yourself, or if I am not able to deliver fast, I am attaching a diff:
```diff
diff --git a/source/parse.h b/source/parse.h
index f716925..65d2fb0 100644
--- a/source/parse.h
+++ b/source/parse.h
@@ -3606,6 +3606,10 @@ private:
                     && curr().type() != lexeme::LeftParen               // not imediatelly called
                     && curr().type() != lexeme::RightParen              // not as a last argument to function
                     && curr().type() != lexeme::Comma                   // not as first or in-the-middle, function argument
+                    && curr() != "is"
+                    && curr() != "as"
+                    && curr() != "do"
+                    && curr() != "next"
                 ) {
                     // this is a fix for a short function syntax that should have double semicolon used
                     // (check comment in expression_statement(bool semicolon_required))
```

**Comment by JohelEGP** [comment]
> If the return type of an unnamed function is omitted, it will be `void`.

It's still valid code. Not practically useful, but slide-ware/example-ware useful. Like for reporting bugs.

> Use parenthesis instead of `;`, otherwise the statement will be ended before `is`.

I think this should work to disambiguate when you want the `is` outside the function expression's statement.
Seems like a natural fit, considering the other cases you can add `;`.
So I think it's a bug that it doesn't work.

> I need to correct my build system to handle self-compilation by the previous version of cppfront. I will deliver the patch soon.

I didn't notice because the generated Cpp1 source files are checked in.
I just launched my usual command to compile `cppfront` and it worked.

**Comment by filipsajdak** [comment]
The original code is not working, but the following is:
```cpp
main: () = {
  (:() = 0;) is int;
}
```
