### ISSUE TITLE
[BUG] `for` loop don't allow several assignments in `next`

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#448]
`for` loop (and other loops) don't accept several assignments inside `next`

**Reproduce Code**
https://cpp2.godbolt.org/z/aqYqr63z5

```
main: () = {
	(copy a := 0, copy b := 0)
	//for "abc" next a++ do (i) { //ok
	for "abc" next { a++; b++; } do (i) { //error
	//for "abc' next a do (i) { //unused a
		std::cout << i << a << b << '\n';
	}
}
```

**Version**
latest (38aec57)

**Command lines**
cppfront/cppfront $1.cpp2 -p
clang++-15 -Icppfront/include $1.cpp -std=c++20 -o $1

**Expected result**
Some block syntax for that assignment or diagnostic

**Actual result**
Compilation error

**Additional notes**
In grammar only single expr allowed
//G next-clause:
//G     'next' assignment-expression

Additionally, _logical-or-expression_ could be logical.
Which can lead to compiled, but unused logical expression
`for "abc' next a do (i) { //unused a`

**Comment by realgdman** [comment]
Temporary workaround was found
```
main: () = {
	a:=0; b:=0;
	l := :() = { a&$*++; b&$*++;  };
	for "abc" next l() do (c) {
		std::cout << c << a << b << '\n';
	}
}
```
Thanks for idea from here, https://github.com/hsutter/cppfront/issues/432 currently lambda cannot be declared inside `next`

**Comment by msadeqhe** [comment]
The example should be written like this:

```cpp
main: () = {
	(copy a: = 0, copy b: = 0)
	for "abc" next (a++, b++) do (i) {
		std::cout << i << a << b << '\n';
	}
}
```

Cpp2 generates this:

```cpp
auto main() -> int{
{
auto a = 0;
auto b = 0;

 { auto const& cpp2_range = "abc"; for ( auto const& i : cpp2_range )  { do {
  std::cout << i << a << b << '\n';
 } while (false); (++a, ++b); }}
}
}
```

**Comment by realgdman** [comment]
Well I should have guessed. Even this works.
for "abc" next ( a++, b++, std::cout << a, foo()) do (c)

**Comment by JohelEGP** [comment]
See <https://github.com/hsutter/cppfront/issues/449#issuecomment-1544031412>. It may work by accident.
