### ISSUE TITLE
[BUG] Cannot specity `<const>` or `<in>`  in function template arguments

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#456]
I'm using library (flecs) with API like

ecs.system<Position, const Velocity>()
    .each([] some lambda

And haven't found way to specify that `const` in template call to system()
Which, I believe, cannot be deduced from parameters of lambda

	foo<int>();
	foo<const int>(); //error
	foo<int const>(); //error
	foo<in int>(); //error

https://cpp2.godbolt.org/z/sjMWTq3b7

But according to this comment https://github.com/hsutter/cppfront/issues/425#issuecomment-1546751644 , it works on pointers
https://cpp2.godbolt.org/z/Tx8e9KfKc
`	f<* const int>();`

**Comment by JohelEGP** [comment]
I think it may be a bug in the parser.
For `f<const int>()`,
it's supposed to parse an expression or type-id before a `,` or `>`:
```C++
//G template-argument-list:
//G     template-argument-list ',' template-argument
//G
//G template-argument:
//G     # note: < > << >> are not allowed in expressions until new ( is opened
//G     expression
//G     type-id
```
Or maybe it parses `const` as an identifier and calls it a day, expression completed.
Just to find that it's not followed by `,` or `>`, and fails.

**Comment by AbhinavK00** [comment]
> All common templates need to be written f<inout A, inout B>()

I don't think so, as [#425(comment)](https://github.com/hsutter/cppfront/issues/425#issuecomment-1546760953) points out, a parameter direction does NOT operate on a type. And when you think about it,
```
F<out T>
F<move T>
```
do not make sense. So we need not to change the types in templates to <inout T> atleast.
There are two ways after this, either dont allow parameter passing directives on non-type template parameters and call it a day OR think about how all of this should work and allow parameter passing directives on non-type template parameters.

**Comment by realgdman** [comment]
OK I got where my misunderstanding about `<in>` coming from.
What I learned about project, it was about
`foo(in x);` and `(inout i:=0) { ... }` not allowing `const`.
But apparently you can write
```
i: const int = 0;
T: type = { j: const int = 0; }
```
That means some places use new syntax, some old, and thus `<const T>` should be accepted.

Hence I found workaround for my issue
```
i: int = 0;
ci: const int = 0;
foo<decltype(i)>();
foo<decltype(ci)>();
foo<decltype(ci)>(); //careful with last use - std::move(decltype(ci)) remove const
```
print nonconst, const, nonconst.
https://cpp2.godbolt.org/z/8E8MxjnKd

Regarding `<in T>`, this can be chalked from issue, and thought as discussion of further unifying syntax.

**Comment by AbhinavK00** [comment]
I also learnt the same thing from this issue, I had fully forgotten about `const` being in cpp2 lol.

**Comment by JohelEGP** [comment]
`const` is definitely being parsed as an expression.
See how `const * i32` this isn't transformed like in a type-only context: <https://cpp2.godbolt.org/z/46KezxeY6>.
```Cpp2
main: () = {
  x: const * int = g;
  v<const * int>;
}
```
```C++
auto main() -> int{
  int* const x {g};
  v<const * int>;
}
```

---

One way to fix this is to introduce alternative grammars that are definitely not something else.
After applying <https://github.com/hsutter/cppfront/issues/387#parameter-declaration-list>:
```diff
+//G unqualified-type-id:
+//G     id-expression
+//G     function-type

+//G definite-type-id:
+//G     type-qualifier-seq unqualified-type-id

 //G type-id:
-//G     type-qualifier-seq? id-expression
-//G     type-qualifier-seq? function-type
+//G     type-qualifier-seq? unqualified-type-id

 //G template-argument:
 //G     # note: < > << >> are not allowed in expressions until new ( is opened
+//G     definite-type-id
 //G     expression
 //G     type-id

 //G parameter-declaration:
 //G     parameter-direction? unnamed-declaration
 //G     this-specifier? parameter-direction? declaration
 //G     this-specifier? parameter-direction? identifier

 //G return-list:
 //G     '->' type-id
```

And similarly for <https://github.com/hsutter/cppfront/issues/387#issuecomment-1534970681>:
```diff
+//G identifier-list:
+//G     identifier
+//G     identifier-list ',' identifier

+//G inconclusive-type-id:
+//G     '(' identifier-list ')'

 //G is-as-expression:
 //G     prefix-expression
+//G     is-as-expression is-definite-value-constraint
 //G     is-as-expression is-type-constraint
 //G     is-as-expression is-value-constraint
 //G     is-as-expression as-type-cast
 //GTODO     type-id is-type-constraint

+//G is-definite-value-constraint
+//G     'is' inconclusive-type-id
```

**Comment by JohelEGP** [comment]
The suggested complication above
is to make `f<const i32>()` work
while keeping the grammar context-free.

The alternatives I've considered are (assuming no function type support):
- `i32 as const` to work and cast `i32` to `const` (inconsistent).
- `const type-id` to be an expression
  that is semantically required to occur in a context
  where _type-id_ is an alternative production.

**Comment by JohelEGP** [comment]
Here's a simpler alternative, with support for function types.

Proposal [_parameter-declaration-list_][] achieves feature parity with Cpp1.
It makes the name of a parameter optional in a declaration or type.

The alternative maintains the status-quo: Parameters of a declaration can't be unnamed.
Introduce the converse for types: A _function-type-id_ whose parameters must be unnamed.

First, define _function-type-id_:
```diff
 //G type-id:
 //G     type-qualifier-seq? id-expression
+//G     type-qualifier-seq? function-type-id

 //G parameter-declaration:
 //G     this-specifier? parameter-direction? declaration
 //G     this-specifier? parameter-direction? identifier
+//G parameter-declaration-type:
+//G     parameter-direction? unnamed-declaration

 //G parameter-declaration-list
 //G     '(' parameter-declaration-seq? ')'
+//G parameter-declaration-type-list
+//G     '(' parameter-declaration-type-seq? ')'

 //G parameter-declaration-seq:
 //G     parameter-declaration
 //G     parameter-declaration-seq ',' parameter-declaration
+//G parameter-declaration-type-seq:
+//G     parameter-declaration-type
+//G     parameter-declaration-type-seq ',' parameter-declaration-type

 //G function-type:
 //G     parameter-declaration-list throws-specifier? return-list? contract-seq?
+//G function-type-id:
+//G     parameter-declaration-type-list throws-specifier? return-list?
```

Then, to fix this issue (#456), update _template-argument_:
```diff
 //G template-argument:
 //G     # note: < > << >> are not allowed in expressions until new ( is opened
+//G     'const' type-id
+//G     function-type-id
 //G     expression
 //G     type-id
```

With that:
```Cpp2
v<const int, // Type.
  (:int), // Function type.
  ((:int=0))>; // Value `0`.
```

And to workaround <https://github.com/hsutter/cppfront/issues/387#issuecomment-1534970681>:
```Cpp2
x is (x); // Same as today.
x is (:int); // Asks if "`x` has type `(:int)`".
x is ((:int=0)); // Asks if "`x` is `0`".
```

[_parameter-declaration-list_]: https://github.com/hsutter/cppfront/issues/387#parameter-declaration-list

**Comment by JohelEGP** [comment]
Or maybe just add _function-type-id_ as a synonym for _function-type_,
and require during semantic analysis that its parameters match `parameter-direction? unnamed-declaration`.

```diff
 //G type-id:
 //G     type-qualifier-seq? id-expression
+//G     type-qualifier-seq? function-type-id

 //G function-type:
 //G     parameter-declaration-list throws-specifier? return-list? contract-seq?
+//G function-type-id:
+//G     # Note: Parameters must match `parameter-direction? unnamed-declaration`.
+//G     function-type

 //G template-argument:
 //G     # note: < > << >> are not allowed in expressions until new ( is opened
+//G     'const' type-id
+//G     function-type-id
 //G     expression
 //G     type-id
```

**Comment by JohelEGP** [comment]
Assuming that `in` should be a valid parameter name (see #397),
the simplification above means that the meaning of `(in)` and `(in: _)`
changes depending on whether it's a _function-type_ or _function-type-id_,
where in the former it's a parameter name, and in the latter a _parameter-direction_.

**Comment by JohelEGP** [comment]
For <https://github.com/hsutter/cppfront/issues/492#issuecomment-1599710087>, I wrote
```Cpp2
operator_is: <T, F> (v: T, f: F) -> bool requires std::predicate<decltype((f)), decltype((v))> = { return std::invoke(f, v); }
```
I take advantage of `decltype((x))` to form a type that is an lvalue reference to the type of `x`.

[We've already mentioned](https://github.com/hsutter/cppfront/issues/456#issuecomment-1547273369)
that `in T` can't work, because the parameter directions work on expressions.

But wanting to specify reference types for template arguments
made me think it'd be convenient to specify them just like a parameter declaration.
Based on the first illustration at <https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-operators>,
a function type will probably look like `(:i32) -> * (:i32) -> std::string`
(See <https://github.com/hsutter/cppfront/issues/387#parameter-declaration-list> for some proposals).
So the idea is to be able to specify type template arguments using the same parameter declaration syntax.
Re-specifying the `operator_is` above:
```Cpp2
operator_is: <T, F> (v: T, f: F) -> bool requires std::predicate<in: T, in: F> = { return std::invoke(f, v); }
```

**Comment by JohelEGP** [comment]
Although `:` is supposed to introduce names, so that doesn't work quite well.

**Comment by MaxSagebaum** [comment]
I think in one talk Herb metioned also, that he would like to introduce specifications on the calling side like
```
f: (out o: int, in i: int) -> void;
a: int = 1;
b: int = 2;
f(out a, in b);
```

If this is introduced, then it would only be logical that template parameters could also be specified in with these modifiers without using `:`.
