### ISSUE TITLE
[SUGGESTION] `if (i==j)` gives clang warning about (i==j)

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#457]
`if (i==j)` in cpp2, when lowered to cpp1, encloses condition in parens  `if ((i==j))`
Which is, probably, for good, but in modern C++, for example clang, gives a warning

https://cpp2.godbolt.org/z/av3ech559

>warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
>note: remove extraneous parentheses around the comparison to silence this warning
>note: use '=' to turn this equality comparison into an assignment

It can be a problem if "threat warnings as error" enabled, in case of mixed cpp1/cpp2.

**Comment by JohelEGP** [comment]
It's not extra. It's the same you write.
`if a` is Cpp2, and _has_ to lower to Cpp1 `if (a)`.
