### ISSUE TITLE
[BUG] Local class (inside function) doesn't emit declaration

### ISSUE THREAD

**Issue by realgdman** [hsutter/cppfront#458]
Local class (declared inside function) doesn't emit cpp1 declaration.

Class is checked for errors, does emit method definitions, but missing class and member declarations.

**Reproduce Code**
```
main: () = {
  T: type = { public i: int; }	
  t:=T();
  S: type = { foo: (this) = {} }
  s: S = ();
}
```
https://cpp2.godbolt.org/z/aoMoj7hnY

**Version**
latest (ebe5ebc)

**Command lines**
cppfront/cppfront $1.cpp2 -p
clang++-16 -Icppfront/include $1.cpp -std=c++20 -o $1

**Expected result**
Lowered to cpp1 and compiled local class like:
https://cpp.godbolt.org/z/dPbhv53b3

**Actual result**
Passes cpp2 checks, emits method definition, but no class declaration
Leading to cpp1 error: use of undeclared identifier 'T', 'S'

<details>
  <summary>Lowered cpp1</summary>

```  
//=== Cpp2 function definitions =================================================

#line 1 "innerclass.cpp2"
auto main() -> int{

 auto t {T()}; 
 auto S::foo() const -> void{}
 S s {}; 
}
```
</details>

**Comment by realgdman** [comment]
It appears that emitting method definition is issue too.
I think it's not legal in cpp1 to split local class into declaration and definition.
```
int main() {
  class T { public: int foo(); };
  int T::foo() { return 42 }; //cpp1 error
}
```

**Comment by JohelEGP** [comment]
Given https://github.com/hsutter/cppfront/commit/379ae0311f177ea42517cb07520c4f804f4396b6#diff-09d210b8aa3d8090c8877ce7afc954f7e8affd2de2e0546bf0edbb7a9f7ba98eR1099,
this would error with:
```output
(temporary alpha limitation) a type must be in a namespace or type scope - function-local types are not yet supported
```

**Comment by hsutter** [comment]
Thanks! Correct, I plan to make this work but it's a little more work (mainly to emit function bodies in-line instead of out-of-line) and lower on the priority list, so I'll close this for now as resolved by the new warning.
