### ISSUE TITLE
[BUG] Escaping `'"'` in string in interpolation fails assertion

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#461]
<a id="title"/>

**[Title](#title)**: Escaping `'"'` in string in interpolation fails assertion.

<a id="rep"/>
<a id="cpp2"/>

**[Minimal reproducer](#rep)** (<https://cpp2.godbolt.org/z/vYsh34z5K>):

```Cpp2
main: () = {
  std::cout << "\"\"" << '\n'; // Prints `""`.
  std::cout << $R"("")" << '\n'; // Prints `""`.
  std::cout << "\"(\"\")$\"" << '\n'; // Prints `""`.
  std::cout << "(\"\\\"\\\"\")$" << '\n'; // cppfront asserts.
}
```

<a id="cmd"/>

<details><summary><b><a href="#cmd">Commands</a></b>:</summary>

```bash
cppfront -clean-cpp1 main.cpp2
```

</details>

<a id="expected"/>

**[Expected result](#expected)**:

A diagnostic, or to print `""` like the other lines.

<a id="actual"/>

**[Actual result and error](#actual)**:

```output
cppfront: source/lex.h:437: std::string cpp2::expand_string_literal(std::string_view, std::vector<error_entry>&, source_position): Assertion `pos == length-1 && text[pos] == '"'' failed.
```

**Comment by hsutter** [comment]
@filipsajdak I think you looked at this last -- can you take a look at this?

**Comment by filipsajdak** [comment]
I am on it.
