### ISSUE TITLE
[BUG] Non-empty line after one-liner type with requires clause fails assertion

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#472]
<a id="title"/>

**[T](#title)itle**: Non-empty line after one-liner type with requires clause fails assertion.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/bfh5bfTj4>):

```Cpp2
t: type requires true = { }
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront -clean-cpp1 main.cpp2
```
</details>

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a href="#out">O</a>utput.

```output
cppfront: source/cppfront.cpp:523: void cpp2::positional_printer::align_to(cpp2::source_position): Assertion `psource && 0 <= curr_pos.lineno && curr_pos.lineno < std::ssize(psource->get_lines())+1' failed.
```

**Comment by filipsajdak** [comment]
I have an easy fix for the assertion:
```diff
diff --git a/source/cppfront.cpp b/source/cppfront.cpp
index 5b89964..44cc52e 100644
--- a/source/cppfront.cpp
+++ b/source/cppfront.cpp
@@ -5094,7 +5094,7 @@ public:
                 if (n.requires_clause_expression) {
                     printer.print_cpp2("requires( ", n.requires_pos);
                     emit(*n.requires_clause_expression);
-                    printer.print_cpp2(" )\n\n", n.requires_pos);
+                    printer.print_cpp2(" )\n", n.requires_pos);
                 }
 
                 printer.print_cpp2("class ", n.position());
```

But even without the parsing error, the result cpp1 code is not good (check here: https://cpp2.godbolt.org/z/eGMMz8Txj)
```cpp
#include "cpp2util.h"

requires( true )

class t;
requires( true )

class t {
      public: t() = default;
      public: t(t const&) = delete; /* No 'that' constructor, suppress copy */
      public: auto operator=(t const&) -> void = delete;

};

auto main() -> int;

auto main() -> int{}
```
error:
```
build/_cppfront/main.cpp:5:1: error: expected unqualified-id before 'requires'
    5 | requires( true )
      | ^~~~~~~~
build/_cppfront/main.cpp:8:1: error: expected unqualified-id before 'requires'
    8 | requires( true )
      | ^~~~~~~~
make[2]: *** [CMakeFiles/test.dir/build.make:81: CMakeFiles/test.dir/_cppfront/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
```

**Comment by JohelEGP** [comment]
Hmmm... yes.
It's because `t` isn't a templated entity.
Just add a _template-head_ to it.
Thank you for looking into this!

**Comment by filipsajdak** [comment]
The most probably requires clause for non-templates should be a cpp2 parsing error.

**Comment by JohelEGP** [comment]
That's actually a Cpp1 semantic rule
that _could_ be elevated to a Cpp2 parser error,
but so could many other Cpp1 semantic rules.

**Comment by hsutter** [comment]
I think I'd prefer leaving the semantic rule enforced by the Cpp1 compiler, as long as it's reasonably readable and points to the right Cpp2 line number.

**Comment by hsutter** [comment]
Re elevating the Cpp1 semantic rule to Cpp2, repeating rationale from #528 for visibility:

I do think there's value in diagnosing a `requires` on a non-templated type for _type_ declarations.

Rationale:
- writing a stray `requires` on a function already gives a nice Cpp1 diagnostic (e.g., MSVC says `error C7599: 't::f': a trailing requires clause is only allowed on a templated function`)
- writing a stray `requires` on a type currently lowers it to a naked `requires` at global scope before the type which leads to a harder-to-understand Cpp1 diagnostic (e.g., MSVC says `error C2059: syntax error: 'requires'`, which is correct and indicates the rough issue, but it's not as specific)

So diagnosing the type case in Cpp2 delivers the primary diagnostic usability improvement.
