### ISSUE TITLE
[SUGGESTION] Add a -o flag to specify the output file

### ISSUE THREAD

**Issue by jpakkane** [hsutter/cppfront#48]
Currently `cppfront` seems to write its output `.cpp` file next to the input `.cpp2` file. This makes it difficult to integrate with setups that have separate build and source directories. Please add a `-o` command line argument so the output path can be specified from the outside.

**Comment by hsutter** [comment]
OK, I've taken a first pass at it in the above commit... I'll close the issue but just comment/reopen here if it doesn't do what you need.

**Comment by jpakkane** [comment]
[Works just fine](https://nibblestew.blogspot.com/2022/10/using-cppfront-with-meson.html). Thanks.

**Comment by hsutter** [comment]
Great, added to the wiki home page: https://github.com/hsutter/cppfront/wiki.
Thanks, Jussi!
