### ISSUE TITLE
[SUGGESTION] Linear Scan Template Syntax (no chevrons / angle brackets)

### ISSUE THREAD

**Issue by Cons-Cat** [hsutter/cppfront#494]
This is a suggestion for toolability enhancement. Apologies if this has been discussed before, but I couldn't find an issue about it.

At my day job, I've written something like an extremely simplified version of [libassert](https://github.com/jeremy-rifkin/libassert). To decompose N-number of operands from a C++ expression like `foo + moo == zoo` (turned into a string using `#`), I parse the expression's text using a linear scan rather than a recursive descent. There is no value in recursive descent here, because I cannot decompose the operands within bracket-pairs like `()` or `{}` anyways using this technique. `(foo + moo) == zoo` must be decomposed as `(foo + moo)` and `zoo`.

However, chevrons present a major challenge for this tool. If the expression is `foo<int> < moo == zoo`, this is very difficult to parse in my dumb-style. I have to do lookaheads to determine if pairs match, and then there are still hard edge-cases like `foo<0 > 1> < moo == zoo<1 > 2>`.

Parsing comparison expressions within templates used to cause the Emacs C++ highlighter to malfunction until clangd [added semantic tokens](https://github.com/llvm/llvm-project/commit/bbddbe580bca5fa1c0478a3ec6edd0e0c40b9d96) _just for template rainbow brackets_. Text editors evidently cannot highlight angle brackets properly without something like LSP or tree-sitter. I consider this all evidence that the angle-brackets template syntax is not very toolable.

One of D's most obvious deviations from C++ is the use of `!` for parsing templates rather the angle brackets, and Circle recently [introduced a compromise](https://github.com/seanbaxter/circle/blob/master/new-circle/README.md#template_brackets) between the two syntax, which would partially solve my linear scan parser. I think I would still need a lookahead, but at least the lookahead wouldn't be very complex.

The V language recent-ish-ly switched from using angle-brackets for its generics to square-brackets like Go, to simplify parsing. Although I'm not sure that square-brackets would be possible for this in C++, due to `static operator[]`. Maybe a nested `my_type[[int]]` syntax would work, although it looks like an attribute.

I don't have any specific suggestions for a syntax, but something that makes this kind of expression decomposer easier to write would be useful, in my opinion.

**Comment by JohelEGP** [comment]
Have you read <https://github.com/hsutter/cppfront/wiki/Design-note%3A-Unambiguous-parsing>?

**Comment by Cons-Cat** [comment]
> Have you read <https://github.com/hsutter/cppfront/wiki/Design-note%3A-Unambiguous-parsing>?
> 

No, I somehow missed that. That would solve my problem as far as I'm concerned, thanks!
