### ISSUE TITLE
[BUG]  Undeclared variables not caught

### ISSUE THREAD

**Issue by TobiSchluter** [hsutter/cppfront#498]
There appear to be no checks whether variables are actually declared, e.g.
```
main: (args) -> int = {
    i : int = j;
    j : int = k;
    m : int;
    m = n;
    return i;
}
```
This compiles to C++, producing invalid C++. https://godbolt.org/z/fzWqheWvn

This is obviously hard to get right in a preprocessor when global symbols could be everywhere, but it seems dangerously simple to produce invalid code without these checks.

I'm sorry if this was reported before, I think it deserves at least an FAQ mention.

**Comment by JohelEGP** [comment]
Compile-time errors are good.
I don't think there's anything of value for cppfront or Cpp2 to add here.

**Comment by hsutter** [comment]
Thanks! Yes, the intent was for this kind of error to be reported in the Cpp1 compiler.
