### ISSUE TITLE
[BUG] Pointer type not parsed as template argument

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#502]
<a id="title"/>

**[T](#title)itle**: Pointer type not parsed as template argument.

<a id="desc"/>

**[D](#desc)escription**:

See <https://github.com/hsutter/cppfront/issues/456#issuecomment-1546984283>.
It's valid grammar.
I guess the error is being emitted
while parsing the expression production
without regard for the context.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/rWYevT9h7>):

```Cpp2
main: () = std::is_void_v<* i32>;
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront -clean-cpp1 main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**:

```output
Program returned: 0
```

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a id="out"/>
<a href="#out">O</a>utput:

```output
main.cpp2(1,27): error: prefix '*ptr' dereference is not valid Cpp2; use postfix 'ptr*' instead
```

**Comment by MaxSagebaum** [comment]
This is also true for `const` modifier:
```
main: () = std::is_void_v< const i32>;
```

cppfront output is:
```
emp.cpp2...
temp.cpp2(1,34): error: ill-formed initializer (at 'i32')
temp.cpp2(1,1): error: unexpected text at end of Cpp2 code section (at 'main')
temp.cpp2(1,0): error: parse failed for section starting here
```

I tried to have a look at the parsing. Either the template parse needs to be elevated before the binary < operator or this error needs to be non fatal.

**Comment by JohelEGP** [comment]
That's the point of the linked issue in the description.

**Comment by MaxSagebaum** [comment]
Sorry missed that.
