### ISSUE TITLE
[BUG] `token` stores `start, count` instead of `string_view` to save space, but padding gets in the way

### ISSUE THREAD

**Issue by PoetaKodu** [hsutter/cppfront#517]
**Describe the bug**

I came across this comment:
https://github.com/hsutter/cppfront/blob/main/source/lex.h#L312

The problem is that because of padding, the structure takes up the same amount of space as if it
contained `string_view` instead.

Another problem is that in theory user could input a string literal token that is over 2^16 characters long.

**Comment by JohelEGP** [comment]
> Another problem is that in theory user could input a string literal token that is over 2^16 characters long.

The current implementation uses `int16_t`,
which means the max is $2^{15}-1$,
as opposed to the minimum of $2^{16}$
required at <https://eel.is/c++draft/implimits#2.16.sentence-1>.
