### ISSUE TITLE
[SUGGESTION] Why is mixing allowed?

### ISSUE THREAD

**Issue by crim4** [hsutter/cppfront#520]
Why is mixing cpp1 and cpp2 in the same file allowed?
In my opinion, this can lead to several problems:
* Poor parser design: the parser just skips all the tokens until it matches the tokens pattern `<id><colon>`, this results in ugly code generations with typos or something...
* Bloated syntax highlighting extensions: now you need an syntax highlighting extension for you editor which supports both the languages' syntaxes in a single file ... (and we all know that cpp syntax is annoying to highlight correctly in editors, add now that the extension needs to highlight another completely different syntax)
* Confusional source code: now your cpp2 source code may look ugly because you can just alternate cpp1 syntax constructs and cpp2 ones, this makes no sense and actually creates a lot of ugly results (at least, this is no longer simple)

I'm not saying to completely remove the mixing, but maybe make it legal only inside a `inline_cpp1 { ... }` block

**Comment by JohelEGP** [comment]
> Why is mixing cpp1 and cpp2 in the same file allowed?

It's in the README.
See <https://github.com/hsutter/cppfront#whats-different-about-this-experiment>.
I also recommend watching <https://github.com/hsutter/cppfront#2020-bridge-to-newthingia>.

**Comment by JohelEGP** [comment]
> I still don't see how having multiple, completely different, languages in the same file helps getting 10x simpler c++?

It doesn't.
Read again.
It says that you only get 10x simpler if you write purely Cpp2.

**Comment by crim4** [comment]
Nice, so we have the same idea, don't we? Then, what's the point of allowing implicit mixing of cpp1 and cpp2, and not just add a `inline_cpp1 {}` or `emit_cpp1 {}` or just `cpp1 {}`, well you understood what i mean

**Comment by SebastianTroy** [comment]
It's so you can start writing cpp2 in a pre existing cpp1 file without changing any of the cpp1. The idea is to make minimal friction for adoption. 1 file is fine, a hundred files? Should you have to wrap all of them in inlibe::cpp1 scopes? What if you add cpp2 in the middle, then you have to end the previous scope and start a new one after, just annoying.


On 20 June 2023 17:48:18 crim ***@***.***> wrote:

Nice, so we have the same idea, don't we? Then, what's the point of allowing implicit mixing of cpp1 and cpp2, and not just add a inline_cpp1 {} or emit_cpp1 {} or just cpp1 {}, well you understood what i mean

**Comment by crim4** [comment]
update: I just saw this now
![image](https://github.com/hsutter/cppfront/assets/108405263/274debe5-dd9e-433c-82e0-060c91706548)

**Comment by realgdman** [comment]
Mixing is useful during transitional period, for example when you need declare something with templates, which is not always possible in pure cpp2 yet.
