### ISSUE TITLE
Possible oversight with postfix "type" keyword?

### ISSUE THREAD

**Issue by switch-blade-stuff** [hsutter/cppfront#53]
I have a bit of a concern about the postfix `type` and `namespace` keywords, both about consistency and implementation caveats.

The main gist of my concern is that with postfix `type` keyword, a type's parents cannot be defined as they are in syntax 1, as column is being used for the keyword.

Of course it can be done via Java-style `extends` (or similar) keyword. Or via a second column after the `type`. But that just seems like introducing visual noise into the syntax for the sake of having a postfix keyword.

Another concern is how would template declarations and concept requirements work, would the template/requires keywords also come after the column like this?
```my_type : template<typename T> requires (X) type```
or like this
```my_type : type template<typename T> requires (X)```
This, at least to me, seems a bit noisy as well.

And finally - consistency: this way there will be prefix keywords (i.e. `if`, `for`, etc.), postfix keywords without a column (ex. `noexcept`) and postfix keywords with a column (`type`). This, again, seems to me like additional syntactical noise for the sake of "using the shiny postfix".

Are there any valid reasons for the postfix **keywords** for types/namespaces that i just dont see? How would inheritance, templates, etc. work with the postfix keywords?

**Comment by hsutter** [comment]
Good points, and I think most of your questions will be answered when I implement classes and namespaces.

Briefly for now, they will look something like this:

```
my_company: namespace = {

    my_type: <T: type is X> type = {
        // ...
    }

}
```

For more about `is X` please see [P2392: Pattern matching using `is` and `as`](https://wg21.link/p2392) such as section 2.1.2, and my [CppCon 2021 talk about it](https://www.youtube.com/watch?v=raB_289NxBk).

**Comment by jcanizales** [comment]
> Briefly for now, they will look something like this:
> 
> ```
> my_company: namespace = {
> 
>     my_type: <T: type is X> type = {
>         // ...
>     }
> 
> }
> ```

A comment about that proposed syntax is that, unless you're planning to ban adding names to the same namespace in different files (or in different sections of a same file), this would make it look like the whole namespace is being re-declared and replaced:

```
my_company: namespace = {
    type_1: type = {
        // ...
    }
}
// ...
my_company: namespace = {
    type_2: type = {
        // ...
    }
}
```
