### ISSUE TITLE
[BUG] Empty `@value` type lowers with unused parameters

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#560]
<a id="title"/>

**[T](#title)itle**: Empty `@value` type lowers with unused parameters.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/EcPEz57P3>):

```Cpp2
t: @value type = { }
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -fsanitize=undefined -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: No warnings.

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

class t;


//=== Cpp2 type definitions and function declarations ===========================

class t {
public: [[nodiscard]] auto operator<=>(t const& that) const -> std::strong_ordering = default;
public: t(t const& that);

public: auto operator=(t const& that) -> t& ;
public: t(t&& that) noexcept;
public: auto operator=(t&& that) noexcept -> t& ;
public: explicit t();

};
auto main() -> int;


//=== Cpp2 function definitions =================================================



t::t(t const& that){}
auto t::operator=(t const& that) -> t& {
                                return *this;}
t::t(t&& that) noexcept{}
auto t::operator=(t&& that) noexcept -> t& {
                                return *this;}
t::t(){}
auto main() -> int{}
```
</details>

<a id="out"/>
<a href="#out">O</a>utput:

```output
main.cpp2:1:15: warning: unused parameter 'that' [-Wunused-parameter]
    1 | t::t(t const& that){}
      |               ^
main.cpp2:2:28: warning: unused parameter 'that' [-Wunused-parameter]
    2 | auto t::operator=(t const& that) -> t& {
      |                            ^
main.cpp2:4:10: warning: unused parameter 'that' [-Wunused-parameter]
    4 | t::t(t&& that) noexcept{}
      |          ^
main.cpp2:5:23: warning: unused parameter 'that' [-Wunused-parameter]
    5 | auto t::operator=(t&& that) noexcept -> t& {
      |                       ^
4 warnings generated.
```

**Comment by JohelEGP** [comment]
This is the workaround (<https://cpp2.godbolt.org/z/nozv7ef5v>):
```Cpp2
t: @value type = {
  operator=: (out this, that) = _ = that;
}
main: () = { }
```

**Comment by hsutter** [comment]
Thanks! I think the simplest thing is to emit `[[maybe_unused]]` on a `that` parameter if the class is empty.

I'll also add `-Wunused-parameter` to my GCC and Clang regression tests.

**Comment by hsutter** [comment]
> I'll also add `-Wunused-parameter` to my GCC and Clang regression tests.

I wrote that before realizing that would make me update a dozen regression tests that had unused parameters. But all's well that ends well, because _that_ in turn made me add full support for `_` unused parameter names. 😁 The spread of `_` wildcards throughout the language continues as I find places I missed...
