### ISSUE TITLE
[BUG] Type-scope placeholder variable not rejected

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#565]
<a id="title"/>

**[T](#title)itle**: Type-scope placeholder variable not rejected.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/xWG9ecPGr>):

```Cpp2
t: @struct type = {
  _: i32;
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -fsanitize=undefined -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: An error on `  _: i32;`.

<a id="actual"/>

**[A](#actual)ctual result and error**: `  public: cpp2::i32 auto_2_3; `

**Comment by realgdman** [comment]
That might be ok, consider some existing protocol or WinAPI structure with reserved or dummy fields which names doesn't matter.

**Comment by JohelEGP** [comment]
They might not matter.
But I doubt they'll like ABI changes because the variable's source line changed.
Remember that `_` variables lower to `auto_`_`line`_`_`_`column`_.

**Comment by hsutter** [comment]
Thanks!

I'm not sure this is a bug though? The meaning of `_` is to express "don't care." Here, it would say we don't care about the name of the member variable (including for ABI reasons). If we care about the name we should give it a name.

> But I doubt they'll like ABI changes because the variable's source line changed.
> Remember that `_` variables lower to `auto_`_`line`_`_`_`column`_.

If the line number changes, then:
- It won't change the type's name or object layout.
- It will change the anonymized name for that member. But that name already can't be used in the Cpp2 or Cpp1 code, and if some external code is depending on the anonymized name then that's a "do care" reason to give the object a stable known name, right?

If I've missed something, please reopen. Thanks again!
