### ISSUE TITLE
[BUG] Can't use `sizeof`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#566]
<a id="title"/>

**[T](#title)itle**: Can't use `sizeof`.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/8bs65Tzcz>): `main: () -> int = sizeof(i32);`

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -fsanitize=undefined -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: `Program returned: 4`.

<a id="actual"/>

**[A](#actual)ctual result and error**: `main.cpp2(1,25): error: use 'sizeof(()', not 'sizeof ('`.

**Comment by hsutter** [comment]
Thanks. That's a migration diagnostic, and it should check that the next character isn't `(` before complaining!
