### ISSUE TITLE
[BUG] Permit deduced return type for `operator<=>`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#571]
<a id="title"/>

**[T](#title)itle**: Permit deduced return type for `operator<=>`.

<a id="desc"/>

**[D](#desc)escription**:

Currently, Cpp2 offers some `@ordered` metafunctions.
It also permits authoring `operator<=>` so long as you avoid running into this:
`error: operator<=> must return std::strong_ordering, std::weak_ordering, or std::partial_ordering`.

This behavior leaves out the case where the ordering shouldn't be fixed at the source level,
but be left to the Cpp1 compiler to compute based on the type's members.

The use case is a `quantity` template.
As it stands, it can either:
- Be `@ordered`, or
- be the order of floating-point, which isn't `std::strong_ordering`.

The first option means that comparing `quantity<float>`
would result in a hard error rather than being weakened to the floating point's ordering.
The second option is not good for users of integer types.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer**:

`operator<=>`: <https://cpp2.godbolt.org/z/GcMs3YGqM>.
```Cpp2
quantity: @struct <Number: type> type = {
  number: Number;
  operator<=>: (this, that) -> _;
}
main: () = _ = ((quantity<float>() < quantity<float>()));
```
`@ordered`: <https://cpp2.godbolt.org/z/j545odjxb>.
```Cpp2
quantity: @struct @ordered <Number: type> type = {
  number: Number;
}
main: () = _ = ((quantity<float>() < quantity<float>()));
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -fsanitize=undefined -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**:

For `operator<=>`, for the return type to lower to `auto`
so that it just works: <https://cpp2.godbolt.org/z/eG4K9WPc3>.

<a id="actual"/>

**[A](#actual)ctual result and error**:

`operator<=>`:
```output
main.cpp2(3,3): error: operator<=> must return std::strong_ordering, std::weak_ordering, or std::partial_ordering
```
`@ordered`:
```output
main.cpp2:3:102: error: no matching conversion for static_cast from 'std::partial_ordering' to 'std::strong_ordering'
    3 |   public: [[nodiscard]] auto operator<=>(quantity const& that) const -> std::strong_ordering = default;
      |                                                                                                      ^
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:1690:28: note: in defaulted three-way comparison operator for 'quantity<float>' first required here
 1690 |     return CPP2_FORWARD(t) < CPP2_FORWARD(u);
      |                            ^
main.cpp2:4:36: note: in instantiation of function template specialization 'cpp2::cmp_less<quantity<float>, quantity<float>>' requested here
    4 | auto main() -> int { (void) (cpp2::cmp_less(quantity<float>(),quantity<float>()));  }
      |                                    ^
```

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

`@ordered`:
```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

template<typename Number> class quantity;
  

//=== Cpp2 type definitions and function declarations ===========================

template<typename Number> class quantity {
  public: Number number; 
  public: [[nodiscard]] auto operator<=>(quantity const& that) const -> std::strong_ordering = default;

};
auto main() -> int;


//=== Cpp2 function definitions =================================================


auto main() -> int { (void) (cpp2::cmp_less(quantity<float>(),quantity<float>()));  }
```
</details>

**Comment by hsutter** [comment]
Good point, it now allows `_` as a return type. Thanks!

**Comment by JohelEGP** [comment]
Thank you!
