### ISSUE TITLE
[BUG] Argument list parentheses kept in non-local initialization

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#597]
<a id="title"/>

**[T](#title)itle**: Argument list parentheses kept in non-local initialization.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/7Gcvzzov8>):

```Cpp2
u: type == std::array<i32, 2>;
t: @struct type = {
  this: std::integral_constant<u, :u = (17, 29)>;
}
main: () = _ = :u = (17, 29);;
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -fsanitize=undefined -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: No warnings; same as the `u` in `main`.

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"


class t;
  

//=== Cpp2 type definitions and function declarations ===========================

using u = std::array<cpp2::i32,2>;
class t: public std::integral_constant<u,u{(17, 29)}> {

};
auto main() -> int;


//=== Cpp2 function definitions =================================================


auto main() -> int { static_cast<void>(u{17, 29});  }
```
</details>

<a id="out"/>
<a href="#out">O</a>utput:

```output
main.cpp2:2:45: warning: left operand of comma operator has no effect [-Wunused-value]
    2 | class t: public std::integral_constant<u,u{(17, 29)}> {
      |                                             ^~
1 warning generated.
```

**Comment by JohelEGP** [comment]
This is just a duplicate of #503.

**Comment by jcanizales** [comment]
`main: () = _ = :u = (17, 29);;`

What is the meaning of this?

**Comment by JohelEGP** [comment]
If you mean the extra semicolon, there's a few open bugs in the area: <https://github.com/hsutter/cppfront/issues?q=is%3Aissue+is%3Aopen+unnamed+declaration+in%3Atitle+>.
#479 is also related, see in particuar: <https://github.com/hsutter/cppfront/pull/479/files#diff-43ba71198da8225f205041c699dba495883d7d416c0b58916bf226aae97bafaeR4069-R4071>.
I haven't reported this particular instance, yet. Maybe it'd be a duplicate of another one.

Otherwise,
we're discarding (`_ =`) an unnamed declaration of `u` initialized with `(17, 29)`
in `main`'s *expression-statement*'s body.

**Comment by JohelEGP** [comment]
Opened #611 for that now.

**Comment by jcanizales** [comment]
Thanks for the explanation!
