### ISSUE TITLE
[BUG] Negation not working on bools and functions that return bools

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#61]
Exclamation signs disappear when compiled by cppfront.

Cpp2 code:
```cpp
main: () -> int = {
    b : bool = false;

    c := !b;

    while !b || !is_true() {
        b = !true;
    }
}

is_true: () -> bool = false;
```
after compilation with cppfront (I will limit the code to line that matters)
```cpp
[[nodiscard]] auto main() -> int{
    bool b { false }; 

    auto c { b }; 

    while( b ||  is_true() ) {
        b = true;
    }
}
```
All exclamation signs disappeared - no way to negate the boolean expression. 

Expected result:
```cpp
[[nodiscard]] auto main() -> int{
    bool b { false }; 

    auto c { !b }; 

    while( !b ||  !is_true() ) {
        b = !true;
    }
}
```

**Comment by hsutter** [comment]
It's not often I can fix a bug by removing the two characters `\\`. :)

I had disabled `!` (in favor of `not`) as an experiment to try having no unary prefix operators at all. But now I've re-enabled `-` and `+` and forgot to re-enable `!` too. Fixed, thanks!
