### ISSUE TITLE
[BUG] Function returning unnamed declaration needs extra semicolon

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#611]
<a id="title"/>

**[T](#title)itle**: Function returning unnamed declaration needs extra semicolon.

<a id="desc"/>

**[D](#desc)escription**:

This is the case when the function followed by Cpp1 code or EOF.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/cP1Gzrzad>):

```Cpp2
main: () = _ = :i32 = 0;
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++17 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: A well-formed program.

<a id="actual"/>

**[A](#actual)ctual result and error**: `main.cpp2: error: unexpected end of source file`.

**Comment by JohelEGP** [comment]
Doesn't reproduce anymore.

**Comment by gregmarr** [comment]
I suspect this was fixed by https://github.com/hsutter/cppfront/commit/785c44d29bdb2cc6ee9edcd0ab2047d7c1367217
