### ISSUE TITLE
[BUG] typo: precedence versus predecence

### ISSUE THREAD

**Issue by nigeltao** [hsutter/cppfront#621]
Basic typos in comments are usually not worth fixing. However, I wanted to learn more about "how does cppfront implement operator precedence" and the obvious `grep` gave zero leads. Only after I dug into `source/parse.h` more did I find the typographical error.

```
$ grep -i precedence source/*

$ grep -i predecence source/*
source/parse.h:    //     /*term*/-expression { { /* operators at this predecence level */ } /*term*/-expression }*
```

**Comment by JohelEGP** [comment]
There's no typo in your title :)
