### ISSUE TITLE
[BUG] Error due to a missing header when compiling cppfront with gcc-13

### ISSUE THREAD

**Issue by fedapo** [hsutter/cppfront#659]
Building of `cppfront` with gcc-13 results in the following error.

```
> g++-13 source/cppfront.cpp -std=c++20 -o cppfront
In file included from source/sema.h:21,
                 from source/cppfront.cpp:18:
reflect.h2: In function 'cpp2::meta::basic_enum__ret cpp2::meta::basic_enum(type_declaration&, const auto:141&)':
reflect.h2:819:75: error: incomplete type 'std::numeric_limits<signed char>' used in nested name specifier
reflect.h2:819:144: error: incomplete type 'std::numeric_limits<signed char>' used in nested name specifier
reflect.h2:822:82: error: incomplete type 'std::numeric_limits<short int>' used in nested name specifier
reflect.h2:822:152: error: incomplete type 'std::numeric_limits<short int>' used in nested name specifier
reflect.h2:825:82: error: incomplete type 'std::numeric_limits<int>' used in nested name specifier
reflect.h2:825:152: error: incomplete type 'std::numeric_limits<int>' used in nested name specifier
reflect.h2:828:93: error: incomplete type 'std::numeric_limits<long long int>' used in nested name specifier
reflect.h2:828:174: error: incomplete type 'std::numeric_limits<long long int>' used in nested name specifier
```

The problem is a missing `#include <limits>` in the file `cpp2util.h`. The problem seems to be a bit larger as several other includes (e.g. `<random>`) should be added. This shows only under specific building configs as the missing parts are in the else-branch of some conditionally included code, the preprocessor define controlling this being `CPP2_USE_MODULES`.

**Comment by JohelEGP** [comment]
Resolved by #660.

**Comment by hsutter** [comment]
Funny, the "closes #659" didn't seem to auto-close this... closing manually.

**Comment by JohelEGP** [comment]
That's because the word of power goes in the opening comment, not the title.

**Comment by hsutter** [comment]
Ah, so it's different between PRs and commits... for commits I got used to putting it in the title. Thanks for the tip!

**Comment by JohelEGP** [comment]
Yeah, in commit messages, it works anywhere.
