### ISSUE TITLE
[BUG] Basic initialization with enums doesn't work.

### ISSUE THREAD

**Issue by leejy12** [hsutter/cppfront#670]
**Describe the bug**
Commit: d43a1f61502ce6438f0f8a4a4cc01a26ac494ca4
Basic initialization with explicitly typed enums don't work.

**To Reproduce**

cpp2:
```
MyEnum: @enum type = {
    Foo;
    Bar;
}

main: () -> i32 = {
    x: MyEnum = MyEnum::Foo;
}
```

cpp1:
```
[[nodiscard]] auto main() -> cpp2::i32
{
    MyEnum x{MyEnum::Foo}; // Error!
}
```

The type of `MyEnum::Foo` is `cpp2::strict_value<cpp2::i8, MyEnum, false>` which can't be converted to `MyEnum` class.

**Comment by JohelEGP** [comment]
That's right.
I mentioned this at <https://github.com/hsutter/cppfront/commit/a92fdc8b63497e19e6f1ad0b3981d19acebf0926#r126543753>.

**Comment by hsutter** [comment]
Yup, this is next on my list.
