### ISSUE TITLE
[BUG] Type deduction from initialization should be allowed

### ISSUE THREAD

**Issue by Ashfmate** [hsutter/cppfront#677]
CTAD with auto does not work for some applications when trying to translate from standard cpp to cppfront

So the code that I had in standard cpp is `auto res = std::optional{ false };` (lol nvm the use, it was for a joke coding contest)
but when I wanted to translate to cppfront I used this line `res:= std::optional{false};` which then prompted this compile error "cpp2-cppfront: trying to pop an empty stack in rule: (unknown)"

Granted I am using Godbolt's compiler explorer and I don't know if this isn't an issue with the actual compiler though it did strike me strangely that it did not work

The code that I did get to work in cppfront is `res: std::optional<bool> = false;` which is fine but I do believe that the first one I showed should be allowed, and really thank you so much for making cppfront, it is a literal dream for most c++ developers lol

**Comment by AbhinavK00** [comment]
Use

```
res := std::optional(false);
```
Braced initializers don't work in cpp2, use parens instead.

**Comment by AbhinavK00** [comment]
Use

```
res := std::optional(false);
```
Braced initializers don't work in cpp2, use parens instead.

**Comment by Ashfmate** [comment]
> Use
> 
> ```
> res := std::optional(false);
> ```
> 
> Braced initializers don't work in cpp2, use parens instead.

Thanks so much, wondered why it didn't work lol

**Comment by AbhinavK00** [comment]
Happy to help! You should close this though.

**Comment by JohelEGP** [comment]
I do wonder.
Using braces instead of parentheses deserves a better error message.
