### ISSUE TITLE
[BUG] Possible FOR loop scoping problem

### ISSUE THREAD

**Issue by guybrush77** [hsutter/cppfront#683]
**Describe the bug**

Possible `for` loop scoping problem

**To Reproduce**

Try the following cpp2 code:

```
Foo: type = {}

main: () = {

    numbers: std::vector<int> = ( 1, 2 );

    for numbers do (n) {
        std::cout << n << "\n";
    }

    n: Foo;
    n = ();
}
```

I would expect this code to compile. Instead it fails, with MSVC producing an error:
```
repro.cpp2(8): error C2228: left of '.value' must have class/struct/union
repro.cpp2(8): note: type is 'const int'
```

**Additional context**

Notice that the `n` var inside the loop and after it have the same name.

Interestingly, if we delete line 8 (with `cout`), the problem goes away.

Also, if we initialize `Foo` on the same line, i.e.
```
n: Foo = ();
```
then the example works.

**Comment by hsutter** [comment]
Thanks! I see the bug, fix coming. 👍 🙏

**Comment by filipsajdak** [comment]
I will check the issue with deducing pointers.
