### ISSUE TITLE
[BUG] `<...>` lowers to unnamed pack

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#708]
<a id="title"/>

**[T](#title)itle**: `<...>` lowers to unnamed pack.

<a id="desc"/>

**[D](#desc)escription**:

Since commit 025d7aff26a5bf24e77dc46fd7700f41d3e7e03e, `...` is an _identifier_.
So `...` in a _template-parameter-declaration-list_ lowers to `typename ...`,
just like `T` would lower to `typename T`.

Feature or bug?
I call bug.
#603 makes it so that template template parameters are emitted.
Because it chooses to lower them unnamed, it lowers `T: <...>` to `template<typename> class T`.
The existing branch in `main` to print a pack's ellipsis,
`if (n.declaration->is_variadic) {` (<https://github.com/hsutter/cppfront/pull/603/files#diff-e683e1259bbc0d6de7f1fbf797fb772f31a0a1ef2254ec317d15c298102fa3f3R3931>)
isn't exercised because it the declaration isn't variadic (it's name just happens to be `...`).

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/YbzMc3dh3>):

```Cpp2
f: <...> () = { }
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: A diagnostic due to naming a declaration `...`.

<a id="actual"/>

**[A](#actual)ctual result and error**:

```output
Program returned: 0
```

```C++
template<typename ...> auto f() -> void{}
```

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"



//=== Cpp2 type definitions and function declarations ===========================

template<typename ...> auto f() -> void;
auto main() -> int;


//=== Cpp2 function definitions =================================================

template<typename ...> auto f() -> void{}
auto main() -> int{}
```
</details>

**Comment by JohelEGP** [comment]
A simpler reproducer (<https://cpp2.godbolt.org/z/Kf8fdWz95>):
```Cpp2
main: () = {
  ...: int = 0;
}
```
```C++
auto main() -> int{
  int ... {0}; 
}
```

**Comment by hsutter** [comment]
Thanks! Yes, that's a bug... fixing now...
