### ISSUE TITLE
[BUG] Assertion failure on malformed type alias definition

### ISSUE THREAD

**Issue by cpp-niel** [hsutter/cppfront#712]
**Describe the bug**
The cppfront compiler terminates with an assertion failure when a type alias definition incorrectly uses `=` instead of `==`. 

**To Reproduce**
1. Sample code - distilled down to minimal essentials please
The behaviour can be reproduced by trying to compile this code:
```
abc: type = {
    a: int;
}

xyz: type = abc;
```

2. Command lines including which C++ compiler you are using

simple compilation without any additional command line arguments triggers the problem

3. Expected result - what you expected to happen

A syntax error from the compiler

4. Actual result/error

```
cppfront: source/cppfront.cpp:5356: void cpp2::cppfront::emit(const cpp2::declaration_node&, const std::string&): Assertion `n.initializer && n.initializer->is_compound()' failed.
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

**Additional context**
Compiler explorer link: https://godbolt.org/z/6ceYTeMYP

**Comment by hsutter** [comment]
Thanks!
