### ISSUE TITLE
[SUGGESTION] Monadic Types

### ISSUE THREAD

**Issue by Oliver-makes-code** [hsutter/cppfront#713]
Monadic types never really felt like they fit in regular C++, but with this being an overhaul of syntax, it feels more functional and data oriented. I'm suggesting something similar to Rust enums, a way to model data that can have multiple discrete types, but are all mutually exclusive, unlike C unions.

Here's a possible syntax, we could use other syntax if wanted
```cpp
SomeMonad: monad = {
  FirstValue(string);
  SecondValue(int);
}
```

It'd probably compile to the following C++ code
```cpp
enum class SomeMonadType {
  FirstValue,
  SecondValue
};

struct SomeMonad {
  SomeMonadType type;
  union {
    string FirstValue;
    int SecondValue;
  } value;
};
```

It could also be compiled to a set of classes where the base `SomeMonad` class only allows inheritance to the values of the monad, which might be safer.

Allowing a concise way to model multiple data types in the same variable allows you to be more certain of code flow and returns, instead of needing to return a void pointer or similar.

**Comment by AbhinavK00** [comment]
I think what you suggest here is already achived in cppfront by the use of `union` metafunction which is a safe, discriminated c-union.

**Comment by Oliver-makes-code** [comment]
> I think what you suggest here is already achived in cppfront by the use of `union` metafunction which is a safe, discriminated c-union.
Ah it looks like it is, I didn't see that in my initial search.
