### ISSUE TITLE
[BUG] Can't declare variable/parameter of type pointer to function

### ISSUE THREAD

**Issue by ntrel** [hsutter/cppfront#718]
**Describe the bug**
cppfront errors when attempting to do this.

**To Reproduce**
```
f: (a: *() -> int) = {}
```
    callback.cpp2(3,9): error: '*'/'const' type qualifiers must be followed by a type name or '_' wildcard (at '(')

Using a type alias also fails:
```
F: type == () -> int;
f: (a: *F) = {}
```
    callback.cpp2(1,13): error: a 'type ==' alias declaration must be followed by a type name

**Comment by JohelEGP** [comment]
This is #711 and #343.

**Comment by ntrel** [comment]
Those use `std::function`, a template type, whereas this is about parsing a pointer to function type. Though it looks like #526 would fix this too.

**Comment by JohelEGP** [comment]
They're all about being able to name function types.
To name a pointer to function type,
you need to name a function type.

**Comment by hsutter** [comment]
Thanks! Your code is now working with PR #1183:

```cpp
F: type == () -> int;
f1: (a: *F)         = std::cout << a();
f2: (a: *() -> int) = std::cout << a();

g: () -> int = 42;

main: () = {
    f1(g&);
    f2(g&);
}
```
