### ISSUE TITLE
[BUG] Default-access not considered by reflection API

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#721]
<a id="title"/>

**[T](#title)itle**: Default-access not considered by reflection API.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/G57h9YWev>):

```Cpp2
t: @basic_value type = {
  operator=: (move this) = { }
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**:
Same as `public operator=: (move this) = { }` (<https://cpp2.godbolt.org/z/eMMYsdMYq>).

<a id="actual"/>

**[A](#actual)ctual result and error**:
`main.cpp2(2,3): error: while applying @basic_value - a value type may not have a non-public destructor`.

**Comment by hsutter** [comment]
Good catch, thanks!
