### ISSUE TITLE
[BUG] Characters inside character literals should be ignored in the `process_cpp2_line` function

### ISSUE THREAD

**Issue by cpp-niel** [hsutter/cppfront#732]
**Describe the bug**
The `process_cpp2_line` function in cppfront tracks, for instance, the opening and closing of braces and emits an error if the end of a file is reached before all opened braces have been closed again. This analysis ignores braces inside string literals, but not inside character literals. 

**To Reproduce**
1. Sample code - distilled down to minimal essentials please

Here's an example that confuses the analysis by putting a left brace in a character literal:
```
main : () -> int = {
    return '{' as int;
}
```

2. Command lines including which C++ compiler you are using

`cppfront -p -o test.cpp test.cpp2`

where `test.cpp2` contains the above code.

3. Expected result - what you expected to happen

I would expect cppfront to compile the code without issue.

4. Actual result/error

```
test.cpp2(4,0): error: end of file reached with 1 missing } to match earlier { on line 1
```

**Additional context**

https://godbolt.org/z/nhcfzr379

**Comment by hsutter** [comment]
Thanks! I see this was being accounted for in Cpp1 lines, but not in Cpp2 lines.
