### ISSUE TITLE
[BUG] No implicit move or forward on last use in initialization

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#749]
<a id="title"/>

**[T](#title)itle**: No implicit move or forward on last use in initialization.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/Pb6YaYvsT>):

```Cpp2
f: (copy x)    = { _ = x; } // OK, moves.
f: (forward x) = { _ = x; } // OK, forwards.
g: (copy x)    = { i := x; } // Wrong, doesn't move.
g: (forward x) = { i := x; } // Wrong, doesn't forward.
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**:

```C++
auto f(auto x) -> void{static_cast<void>(std::move(x));}// OK, moves.
auto f(auto&& x) -> void{static_cast<void>(CPP2_FORWARD(x)); }// OK, forwards.
auto g(auto x) -> void{auto i {std::move(x)}; }// Wrong, doesn't move.
auto g(auto&& x) -> void{auto i {CPP2_FORWARD(x)}; }// Wrong, doesn't forward.
```

<a id="actual"/>

**[A](#actual)ctual result and error**:

```output
Program returned: 0
```

```C++
auto f(auto x) -> void{static_cast<void>(std::move(x));}// OK, moves.
auto f(auto&& x) -> void{static_cast<void>(CPP2_FORWARD(x)); }// OK, forwards.
auto g(auto x) -> void{auto i {x}; }// Wrong, doesn't move.
auto g(auto&& x) -> void{auto i {x}; }// Wrong, doesn't forward.
```

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"



//=== Cpp2 type definitions and function declarations ===========================

auto f(auto x) -> void;
auto f(auto&& x) -> void;
auto g(auto x) -> void;
auto g(auto&& x) -> void;
auto main() -> int;


//=== Cpp2 function definitions =================================================

auto f(auto x) -> void{static_cast<void>(std::move(x));}// OK, moves.
auto f(auto&& x) -> void{static_cast<void>(CPP2_FORWARD(x)); }// OK, forwards.
auto g(auto x) -> void{auto i {x}; }// Wrong, doesn't move.
auto g(auto&& x) -> void{auto i {x}; }// Wrong, doesn't forward.
auto main() -> int{}
```
</details>

**Comment by hsutter** [comment]
Thanks! Repeating rationale here from #792 comment thread: The issue is that I was trying out lifting move-from-last-use if the last use was in an initializer, because of examples like `view: std::span = local_variable;` when that was the last use of `local_variable`, which is an error for an rvalue. But that also suppresses a righteous move in examples like `result := local_variable;`. So I now agree those should be treated as rvalues too, and if that causes an error for an rvalue then the programmer must write an explicit discard of the initializer variable.
