### ISSUE TITLE
[BUG] [CPP2_UFCS] error: too many arguments to function call, expected single argument 's' 

### ISSUE THREAD

**Issue by lexasub** [hsutter/cppfront#756]
**Describe the bug**
global.cpp2:9:3: error: too many arguments to function call, expected single argument 's', have 2 arguments
  CPP2_UFCS(open, file, s);

**To Reproduce**
global.cpp2:
IReader: @interface type = {
	open: (this, in s: std::string_view) -> void;
}
#include <fstream>
FileReader: type = {
	this: IReader = ();	
	file: std::ifstream;
	open: (override this, in s: std::string_view) -> void = {
		file.open(s);
	}
}
Command lines including which C++ compiler you are using:
../cppfrontO2 global.cpp2 -o global.cpp; clang++ -I .. -std=c++20 global.cpp -o file #i get error on clang stage
Expected result - compiled program

**Additional context**
in ../ - src of cppfront and binary
generated cpp1:
#include "cpp2util.h"
class IReader;
#line 5 "global.cpp2"
class FileReader;
class IReader {
 public: virtual auto open(cpp2::in<std::string_view> s) const -> void = 0;
public: virtual ~IReader() noexcept;
 public: IReader() = default;
 public: IReader(IReader const&) = delete; /* No 'that' constructor, suppress copy */
 public: auto operator=(IReader const&) -> void = delete;
#line 3 "global.cpp2"
};
#include <fstream>
class FileReader: public IReader {
 private: std::ifstream file;
 public: auto open(cpp2::in<std::string_view> s) const -> void override;
 public: FileReader() = default;
 public: FileReader(FileReader const&) = delete; /* No 'that' constructor, suppress copy */
 public: auto operator=(FileReader const&) -> void = delete;
#line 11 "global.cpp2"
};
IReader::~IReader() noexcept{}
#line 8 "global.cpp2"
 auto FileReader::open(cpp2::in<std::string_view> s) const -> void{
  CPP2_UFCS(open, file, s);
 }

**Comment by JohelEGP** [comment]
You need an `inout this` parameter to modify the data member: <https://cpp2.godbolt.org/z/fvbs6djqf>.

**Comment by lexasub** [comment]
> You need an `inout this` parameter to modify the data member: https://cpp2.godbolt.org/z/fvbs6djqf.

thank you!
