### ISSUE TITLE
[BUG] Variadic parameter with invalid type ignored

### ISSUE THREAD

**Issue by ntrel** [hsutter/cppfront#763]
**Describe the bug**
The code below specifies the type of the variadic parameter `args` as `int`, which is invalid.

**To Reproduce**
```c++
main: () = 
{
    f("", ""); // should error, not int
}

f: (args...: int) = {}
```
The Cpp1 signature generated for the variadic overload is a template with type inference for `args`:
```c++
auto f(auto const& ...args) -> void{}
```
So the `: int` has been ignored and `f` should not be a template as the parameter type was specified.

**Comment by hsutter** [comment]
Are you using the latest `main`? I think I fixed a bug in this area a few weeks ago that could looks like this.

Right now I can't reproduce the bug, I get the expected (correct) error on all the compilers I tried. For me the generated declaration of the above `f` is:

```
auto f(auto const& ...args) -> void
CPP2_REQUIRES ((std::is_convertible_v<CPP2_TYPEOF(args), int> && ...))
    // ^ this is a macro so we can suppress it on GCC 10 to avoid a compiler bug
```

and the definition of `f` is:

```
auto f(auto const& ...args) -> void
requires ((std::is_convertible_v<CPP2_TYPEOF(args), int> && ...))
    // ^ this is emitted on all compilers
{}
```

Is that what you get in your generated `.cpp`?

**Comment by ntrel** [comment]
> I think I fixed a bug in this area a few weeks ago

Sorry, you are right I must have been testing on an older commit. I can confirm the generated code is as you posted, with the constraint.
