### ISSUE TITLE
[BUG] `constexpr` anonymous object rejected as function or type

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#787]
<a id="title"/>

**[T](#title)itle**: `constexpr` anonymous object rejected as function or type.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/9d7f8v8Pa>):

```Cpp2
main: () = {
  _: int == 0;
}
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: A better error message, or a valid program.

<a id="actual"/>

**[A](#actual)ctual result and error**: `main.cpp2(2,3): error: '_' (wildcard) may not be the name of a function or type - it may only be used as the name of an anonymous object or anonymous namespace`

**Comment by ntrel** [comment]
If you remove the `_`, you get `error: syntax error at '==' - did you mean '='? (at '==')`.

It would indeed be useful to be able to ensure compile-time evaluation of an expression by using `:== expr`.

**Comment by hsutter** [comment]
Thanks!
