### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iprtel** [hsutter/cppfront#792]
**Describe the bug**
cppfront produces CPP1 code that is no accepted by gcc-11.4 or clang-18.0.0

**To Reproduce**
1. in issue_base.h
```
class IssueBase {
public:
    virtual bool virtualConstFunction() const = 0;
    virtual bool virtualFunction() = 0;
};
```
2. in issue.cpp2
```
#include "issue_base.h"
Issue : type = {
    virtualConstFunction : (this) -> bool = {
        std::cout << "virtual const function called\n";
        return true;
    }
    virtualFunction : (inout this) -> bool = {
        std::cout << "virtual function called\n";
        return false;
    }
}

main : () = {
    issue : Issue = ();
    issue.virtualFunction();
    issue.virtualConstFunction();
    issue.virtualFunction();
}
```

Cppfront generates `std::move(issue)` for the last use of `issue` in main. This works fine if `virtualConstFunction` is the last function called but fails if `virtualFunction` is the last call.

**gcc-11.4.0:**
> [proc] Executing command: /usr/bin/cmake --build /workspaces/cpp2_learn/build --config Debug --target issue -j 10 --
[build] [1/3  33% :: 0.007] Generating ../_cppfront/issue.cpp
[build] /workspaces/cpp2_learn/issue/issue.cpp2... ok (mixed Cpp1/Cpp2, Cpp2 code passes safety checks)
[build] 
[build] [2/3  66% :: 1.423] Building CXX object issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o
[build] FAILED: issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o 
[build] /usr/bin/g++  -I/workspaces/cpp2_learn/issue -isystem /workspaces/cpp2_learn/cppfront/cppfront/include -g -std=gnu++20 -MD -MT issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o -MF issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o.d -o issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o -c /workspaces/cpp2_learn/build/_cppfront/issue.cpp
[build] In file included from /workspaces/cpp2_learn/build/_cppfront/issue.cpp:7:
[build] /workspaces/cpp2_learn/issue/issue.cpp2: In instantiation of 'main()::<lambda(auto:80&&)> [with auto:80 = Issue]':
[build] /workspaces/cpp2_learn/issue/issue.cpp2:19:5:   required from here
[build] /workspaces/cpp2_learn/issue/issue.cpp2:19:5: error: 'virtualFunction' was not declared in this scope
[build]    19 |     issue.virtualFunction();
[build]       |     ^
[build] ninja: build stopped: subcommand failed.

**clang-18.0.0:**
> [build] [1/3  33% :: 0.006] Generating ../_cppfront/issue.cpp
[build] /workspaces/cpp2_learn/issue/issue.cpp2... ok (mixed Cpp1/Cpp2, Cpp2 code passes safety checks)
[build] 
[build] [2/3  66% :: 1.704] Building CXX object issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o
[build] FAILED: issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o 
[build] /usr/bin/clang++-18  -I/workspaces/cpp2_learn/issue -isystem /workspaces/cpp2_learn/cppfront/cppfront/include -g -std=gnu++20 -MD -MT issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o -MF issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o.d -o issue/CMakeFiles/issue.dir/__/_cppfront/issue.cpp.o -c /workspaces/cpp2_learn/build/_cppfront/issue.cpp
[build] /workspaces/cpp2_learn/issue/issue.cpp2:19:17: error: use of undeclared identifier 'virtualFunction'
[build]    19 |     CPP2_UFCS_0(virtualFunction, std::move(issue));
[build]       |                 ^
[build] /workspaces/cpp2_learn/issue/issue.cpp2:19:5: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<Issue>' requested here
[build]    19 |     CPP2_UFCS_0(virtualFunction, std::move(issue));
[build]       |     ^
[build] /workspaces/cpp2_learn/cppfront/cppfront/include/cpp2util.h:797:2: note: expanded from macro 'CPP2_UFCS_0'
[build]   797 | }(PARAM1)
[build]       |  ^
[build] 1 error generated.
[build] ninja: build stopped: subcommand failed.

**The generated main:**
```
#line 14 "/workspaces/cpp2_learn/issue/issue.cpp2"
auto main() -> int{
    Issue issue {}; 

    CPP2_UFCS_0(virtualFunction, issue);
    CPP2_UFCS_0(virtualConstFunction, issue);
    CPP2_UFCS_0(virtualFunction, std::move(issue));
}
```

If the `std::move(...)` is removed around `issue` both compilers accept the code.

**Comment by JohelEGP** [comment]
For the implicit move, see <https://github.com/hsutter/cppfront/issues/305#issuecomment-1586580100>.
You need to add `_ = issue;`.

To actually declare `Issue` as an `IssueBase`,
you need a `this: IssueBase;` data member.
To override the virtual functions,
you need `override this` and `override inout this` parameters.

**Comment by iprtel** [comment]
Thanks. So my simplified test case is issue.cpp2. I still get the same error. 
```
Issue : type = {
    constFunction : (this) -> bool = {
        std::cout << "const function called\n";
        return true;
    }
    nonConstFunction : (inout this) -> bool = {
        std::cout << "non const function called\n";
        return false;
    }
}

main : () = {
    issue : Issue = ();
    _ = issue.nonConstFunction();
    _ = issue.constFunction();
    _ = issue.nonConstFunction();
}
```

Thanks for the help on the inheritance. I struggled with that.

**Comment by JohelEGP** [comment]
You need to discard the last use of `issue`, without any calls.

> You need to add `_ = issue;`.

**Comment by iprtel** [comment]
So if the last function you called is non-const you need to discard the object.
Thanks.

**Comment by iprtel** [comment]
@JohelEGP  sorry to come once again. 
My understanding about the discarding after the last non-const call is not sufficient.
This `main`also fixes the problem:
```
main : () = {
    issue : Issue = ();
    _ = issue.nonConstFunction();
    _ = issue.constFunction();
    result : _ = issue.nonConstFunction();
    std::cout << result ;
}
```
Here the move is on `result` : 
```
#line 12 "/workspaces/cpp2_learn/issue/issue.cpp2"
auto main() -> int{
    Issue issue {}; 
    static_cast<void>(CPP2_UFCS_0(nonConstFunction, issue));
    static_cast<void>(CPP2_UFCS_0(constFunction, issue));
    auto result {CPP2_UFCS_0(nonConstFunction, issue)}; 
    std::cout << std::move(result);
}
```

**Comment by JohelEGP** [comment]
Rvalues are convertible to reference to `const`,
so printing `<<` works because the rhs is taken by reference to `const`.

**Comment by iprtel** [comment]
So why is the discard on `issue` no longer needed? I thought that it was necessary since the last call had  `inout this` and so the object counts as return value that needs to be discarded.

**Comment by JohelEGP** [comment]
`operator<<` typically looks like `operator<<: (inout s: std::ostream, in x: T)`,
so `x` accepts moved objects.

**Comment by iprtel** [comment]
Thanks for the explenation. But I'm more interessted why 
```
main : () = {
    issue : Issue = ();
    result : _ = issue.nonConstFunction();
}
```
is fine. While 
```
main : () = {
    issue : Issue = ();
    _ = issue.nonConstFunction();
}
```
requires a `_ = issue;`

**Comment by JohelEGP** [comment]
That must be #749.

**Comment by hsutter** [comment]
You're right, both should require `_ = issue;`. Will fix.

The issue is that I was trying out lifting move-from-last-use if the last use was in an initializer, because of examples like `view: std::span = local_variable;` when that was the last use of `local_variable`. But that also suppresses a righteous move in examples like `result := local_variable;`. So I now agree those should have an explicit discard of the local variable.

**Comment by iprtel** [comment]
Are you at all concerned that people will just put explicit discards all over the place when trying to fix a compilation problem that the don't understand fully?

**Comment by tomFlowee** [comment]
lets continue this topic on https://github.com/hsutter/cppfront/discussions/901
