### ISSUE TITLE
[BUG] Signed to unsigned conversion warnings in bounds checking.

### ISSUE THREAD

**Issue by gregmarr** [hsutter/cppfront#799]
**Describe the bug**
warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long')

**To Reproduce**
1. Sample code - distilled down to minimal essentials please

https://cpp2.godbolt.org/z/Wh7jTczzh

```
main: () = {
    v: std::vector = ( 1, 2, 3, 4, 5 );
    v[6] = 0;
}
```

Can avoid the warning by using `v[6u]`.

2. Command lines including which C++ compiler you are using
-std=c++23 -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -Werror=unused-value

3. Expected result - what you expected to happen

Clean compile, and out of bounds access error when executed.

4. Actual result/error

```
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:467:30: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
  467 |     return CPP2_FORWARD(x) [ CPP2_FORWARD(arg) ];
      |            ~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:271:37: note: expanded from macro 'CPP2_FORWARD'
  271 | #define CPP2_FORWARD(x)             std::forward<decltype(x)>(x)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/main.cpp:19:11: note: in instantiation of function template specialization 'cpp2::assert_in_bounds<std::vector<int>, int>' requested here
   19 |     cpp2::assert_in_bounds(std::move(v), 6) = 0;
      |           ^
1 warning generated.
```

**Additional context**
Investigating #798 File name and line number when the application terminates

**Comment by JohelEGP** [comment]
> 4\. Expected result - what you expected to happen
> 
> 
> Clean compile, and out of bounds access error when executed.

I disagree.
I like that I get a reminder that `6` should have been unsigned.
And although you get the warning, you still get the contract failure: <https://cpp2.godbolt.org/z/db6Waze1z>.
```output
In file included from /app/build/main.cpp:6:
In file included from /app/cpp2util.h:1:
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:467:30: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
  467 |     return CPP2_FORWARD(x) [ CPP2_FORWARD(arg) ];
      |            ~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:271:37: note: expanded from macro 'CPP2_FORWARD'
  271 | #define CPP2_FORWARD(x)             std::forward<decltype(x)>(x)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/main.cpp:19:11: note: in instantiation of function template specialization 'cpp2::assert_in_bounds<std::vector<int>, int>' requested here
   19 |     cpp2::assert_in_bounds(std::move(v), 6) = 0;
      |           ^
1 warning generated.
[5/5] Linking CXX executable main
Program returned: 139
Bounds safety violation: out of bounds access attempt detected
libc++abi: terminating
Program terminated with signal: SIGSEGV
```

**Comment by realgdman** [comment]
Won't it be inconvenient on big codebases? For example cppfront itself has many [1]

**Comment by JohelEGP** [comment]
Just because there's guaranteed runtime safety
doesn't mean the compile-time warnings lose their value.
If you think so, you can just opt-out of such warnings.

**Comment by gregmarr** [comment]
> I disagree.
> I like that I get a reminder that 6 should have been unsigned.

I don't see a need for obviously positive integer literals to be manually marked as unsigned just to avoid this warning.

**Comment by JohelEGP** [comment]
That makes sense.
I know the heuristics on such warnings can vary widely between Clang and GCC.
Maybe you should try reporting to them.

**Comment by gregmarr** [comment]
This is not a warning in Cpp1.  It shouldn't result in warnings in the support scaffolding in Cpp2.
```
    std::vector v {1, 2, 3, 4, 5}; 
    v[0] = 0;
```

There's nothing to report to Clang or GCC here.  The issue is entirely due to the addition of the `assert_in_bounds` wrapper.  It is already doing checks for signed vs unsigned and converting to unsigned to check the range, so it should do what it can to make sure that it doesn't add a warning.  It may be that this isn't feasible in current Cpp1 to determine whether it should pass signed or unsigned, since not every `operator[]` takes unsigned.  Maybe it requires warning suppression around the `x[arg]` call, which would be a bit ugly, but it's something that the Cpp2 support functions should strive to do.

**Comment by JohelEGP** [comment]
You're right.
In Cpp1, that doesn't warn: <https://compiler-explorer.com/z/r98dd1Gvj>.

It seems that for `assert_in_bounds` to also not warn
it needs to do the same thing Cppfront does for `is` expressions.
That is, raise the index to a template argument: <https://compiler-explorer.com/z/nTqnY6vWM>.

> It is already doing checks for signed vs unsigned and converting to unsigned to check the range

Is it?

**Comment by gregmarr** [comment]
>> It is already doing checks for signed vs unsigned and converting to unsigned to check the range
> Is it?

Yes, it is.  https://github.com/hsutter/cppfront/blob/083c8a0d48df3d3d0d768b9a8b7ab2d26b98b515/include/cpp2util.h#L459-L468

> It seems that for assert_in_bounds to also not warn
> it needs to do the same thing Cppfront does for is expressions.
> That is, raise the index to a template argument: https://compiler-explorer.com/z/nTqnY6vWM.

I was able to fix it for `operator[](std::size_t index)` but then it warns for a class with `operator[](std::ptrdiff_t index)`.

The issue is that in order to prevent a possible conversion warning, it needs to make sure that `x[arg]` is called with `arg` being exactly the type that `operator[]` expects, and that could be a template or be overloaded, so it gets very messy.

```
auto assert_in_bounds(auto&& x, auto&& arg ...
     return CPP2_FORWARD(x) [ CPP2_FORWARD(arg) ];
```

This doesn't change the issue above at all, but since `arg` is guaranteed to be an integral type, I don't think the `&&` and `CPP2_FORWARD()` are needed.

**Comment by JohelEGP** [comment]
That was introduced by #551.
Was it a wrong move to use the same signedness of the argument?

**Comment by gregmarr** [comment]
I think that commit is fine.  It resolved the signedness compare issue in the contract.  There is still a signedness forwarding issue however in the body.

It could be that this wasn't triggered by your CE setup at the time.  I found it using one of your most recent magnificent 4-pane configs that transpiles and then compiles and runs.

**Comment by JohelEGP** [comment]
> > It seems that for assert_in_bounds to also not warn
> > it needs to do the same thing Cppfront does for is expressions.
> > That is, raise the index to a template argument: https://compiler-explorer.com/z/nTqnY6vWM.
> 
> I was able to fix it for `operator[](std::size_t index)` but then it warns for a class with `operator[](std::ptrdiff_t index)`.

That doesn't happen with a template argument: <https://cpp2.godbolt.org/z/qW45c4vP9>.

**Comment by gregmarr** [comment]
> That doesn't happen with a template argument: https://cpp2.godbolt.org/z/qW45c4vP9.

It also doesn't work with variables, only literals.  It might be enough to fix this only for literals, not sure.

**Comment by JohelEGP** [comment]
The fix for variables is <https://github.com/hsutter/cppfront/issues/799#issuecomment-1791329205>.

**Comment by gregmarr** [comment]
Yeah, that's what I meant by "enough to fix this only for literals".

**Comment by hsutter** [comment]
Ah, this is one of the "perfect forwarding isn't perfect" cases. The language has a few built-in special meanings that evaporate when forwarded -- notably the dual meaning of literal '0' (once you forward it, it's no longer literal '0' with the weird pointer-integer duality), but also an integer literal being able to sign-promote correctly without warning (once you forward it, it's no longer a literal).

So the only way to make this warning go away is to ensure the actual subscript is done in a (holds nose) macro.

That is, changing this:

```
auto assert_in_bounds(auto&& x, auto&& arg CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT) -> decltype(auto)
    requires (std::is_integral_v<CPP2_TYPEOF(arg)> &&
             requires { std::size(x); std::ssize(x); x[arg]; std::begin(x) + 2; })
{
    Bounds.expects(0 <= arg && arg < [&]() -> auto {
        if constexpr (std::is_signed_v<CPP2_TYPEOF(arg)>) { return std::ssize(x); }
        else { return std::size(x); }
    }(), "out of bounds access attempt detected" CPP2_SOURCE_LOCATION_ARG);
    return CPP2_FORWARD(x) [ CPP2_FORWARD(arg) ];
}

auto assert_in_bounds(auto&& x, auto&& arg CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT) -> decltype(auto)
{
    return CPP2_FORWARD(x) [ CPP2_FORWARD(arg) ];
}
```

to this:

```
auto assert_in_bounds_impl(auto&& x, auto&& arg CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT) -> void
    requires (std::is_integral_v<CPP2_TYPEOF(arg)> &&
             requires { std::size(x); std::ssize(x); x[arg]; std::begin(x) + 2; })
{
    Bounds.expects(0 <= arg && arg < [&]() -> auto {
        if constexpr (std::is_signed_v<CPP2_TYPEOF(arg)>) { return std::ssize(x); }
        else { return std::size(x); }
    }(), "out of bounds access attempt detected" CPP2_SOURCE_LOCATION_ARG);
}

auto assert_in_bounds_impl(auto&&, auto&& CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT) -> void
{
}

#define CPP2_ASSERT_IN_BOUNDS(x, arg) (cpp2::assert_in_bounds_impl((x),(arg)), (x)[(arg)])
```

Note that now the subscript is done outside the function, in the macro, where it doesn't need to be forwarded.

**Comment by JohelEGP** [comment]
```C++
#define CPP2_ASSERT_IN_BOUNDS(x, arg) (cpp2::assert_in_bounds_impl((x),(arg)), (x)[(arg)])
```
Now we're getting double evaluation of `x` and `arg`.

I noticed because I happened to not rebase well and this stopped working:
```Cpp2
(consume_parameter := call_operator.get_parameters()[1].name()) assert(consume_parameter == "consume");
```
`call_operator.get_parameters()` returns a vector of strings that's expensive to compute.

**Comment by JohelEGP** [comment]
Using UFCS similarly warns
when the target function expects a integer shorter than `int`
and we pass it a literal that promotes when going through the UFCS lambda.
See <https://cpp2.godbolt.org/z/3bKjPjze5>:
```Cpp2
to: (_: i8) = { }
main: () = {
  _ = 0.to();
}
```
```output
main.cpp2:3:21: warning: implicit conversion loses integer precision: 'int' to 'signed char' [-Wimplicit-int-conversion]
    3 |   static_cast<void>(CPP2_UFCS(to)(0));
      |                     ^~~~~~~~~~~~~
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:853:59: note: expanded from macro 'CPP2_UFCS'
  853 | #define CPP2_UFCS(...)                                    CPP2_UFCS_(&,(),,__VA_ARGS__)
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:849:55: note: expanded from macro 'CPP2_UFCS_'
  849 |         return CPP2_UFCS_REMPARENS QUALID __VA_ARGS__(CPP2_FORWARD(obj), CPP2_FORWARD(params)...); \
      |                                           ~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:272:37: note: expanded from macro 'CPP2_FORWARD'
  272 | #define CPP2_FORWARD(x)             std::forward<decltype(x)>(x)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp2:3:34: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<int>' requested here
    3 |   static_cast<void>(CPP2_UFCS(to)(0));
      |                                  ^
1 warning generated.
```

**Comment by JohelEGP** [comment]
> ```C++
> #define CPP2_ASSERT_IN_BOUNDS(x, arg) (cpp2::assert_in_bounds_impl((x),(arg)), (x)[(arg)])
> ```
> Now we're getting double evaluation of `x` and `arg`.

<https://github.com/hsutter/cppfront/issues/799#issuecomment-1791642256> points to the better direction.
`x is 5` already lowers to `cpp2::is<5>(x)`,
and the same can be done for indexing only when the index is a constant.

**Comment by hsutter** [comment]
Thanks @JohelEGP  -- does 4490a7d2ab74ee661c4c5dd060bab578ed1550a8 address your concerns while still addressing this issue?

**Comment by JohelEGP** [comment]
That looks much better, thank you.
