### ISSUE TITLE
[BUG] `cpp2util.h` should use `__cpp_lib_modules`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#800]
<a id="title"/>

**[T](#title)itle**: `cpp2util.h` should use `__cpp_lib_modules`.

<a id="desc"/>

**[D](#desc)escription**:

`cpp2util.h` uses `__cpp_modules` to decide whether to `import std;`.
But it should be using [`__cpp_lib_modules`](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#__cpp_lib_modules).

**Comment by hsutter** [comment]
Thanks!
