### ISSUE TITLE
[BUG] *template-head*s emit backwards

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#802]
<a id="title"/>

**[T](#title)itle**: *template-head*s emit backwards.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/YKM1xaojo>):

```Cpp2
t: @struct <T> type = {
  v: <U> bool == true;
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: `template<typename T> template <typename U> inline CPP2_CONSTEXPR bool t<T>::v = true;`.

<a id="actual"/>

**[A](#actual)ctual result and error**: `template<typename U> template <typename T> inline CPP2_CONSTEXPR bool t<T>::v = true;`.

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

template<typename T> class t;
  

//=== Cpp2 type definitions and function declarations ===========================

template<typename T> class t {
  public: template<typename U> static const bool v;
};
auto main() -> int;


//=== Cpp2 function definitions =================================================


  template<typename U> template <typename T> inline CPP2_CONSTEXPR bool t<T>::v = true;

auto main() -> int{}
```
</details>

<a id="out"/>
<details><summary>
<a href="#out">O</a>utput:
</summary>

```output
main.cpp2:2:79: error: nested name specifier 't<T>::' for declaration does not refer into a class, class template or class template partial specialization
    2 |   template<typename U> template <typename T> inline CPP2_CONSTEXPR bool t<T>::v = true;
      |                                                                         ~~~~~~^
1 error generated.
```
</details>

**Comment by hsutter** [comment]
Fixed, thanks!
