### ISSUE TITLE
[BUG] _using-statement_ at namespace/type scope ICEs

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#803]
<a id="title"/>

**[T](#title)itle**: _using-statement_ at namespace scope [ICE](https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ice)s.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/1hbrMMGr7>):

```Cpp2
ns: namespace = {
  using std::string;
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: For the _using-statement_ to work, just like the Cpp1 equivalent.

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a id="out"/>
<a href="#out">O</a>utput:

```output
cppfront: source/parse.h:3964: cpp2::source_position cpp2::statement_node::position() const: Assertion `!"illegal statement_node state"' failed.
Aborted (core dumped)
```

**Comment by JohelEGP** [comment]
Also at type scope: <https://cpp2.godbolt.org/z/6ee69vGrn>.

**Comment by hsutter** [comment]
Thanks! Adding at namespace scope (easy) and type scope (slightly more work because of delayed bases)...
