### ISSUE TITLE
[BUG] Support `_` unnamed template parameter.

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#812]
<a id="title"/>

**[T](#title)itle**: Support `_` unnamed template parameter.

<a id="desc"/>

**[D](#desc)escription**:

Commit 6ce2643e3ae7f91d0b21bc574fc321f7f015a466 added support only for function parameters.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/WY56cMoTd>):

```Cpp2
f: <_, _> (_, _) = { }
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**:

The template parameters to be named similar to the function parameters.

```C++
template<typename tparam1, typename tparam2> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void;
```

<a id="actual"/>

**[A](#actual)ctual result and error**:

```C++
template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void;
```

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"



//=== Cpp2 type definitions and function declarations ===========================

template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void;
auto main() -> int;


//=== Cpp2 function definitions =================================================

template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void{}
auto main() -> int{}
```
</details>

<a id="out"/>
<details><summary>
<a href="#out">O</a>utput:
</summary>

```output
build/main.cpp:12:31: error: declaration of '_' shadows template parameter
   12 | template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void;
      |                               ^
build/main.cpp:12:19: note: template parameter is declared here
   12 | template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void;
      |                   ^
build/main.cpp:18:31: error: declaration of '_' shadows template parameter
   18 | template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void{}
      |                               ^
build/main.cpp:18:19: note: template parameter is declared here
   18 | template<typename _, typename _> auto f([[maybe_unused]] auto const& param1, [[maybe_unused]] auto const& param2) -> void{}
      |                   ^
2 errors generated.
```
</details>

<a id="see"/>

**[S](#see)ee also**:

- Commit 6ce2643e3ae7f91d0b21bc574fc321f7f015a466.

**Comment by gregmarr** [comment]
I'm curious what the use case is for unused template parameters.  Is it for specializing an existing template?

**Comment by JohelEGP** [comment]
Compilers don't seem to warn on these.
But I have to invent names,
and maybe I'll run out of T, U, V, W, ???.
Of course, this mostly happens in tests.

**Comment by gregmarr** [comment]
Okay, thanks.

**Comment by hsutter** [comment]
Thanks!

**Comment by JohelEGP** [comment]
It doesn't work for [NTTP][]s: <https://cpp2.godbolt.org/z/rdb6dbvv1>.
Also, `<_...: _>` doesn't lower to a parameter pack declaration.
```Cpp2
t: @struct <_...: _> type = {
  f: <_: int> () -> i32 = 0;
}
main: () = { }
```
```C++
template<auto _> class t {
  public: template<int _> [[nodiscard]] static auto f() -> cpp2::i32;
};
```
```output
main.cpp2:2:24: error: declaration of '_' shadows template parameter
    2 |   public: template<int _> [[nodiscard]] static auto f() -> cpp2::i32;
      |                        ^
main.cpp2:1:15: note: template parameter is declared here
    1 | template<auto _> class t {
      |               ^
```
[ABI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#abi-api
[ADL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#adl
[CNTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cnttp
[CPO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cpo
[CRTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#crtp
[CTAD]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ctad
[WG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[SG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[EH]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#eh-tdeh
[HALO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#halo
[ICE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ice
[IFNDR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ifndr
[II]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#iile
[NSDMI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nsdmi
[NTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nttp
[ODR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#odr
[PIMPL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#pimpl
[QoI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#qoi
[RVO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#rvo-nrvo-urvo
[SBO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sbo-soo-sso
[SCARY]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#scary-iterators
[SFINAE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sfinae
[SMF]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#smf
[STL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#stl
[TMP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tmp
[TU]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tu
[UB]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ub
[UDL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#udl
[UFCS]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ufcs
