### ISSUE TITLE
[BUG] Ending a cpp1 string literal with a quoted backslash breaks compilation

### ISSUE THREAD

**Issue by serpent7776** [hsutter/cppfront#813]
**Describe the bug**
Valid cpp1 code is rejected by cppfront. There seem to be an issue with handling backslashes.

**To Reproduce**
1. Sample code - distilled down to minimal essentials please
```cpp
#include <string>

auto escape(char ch)
{
	std::string buf;
	switch (ch)
	{
		case '\\': buf += "\\\\"; break;
	}
	return buf;
}
```

3. Command lines including which C++ compiler you are using
```
cppfront compiler v0.3.0   Build 8B09:1419
built at 76c2941b29e1e17f8086d3581df03d0bb12bc793
```

4. Expected result - what you expected to happen
No compilation error.

5. Actual result/error
```
error: end of file reached with 2 missing } to match earlier { on lines 4 and 7
```

Somewhat related issue was reported here https://github.com/hsutter/cppfront/issues/732

**Comment by gregmarr** [comment]
The issue is specifically `...\\"`.  Adding a space and changing it to `...\\ "` makes the error not happen, so it's treating the `\"` as a quoted double quote, and not terminating the string constant.

**Comment by hsutter** [comment]
Thanks!
