### ISSUE TITLE
[BUG] `@enum<>` names the metafunction `enum>`

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#819]
<a id="title"/>

**[T](#title)itle**: `@enum<>` names the metafunction `enum>`.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/qY1rMnfG4>):

```Cpp2
engine: @enum<> type = {
  off;
  on;
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: A more clear diagnostic, or a working program.

<a id="actual"/>

**[A](#actual)ctual result and error**:

```output
main.cpp2...
main.cpp2(5,1): error: unrecognized metafunction name: enum>
main.cpp2(5,1): error: (temporary alpha limitation) currently the supported names are: interface, polymorphic_base, ordered, weakly_ordered, partially_ordered, copyable, basic_value, value, weakly_ordered_value, partially_ordered_value, struct, enum, flag_enum, union, print
```

**Comment by gregmarr** [comment]
To clarify, were you expecting `@enum<>` to work, and you want it to be equivalent to `@enum` or are you just reporting an error in the error message?

**Comment by JohelEGP** [comment]
Definitely the error.

I don't think `@enum<>` should work.
`@enum` wants a single argument, or none at all.

The current reflection API doesn't distinguish between
an empty template argument list and no argument list at all.
This even works (<https://cpp2.godbolt.org/z/rj6zeffWY>):
```Cpp2
engine: @enum<int,> type = {
  off;
  on;
}
main: () = { }
```
I don't know whether that's the same or a different bug.

**Comment by gregmarr** [comment]
> Definitely the error.

Thanks for the confirmation.  I thought that would be the case.

**Comment by hsutter** [comment]
Thanks! These were two more general errors, both with `unqualified_id` and its template argument list:

- For an empty `<>` template argument list, `unqualified_id_node::to_string` erroneously appended the `>` to the string. Now it doesn't.
- For a nonempty `<>` template argument list, the `unqualified_id()` parser function just ignored an empty trailing `,`. Now it diagnoses it.
