### ISSUE TITLE
[BUG] CPP2_UFCS macros don't work with template functions/methods with multiple template arguments

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#82]
CPP2_UFCS macro is based on variadic macros. That means that every comma `,` in the macro separates two arguments for the macro (unless surrounded by parentheses `()`.

That makes below the cpp2 code (mixed mode):
```cpp
#include <string>

template <auto from, auto to>
auto substr(const std::string& input) -> std::string {
    return input.substr(from, to-from);
}

main: () -> int = {
    test_string: std::string = "Unfortunatelly macros have limitations";
    cmd.substr<3,6>();
}
```
compiles to (skipping boilerplate):
```cpp
[[nodiscard]] auto main() -> int{
    std::string test_string { "Unfortunatelly macros have limitations" }; 
    CPP2_UFCS_0(substr<3,6>, test_string);
}
```
And a call to `CPP2_UFCS_0` will be perceived by the compiler as `CPP2_UFCS_0((substr<3),(6>), (test_string));` (parentheses added to emphasize the problem. That will not compile and will end up with an error:

```
clang++ -std=c++20 -Iinclude ../tests/ufcs-method-limitations.cpp 
tests/ufcs-method-limitations.cpp2:10:30: error: too many arguments provided to function-like macro invocation
    CPP2_UFCS_0(substr<3,6>, test_string);
                             ^
include/cpp2util.h:487:9: note: macro 'CPP2_UFCS_0' defined here
#define CPP2_UFCS_0(FUNCNAME,PARAM1) \
        ^
tests/ufcs-method-limitations.cpp2:10:5: error: use of undeclared identifier 'CPP2_UFCS_0'
    CPP2_UFCS_0(substr<3,6>, test_string);
    ^
2 errors generated.
```

A similar error will happen for `CPP2_UFCS` version - that reminds me why we hate macros so much.

Normally, in such cases, we would add parentheses to give hints to the preprocessor where are the arguments. In this case when we do it we will look like:
```cpp
CPP2_UFCS_0((substr<3,6>), test_string);
```
But it will also fail to compile with the error: `expected unqualified-id`:
```
clang++ -std=c++20 -Iinclude ../tests/ufcs-method-limitations.cpp 
tests/ufcs-method-limitations.cpp2:10:17: error: expected unqualified-id
    CPP2_UFCS_0((substr<3,6>), test_string);
                ^
tests/ufcs-method-limitations.cpp2:10:17: error: expected unqualified-id
error: constexpr if condition is not a constant expression
tests/ufcs-method-limitations.cpp2:10:5: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<std::string &>' requested here
    CPP2_UFCS_0((substr<3,6>), test_string);
    ^
include/cpp2util.h:494:2: note: expanded from macro 'CPP2_UFCS_0'
}(PARAM1)
 ^
3 errors generated.
```

Unless there is a trick to make that macro work again we will need to come up with some other idea to solve it.

I found that bug while trying to update the function call chaining PR (https://github.com/hsutter/cppfront/pull/18). Probably working UFCS will not be possible without semantic analysis on cppfront side.

The same will be needed to allow `Unified "." member/scope selection (e.g., std.swap(x,y))` - it is impossible to distinguish if `std` is a namespace by using `require` expressions or `decltype` hacks (already tried that).

**Comment by filipsajdak** [comment]
I have tried some tricks with expanding macros and packing `FUNCNAME` into an additional macro:
```cpp
#define CPP2_EXPAND(...) CPP2_E(__VA_ARGS__)
#define CPP2_E(...) __VA_ARGS__

#define CPP2_UFCS_FUNCNAME(...) CPP2_EXPAND __VA_ARGS__

#define CPP2_UFCS_0(FUNCNAME,PARAM1) \
[](auto&& obj) { \
    if constexpr (requires{ std::forward<decltype(obj)>(obj).CPP2_UFCS_FUNCNAME(FUNCNAME)(); }) { \
        return std::forward<decltype(obj)>(obj).CPP2_UFCS_FUNCNAME(FUNCNAME)(); \
    } else { \
        return CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward<decltype(obj)>(obj)); \
    } \
}(PARAM1)
```
and I have manually edit generated code to:
```cpp
CPP2_UFCS_0((substr<3,6>), test_string);
```

That ends up with another error:
```
clang++ -std=c++20 -Iinclude ../tests/ufcs-method-limitations.cpp 
tests/ufcs-method-limitations.cpp2:10:18: error: missing 'template' keyword prior to dependent template name 'substr'
    CPP2_UFCS_0((substr<3,6>), test_string);
                 ^     ~~~~~
include/cpp2util.h:494:81: note: expanded from macro 'CPP2_UFCS_0'
    if constexpr (requires{ std::forward<decltype(obj)>(obj).CPP2_UFCS_FUNCNAME(FUNCNAME)(); }) { \
                                                                                ^~~~~~~~
include/cpp2util.h:490:45: note: expanded from macro 'CPP2_UFCS_FUNCNAME'
#define CPP2_UFCS_FUNCNAME(...) CPP2_EXPAND __VA_ARGS__
                                            ^~~~~~~~~~~
include/cpp2util.h:487:33: note: expanded from macro 'CPP2_EXPAND'
#define CPP2_EXPAND(...) CPP2_E(__VA_ARGS__)
                                ^~~~~~~~~~~
include/cpp2util.h:488:21: note: expanded from macro 'CPP2_E'
#define CPP2_E(...) __VA_ARGS__
                    ^~~~~~~~~~~
tests/ufcs-method-limitations.cpp2:10:18: error: missing 'template' keyword prior to dependent template name 'substr'
    CPP2_UFCS_0((substr<3,6>), test_string);
                 ^     ~~~~~
include/cpp2util.h:495:68: note: expanded from macro 'CPP2_UFCS_0'
        return std::forward<decltype(obj)>(obj).CPP2_UFCS_FUNCNAME(FUNCNAME)(); \
                                                                   ^~~~~~~~
include/cpp2util.h:490:45: note: expanded from macro 'CPP2_UFCS_FUNCNAME'
#define CPP2_UFCS_FUNCNAME(...) CPP2_EXPAND __VA_ARGS__
                                            ^~~~~~~~~~~
include/cpp2util.h:487:33: note: expanded from macro 'CPP2_EXPAND'
#define CPP2_EXPAND(...) CPP2_E(__VA_ARGS__)
                                ^~~~~~~~~~~
include/cpp2util.h:488:21: note: expanded from macro 'CPP2_E'
#define CPP2_E(...) __VA_ARGS__
                    ^~~~~~~~~~~
error: constexpr if condition is not a constant expression
tests/ufcs-method-limitations.cpp2:10:5: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<std::string &>' requested here
    CPP2_UFCS_0((substr<3,6>), test_string);
    ^
include/cpp2util.h:499:2: note: expanded from macro 'CPP2_UFCS_0'
}(PARAM1)
 ^
3 errors generated.
```

**Comment by ljleb** [comment]
This may be a dirty solution but we could define a macro (i.e. `CPP2_COMMA`) that expands to the comma `,` and replace template arguments comma separators in the generated cpp1 code.

```cpp
#define CPP2_COMMA ,
```

For example this
```cpp
    cmd.substr<3,6>()
```

would generate this code:
```cpp
    CPP2_UFCS_0(substr<3 CPP2_COMMA 6>, test_string);
```

In my opinion this is not a clean solution as it makes the output less readable when using dot syntax between functions and/or expressions taking multiple template parameters. Though as it seems it would work, I thought it was worth mentioning.

**Comment by ljleb** [comment]
Using a pointer to member function seems to compile fine on all major compilers. It doesn't seem ideal though, as it still warns about the `template` keyword missing.

```cpp
#define CPP2_EXPAND(...) CPP2_E(__VA_ARGS__)
#define CPP2_E(...) __VA_ARGS__

#define CPP2_UFCS_FUNCNAME(...) CPP2_EXPAND __VA_ARGS__

#define CPP2_UFCS_0(FUNCNAME,PARAM1) \
[](auto&& obj) { \
    if constexpr (requires{ decltype(obj)::CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward<decltype(obj)>(obj)); }) { \
        return decltype(obj)::CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward<decltype(obj)>(obj)); \
    } else { \
        return CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward<decltype(obj)>(obj)); \
    } \
}(PARAM1)
```

[compiler explorer link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:28,positionColumn:1,positionLineNumber:28,selectionStartColumn:1,selectionStartLineNumber:28,startColumn:1,startLineNumber:28),source:'%23define+CPP2_EXPAND(...)+CPP2_E(__VA_ARGS__)%0A%23define+CPP2_E(...)+__VA_ARGS__%0A%0A%23define+CPP2_UFCS_FUNCNAME(...)+CPP2_EXPAND+__VA_ARGS__%0A%0A%23define+CPP2_UFCS_0(FUNCNAME,PARAM1)+%5C%0A%5B%5D(auto%26%26+obj)+%7B+%5C%0A++++if+constexpr+(requires%7B+decltype(obj)::CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward%3Cdecltype(obj)%3E(obj))%3B+%7D)+%7B+%5C%0A++++++++return+decltype(obj)::CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward%3Cdecltype(obj)%3E(obj))%3B+%5C%0A++++%7D+else+%7B+%5C%0A++++++++return+CPP2_UFCS_FUNCNAME(FUNCNAME)(std::forward%3Cdecltype(obj)%3E(obj))%3B+%5C%0A++++%7D+%5C%0A%7D(PARAM1)%0A%0A%23include+%3Cstring%3E%0A%0Atemplate+%3Cauto+from,+auto+to%3E%0Aauto+substr(const+std::string%26+input)+-%3E+std::string+%7B%0A++++return+input.substr(from,+to-from)%3B%0A%7D%0A%0Aint+main()%0A%7B%0A++++std::string+test_string+%7B+%22Unfortunatelly+macros+have+limitations%22+%7D%3B+%0A++++CPP2_UFCS_0((substr%3C3,6%3E),+test_string)%3B%0A++++return+0%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:39.35353476324924,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'--std%3Dc%2B%2B20',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+(trunk)+(Editor+%231)',t:'0')),k:27.313131903417432,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86+msvc+v19.latest',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+(trunk)+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

I haven't tested this thoroughly but maybe a starting point?

**Comment by hsutter** [comment]
Thanks everyone...  In the meantime I think it's probably enough of a corner case that we don't need to block other progress on this, so until we have a solution that works, I think the simplest is to just not emit UFCS in the multi-template-arg case that doesn't work with the macro. I'll commit that workaround now as an alpha limitation, but please do reopen this (or create a new issue or PR) if you have a better solution that makes it work!

**Comment by filipsajdak** [comment]
I have found a solution for handling methods with variadic number of arguments - included here: https://github.com/hsutter/cppfront/pull/169#issuecomment-1359292705
