### ISSUE TITLE
[BUG] Interpolation lowers unparenthesized

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#828]
<a id="title"/>

**[T](#title)itle**: Interpolation lowers unparenthesized.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/nzzPsq8n6>):

```Cpp2
main: () = {
  "`(0)$`".clear();
}
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: ``  CPP2_UFCS_0(clear, ("`" + cpp2::to_string(0) + "`"));``

<a id="actual"/>

**[A](#actual)ctual result and error**: ``  "`" + cpp2::to_string(0) + CPP2_UFCS_0(clear, "`");``

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++

#define CPP2_USE_SOURCE_LOCATION Yes

//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"



//=== Cpp2 type definitions and function declarations ===========================

auto main() -> int;
  

//=== Cpp2 function definitions =================================================

auto main() -> int{
  "`" + cpp2::to_string(0) + CPP2_UFCS_0(clear, "`");
}
```
</details>

<a id="out"/>
<details><summary>
<a href="#out">O</a>utput:
</summary>

```output
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:470:44: warning: unused parameter 'where' [-Wunused-parameter]
  470 | auto assert_in_bounds(auto&& x, auto&& arg CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT) -> decltype(auto)
      |                                            ^
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:369:76: note: expanded from macro 'CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT'
  369 |     #define CPP2_SOURCE_LOCATION_PARAM_WITH_DEFAULT , std::source_location where = std::source_location::current()
      |                                                                            ^
build/main.cpp:19:42: error: use of undeclared identifier 'clear'
   19 |   "`" + cpp2::to_string(0) + CPP2_UFCS_0(clear, "`");
      |                                          ^
build/main.cpp:19:30: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<const char (&)[2]>' requested here
   19 |   "`" + cpp2::to_string(0) + CPP2_UFCS_0(clear, "`");
      |                              ^
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:797:2: note: expanded from macro 'CPP2_UFCS_0'
  797 | }(PARAM1)
      |  ^
1 warning and 1 error generated.
```
</details>

[ABI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#abi-api
[ADL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#adl
[CNTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cnttp
[CPO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cpo
[CRTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#crtp
[CTAD]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ctad
[WG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[SG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[ICE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ice
[IFNDR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ifndr
[II]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#iile
[NSDMI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nsdmi
[NTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nttp
[ODR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#odr
[PIMPL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#pimpl
[QoI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#qoi
[RVO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#rvo-nrvo-urvo
[SBO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sbo-soo-sso
[SCARY]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#scary-iterators
[SFINAE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sfinae
[SMF]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#smf
[STL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#stl
[TMP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tmp
[TU]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tu
[UB]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ub
[UDL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#udl
[UFCS]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ufcs

**Comment by JohelEGP** [comment]
I have always thought that interpolation should use `absl::concat`.
That would fix the problem.

**Comment by hsutter** [comment]
Thanks! I might do something similar to `absl::StrCat` in the future, without an Abseil dependency.

**Comment by JohelEGP** [comment]
Thank you!
I find discovered this issue
when I used one of those functions to color strings (from <https://github.com/hsutter/cppfront/pull/831#discussion_r1428697003>)
and noticed that only a latter part of the string was colored.

**Comment by JohelEGP** [comment]
Commit 13826c5b52c553d8f3221ba3d82f19b33e8698a9 regressed
commit acab5c3f185597c290f1fac998799ddac94512e (which didn't add a test).
