### ISSUE TITLE
Error: local variable is not used, but in fact it is

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#832]
The transpiler emits "error: local variable is not used", but in fact it is used.

Compiling

<pre>
main: () = {
  b := true;
  i := 0;
  while i &lt; 3 &amp;&amp; b next i++ {
    std::cout &lt;&lt; i &lt;&lt; std::endl;
  }
}
</pre>

yields

<pre>
whiles.cpp2(2,3): error: local variable b is not used; consider changing its name to '_' to make it explicitly anonymous, or removing it entirely if its side effects are not needed
</pre>

This happens at least since git version <kbd>11f2dbb</kbd>.

**Comment by gregmarr** [comment]
This check was added in https://github.com/hsutter/cppfront/commit/243d03d3fd9608e0e76ddcbe8decfef9deb5ebdf

**Comment by JohelEGP** [comment]
Same for the reproducer of #825.
I'm explicitly discarding them!

**Comment by JohelEGP** [comment]
The reproducer of #825 has 3 similar variants:
```Cpp2
  _ = :(copy b) _ = b;        // Doesn't move.
  for args do (copy c) _ = c; // Doesn't move.
f: (copy x) _    = x; // Moves.
```
Only the parameter of the function expression is diagnosed.
The parameter of both the `for` body and the function are equally local.
It seems inconsistent to diagnose the first one but not the other two.

**Comment by JohelEGP** [comment]
It also rejects this case, called out by the commit message.
```Cpp2
        (copy count := 0)
        while !ret.emplace_back(get_argument(count)).empty() next count++ { }
```

**Comment by JohelEGP** [comment]
This case is accepted if you don't use UFCS (<https://cpp2.godbolt.org/z/jYr1cEqfd>):
```Cpp2
perfects: @struct type = {
  operator(): (this, copy consume) = {
    i:=0;
    // consume(i); // Works.
    i.consume();
  }
}
main: () = { }
```
