### ISSUE TITLE
Inconsistent use of curly braces

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#834]
In a single statement function

<pre>
a: () -&gt; int =
  13;

b: () -&gt; int = {
  return 42;
}
</pre>

and in a for-loop with only one statement

<pre>
v: vector = (1, 2, 3, 4, 5);
for v do (i) {
  print("(i)$ ");
}
println();
for v do (i)
  print("(i)$ ");
println();
</pre>

curly braces are optional.

<p>
But for if
<pre>
b:= true;
if b {
  println("b is true");
} else {
  println("b is false");
}
</pre>

and while

<pre>
v := :vector = (1, 2, 3, 4, 5);
i := 0U;
while i &lt; v.size() next i++ {
  print("(v[i])$ ");
}
println();
</pre>

curly braces are mandatory. This seems inconsistent to me. Or do I miss something?

**Comment by JohelEGP** [comment]
See the thread at <https://github.com/hsutter/cppfront/commit/26a4cbfe0a34b090863487b397925410d912408d#r128455814>:
> Right, that comments should only have mentioned `while` loops, which have the same introductory structure as `if` conditions in that the condition and the body can be grammatically adjacent.
>
> Braces aren't required around `for` loop bodies.
>
> And they happen to be required around `do` loop bodies, but in that case it's not for the reason that a conditional could be ambiguous/confusion, since the body isn't adjacent to a conditional expression. There it's just for readability taste reasons.

**Comment by wolfseifert** [comment]
Closing as duplicate of https://github.com/hsutter/cppfront/commit/26a4cbfe0a34b090863487b397925410d912408d#r128455814.
