### ISSUE TITLE
Ternary operators and if expressions

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#835]
There does not seem to exist a ternary operator <code>a ? b : c</code> in Cpp2.

<p>
Possible solution: make <code>if a { b } else { c }</code> an expression (as <code>inspect</code>).

**Comment by AbhinavK00** [comment]
You can find a related discussion at #757

**Comment by wolfseifert** [comment]
Closing in favour of https://github.com/hsutter/cppfront/discussions/757.
