### ISSUE TITLE
[BUG] `@print` shortcomings

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#840]
<a id="title"/>

**[T](#title)itle**: Single-expression functions print with extra semicolon.

<a id="desc"/>

**[D](#desc)escription**:

This makes the printed code invalid Cpp2:
```output
example.cpp2(4,51): error: a single-expression function should end with a single semicolon (at ';')
```

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/jGb31dK74>):

```Cpp2
#include <functional>
t: @struct @print type = {
  x: std::function<void()> = :() = _ = 0;
  y: std::function<void()> = :() 0;
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: Printed Cpp2 code to be valid.

<a id="actual"/>

**[A](#actual)ctual result and error**: `public x: std::function<void()> = :() = _ = 0;;`.

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"


class t;
  

//=== Cpp2 type definitions and function declarations ===========================

#include <functional>
class t {
  public: std::function<void()> x {[]() -> void { static_cast<void>(0);  }}; 
  public: std::function<void()> y {[]() -> auto { return 0;  }}; 
};
auto main() -> int;

//=== Cpp2 function definitions =================================================


auto main() -> int{}
```
</details>

<a id="out"/>
<details><summary>
<a href="#out">O</a>utput:
</summary>

```output
main.cpp2...

t: type = 
{
    public x: std::function<void()> = :() = _ = 0;;

    public y: std::function<void()> = :() -> move _ = 0;;
}
 ok (mixed Cpp1/Cpp2, Cpp2 code passes safety checks)

```
</details>

<a id="see"/>

**[S](#see)ee also**:

- #479.

**Comment by JohelEGP** [comment]
This is #479's test:
```Cpp2
u: @struct @print type = {
  t: type = {
    operator[]: (this, f) = {}
  }

  main: () -> int = {
    (x := t()) { x[:() -> _ = 0]; }
    (x := t()) { x[:() -> _ = 0;]; }

    assert(!(:() = 0; is int));

    _ = :i32 = 0;
    assert(true);

    return :i32 = 0;
  }

  a: i32 == :i32 = 0;
  b: i32 = 0;
}

main: () = {}
```
What it prints:
```Cpp2
u: type = {
  public t: type = {
    operator[]: (in this, in f: ) = {}
  }

  public main: () -> move int = {
    (in x := t()) { x[:() -> move _ = 0]; }
    (in x := t()) { x[:() -> move _ = 0;]; }
    assert(!(:() = 0; is int))
    _ = :i32 = 0;
    ;
    assert(true)
    return :i32 = 0;
    ;
  }

  public a: i32 == :i32 = 0;
  ;

  public b: i32 = 0;
}

```
And where the errors are at:
```Cpp2
u: type = {
  public t: type = {
    operator[]: (in this, in f: ) = { }
  }

  public main: () -> move int = {
    (in x := t()) { x[:() -> move _ = 0]; }
    (in x := t()) { x[:() -> move _ = 0;]; }
    assert(!(:() = 0; is int)); // Added ';'.
    _ = :i32 = 0;               // x.cpp2(10,5): error: missing ';' after contract-statement (at '_')
    // ;                        // x.cpp2(11,5): error: empty statement is not allowed - remove extra semicolon (at ';')
    assert(true);    // Added ';'.
    return :i32 = 0; // x.cpp2(13,5): error: missing ';' after contract-statement (at 'return')
    // ;             // x.cpp2(14,5): error: empty statement is not allowed - remove extra semicolon (at ';')
  }

  public a: i32 == :i32 = 0;
  // ; // x.cpp2(18,3): error: empty statement is not allowed - remove extra semicolon (at ';')

  public b: i32 = 0;
}
```
- `assert`s need `;`.
- Statements ending in `;` need to remove any extra `;`.

**Comment by JohelEGP** [comment]
Also, deduced type parameters lower with `:` but without a type/placeholder.
And function expressions in initializers of `constexpr` variables have an extra line break.
See <https://cpp2.godbolt.org/z/aoY3zqEW7>.
```Cpp2
t: @struct @print type = {
  i: int == :(_) 0;(0);
}
main: () = { }
```
```Cpp2
t: type = 
{
    public i: int == 
:(in _:) -> move _ = 0;(0);
}
```

**Comment by JohelEGP** [comment]
`@struct`s print without `@struct`,
so they can be invalid Cpp2
and be interpreted by the user wrongly.

`@struct` is doesn't generate Cpp2 code,
but instead affects lowering.
So it should be `@print`ed.

**Comment by AbhinavK00** [comment]
Very sorry for the questions but what does `print` metafunction do? Also, is it confirmed that multiple metafunctions can be applied on the same type?

**Comment by JohelEGP** [comment]
For `@print`, when you use it, like at <https://github.com/hsutter/cppfront/commit/586ff200ce68099c1577937e02f5174e311a7a04#diff-4ccd4b8a84887f1aadc839722d871182e36bd2a986f4bae0dfa9edfdfe1a3952>,
`cppfront` will pretty-print it during compilation: <https://github.com/hsutter/cppfront/commit/586ff200ce68099c1577937e02f5174e311a7a04#diff-86374c72ff7e9b814ef80bc78f78f4cac4189bf2b4fbb78be253303ff4ee9d4b>.
It can be useful to see what a metafunction generates.
For example, see <https://github.com/hsutter/cppfront/issues/821#issuecomment-1809530971>.

Yes, metafunctions form a pipeline: <https://github.com/hsutter/cppfront/issues/447#issuecomment-1547791927>.

**Comment by AbhinavK00** [comment]
Thanks for the answer!

**Comment by hsutter** [comment]
Thanks!

I _think_ I got them all, including the ones in your test cases and a few more... but please check and reopen with a new test case if I missed some.

**Comment by JohelEGP** [comment]
Thank you.
How about <https://github.com/hsutter/cppfront/issues/840#issuecomment-1817546271>?
> `@struct`s print without `@struct`,
> so they can be invalid Cpp2
> and be interpreted by the user wrongly.
> 
> `@struct` doesn't generate Cpp2 code,
> but instead affects lowering.
> So it should be `@print`ed.

**Comment by hsutter** [comment]
> `@struct` doesn't generate Cpp2 code,
> but instead affects lowering.
> So it should be `@print`ed.

Good point, that's the simplest fix for now so I'll implement it that way. Thanks!

**Comment by JohelEGP** [comment]
With program-defined metafunctions (#907), that can be generally true for all metafunctions.
So it might be better if the pretty print visualizer could print processed metafunctions in a C comment.
