### ISSUE TITLE
[SUGGESTION] Make `out` the default for `operator=`

### ISSUE THREAD

**Issue by Pollux42** [hsutter/cppfront#845]
As `in` is the implicit default for `this` in type-scope functions, and since `in` can't be used for `operator=` functions, `out` could be the implicit default for `this`.

It would let us write (among other occurences)
```
operator=: (this, that)
```

Which the simplest and the most generalisable constructor (construction+assignment/copy+move)

**Will your feature suggestion _automate or eliminate_ X% of current C++ guidance literature?**
Not sure about that, but I think it comes with the same kind of benefit than using implicit `in` for `this` in other type-scope functions.

**Comment by msadeqhe** [comment]
`operator=` can have `inout this` parameter too (in this case it will be for both construction and assignment). So `inout this` may be the implicit default, although it will be different to other functions in which `in` is the implicit default.

**Comment by Pollux42** [comment]
> `operator=` can have `inout this` parameter too (in this case it will be for both construction and assignment). So `inout this` may be the implicit default, although it will be different to other functions in which `in` is the implicit default.

No, `inout this` is for assignment only as it requires an initialized `this`.
It's precisely `out this` that works for both construction and assignment, as it's a natural constructor and can also work for the assignment (unless a more specialized `inout this` assignment operator is defined).

**Comment by JohelEGP** [comment]
Since `operator=` is so fundamental, and many users will be writing it,
I think it would be detrimental for it to suggest that the default isn't `in`.

**Comment by AbhinavK00** [comment]
Defaults are good as long as they're same everywhere. This change is not, so I don't think it should happen. While I do understand the reasoning, I would still put consistency throughout the langauage as a higher priority. Having different defaults (as with lambdas in cpp2) is just one more thing to teach, although not a big one.

**Comment by gregmarr** [comment]
I'm on the fence here.  On one hand, the current default isn't usable for this type of function, so having a different usable default makes sense.  On the other hand, having a different default here makes things less consistent.  On the third hand (we all have one of those, right?) there are different defaults for the implicit return type for named and unnamed functions.

**Comment by Pollux42** [comment]
Thank for your feedback.

Indeed, there will be multiple defaults depending on the context. But I don't think it's an issue. I mean I don't think it give something more to teach.
Actually, If we consider this is something new to teach, so every implicit default should also be something more to teach, but we are still happy with good defaults because it let us omit things when it's the most common or the most secure. (such as default parameter, default access specifier, ...)

1. `private` is the default access specifier for `class` wheras `public` is for `struct`.
2. `in` is a default access parameter for member functions whereas `out` could be the default for `operator=`.

I know that in case 1, the default would be opt-in thanks to metaclasses, but I think it does not change anything tp the point

We can take it the opposite way:
We have `in` as default access parameter, but `in` is not legible for `operator=` so there is room for a default here.
Said differently, `operator=` has no default access parameter. It's not an issue, but `out` could be a useful one as it would be the most common case.

**Comment by JohelEGP** [comment]
> On the third hand (we all have one of those, right?) there are different defaults for the implicit return type for named and unnamed functions.

That's wrong, see <https://github.com/hsutter/cppfront/wiki/Design-note%3A-Defaults-are-one-way-to-say-the-same-thing>.

**Comment by AbhinavK00** [comment]
That design note does not mention terse lambdas where the defaults ARE different. Anonymous functions and named functions do have the same default in cpp2 but the terse syntax does not.

**Comment by JohelEGP** [comment]
It's there:

> To me, allowing a generic function `f:(i:_) -> _ = { return i+1; }` to be spelled `f:(i) i+1;` is like that... there's only one way to spell it, but you get to omit parts where you're happy with the defaults. And that's especially useful when writing functions at expression scope (aka lambdas), such as examples like these:

**Comment by AbhinavK00** [comment]
I'm very sorry for missing that. And yes while in the example, it looks like defaults are good, the inconsistency becomes visible when another example is considered. 

```
f : (i) i+1; //works, deduced return type
f : (i) = i+1;  //void return type
```

This is an accepted inconsistency.

**Comment by JohelEGP** [comment]
The second one is an error.
More at <https://github.com/hsutter/cppfront/discussions/714#discussioncomment-7278362>.

**Comment by AbhinavK00** [comment]
Sorry for that, I checked it on compiler explorer and it worked. But it being an error is still inconsistent. Yes, the discussion happened before and that's why I said it's an accepted inconsistency.

**Comment by gregmarr** [comment]
Sorry, I was mis-remembering, it's not named vs. unnamed, though that was discussed, it's unspecified return vs explicitly deduced return vs terse.

      f1:(i) -> _ = { return i + 1; } // deduced return
    //f2:(i) = { return i + 1; } // unspecified return (void, error)
      f3:(i) = { i + 1; } // unspecified return (void)
      f4:(i) i + 1; // deduced return

If you don't specify the return type in a function declaration, it's `void`.  However, if you are declaring a generic function, you get to omit parts where you're happy with the defaults, namely `-> _ = { return ... ; }`.

If you don't specify the parameter passing type in a function declaration, it's `in`.  However, if you are declaring `operator=`, you get to omit parts where you're happy with the defaults, namely the `out` on this.

**Comment by gregmarr** [comment]
@Pollux42 

>private is the default access specifier for class wheras public is for struct.

FYI, Cpp2 has neither of those.  "All you need is type." (see Herb's CppCon 2023 presentation) If I'm remembering correctly (need to get those docs going...), by default, data members are private and functions are public.

**Comment by msadeqhe** [comment]
I think discussion #626 has to be considered here too. IMO If the plan is to unify return values and `out` parameters, we shouldn't make `out this` to be the default in `operator=`.

**Comment by hsutter** [comment]
Thanks for the discussion here. My sense is that I like that `operator=` has to explicitly say `out` (or `inout`, or `move`) to emphasize that it's a constructor. Recall that any `out` parameter de facto operators as a constructor (though in non-`this` cases as effectively a delegating constructor since it doesn't have private access). So it's consistent that `out this` is a constructor for this. I think that should be emphasized, and not only isn't it worth saving the three characters but I think it's a loss to omit the three characters and another thing to remember.

I'll close this for now, but feel free to reopen if you feel there's something important I haven't considered. Again, thanks for the discussion!
