### ISSUE TITLE
[BUG] `operator:` not rejected by cppfront

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#846]
<a id="title"/>

**[T](#title)itle**: `operator:` not rejected by cppfront.

<a id="desc"/>

**[D](#desc)escription**:

This is a case of missing parentheses.
That is, writing
`operator: () = { }` instead of
`operator(): () = { }`.
The Cpp1 error messages do include `()`
(except GCC when the parameter list isn't empty),
so it's not immediately obvious what's wrong.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/q1bqM4e6o>):

```Cpp2
t: @struct type = {
  operator: () = { }
}
main: () = { }
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: A diagnostic that `operator` isn't a valid declaration identifier.

```C++

```

<a id="actual"/>

**[A](#actual)ctual result and error**:

<a id="cpp1"/>
<details><summary>
<a href="#cpp1">C</a>pp2 lowered to Cpp1:
</summary>

```C++


//=== Cpp2 type declarations ====================================================


#include "cpp2util.h"

#line 1 "/app/example.cpp2"
class t;
#line 2 "/app/example.cpp2"
  

//=== Cpp2 type definitions and function declarations ===========================

#line 1 "/app/example.cpp2"
class t {
#line 2 "/app/example.cpp2"
  public: static auto operator() -> void;
};
auto main() -> int;

//=== Cpp2 function definitions =================================================

#line 1 "/app/example.cpp2"

#line 2 "/app/example.cpp2"
  auto t::operator() -> void{}

auto main() -> int{}
```
</details>

<a id="out"/>
<a href="#out">O</a>utput:

```output
main.cpp2:2:23: error: 'operator()' cannot be the name of a variable or data member
    2 |   public: static auto operator() -> void;
      |                       ^
main.cpp2:2:33: error: expected ';' at end of declaration list
    2 |   public: static auto operator() -> void;
      |                                 ^
      |                                 ;
main.cpp2:2:11: error: 'operator()' cannot be the name of a variable or data member
    2 |   auto t::operator() -> void{}
      |           ^
main.cpp2:2:21: error: expected ';' after top level declarator
    2 |   auto t::operator() -> void{}
      |                     ^
      |                     ;
4 errors generated.
```

**Comment by hsutter** [comment]
Thanks! Sorry for the delay as I'm finally catching up on more of the backlog of reports. Now fixed.
