### ISSUE TITLE
[BUG] Initialization violation not caught

### ISSUE THREAD

**Issue by AbhinavK00** [hsutter/cppfront#852]
**Describe the bug**
Unitialised variable passed to an `inout` function while marking it as `out` is not caught as an error.

**To Reproduce**
```cpp
f : (inout a: i32) = {
    std::cout << a;
}

main : () = {
    v : i32;
    f(out v);
}
```

**Additional context**
Generated Code with useless parts omitted.

```cpp
auto f(cpp2::i32& a) -> void{
    std::cout << a;
}

auto main() -> int{
    cpp2::deferred_init<cpp2::i32> v; 
    f(cpp2::out(&v));
}
```

Also, for someone reason it also doesn't suggest me to change the parameter to `in`. 
I tested this on compiler explorer so apologies if this has been fixed and compiler explorer is behind on versions.

**Comment by JohelEGP** [comment]
Well, it is caught by the Cpp1 compiler (<https://cpp2.godbolt.org/z/abcrhvMEz>):
```output
main.cpp2:7:5: error: no matching function for call to 'f'
    7 |     f(cpp2::out(&v));
      |     ^
main.cpp2:1:6: note: candidate function not viable: no known conversion from 'cpp2::out<int>' to 'cpp2::i32 &' (aka 'int &') for 1st argument
    1 | auto f(cpp2::i32& a) -> void{
      |      ^ ~~~~~~~~~~~~
1 error generated.
```
I don't think you can do that in cppfront.

**Comment by AbhinavK00** [comment]
I see. I'll close this then.
