### ISSUE TITLE
[BUG] sizeof...(Args) is compiled incorrectly

### ISSUE THREAD

**Issue by nlbuescher** [hsutter/cppfront#859]
**Describe the bug**

Using an `if constexpr` to determine how many parameters have been passed into the function is not possible because `sizeof...(Args)` is turned into `sizeof(Args)...`, which does not compile.

**To Reproduce**

```cpp2
function: <Args...> (forward args...: Args) = {
    if constexpr sizeof...(Args) > 0 as size_t {
        // do one thing
    }
    else {
        // do another thing
    }
    function(args...);
}
```

The `sizeof...(Args)` should be left untouched and compute the number of arguments passed to the function at compile time. Instead:

Generated C++ code:

```cpp
#line 1 "main.cpp2"
template<typename ...Args> auto function(Args&& ...args) -> void{
#line 2 "main.cpp2"
    if constexpr (cpp2::cmp_greater(sizeof(Args)...,cpp2::as_<size_t, 0>())) {
        // do one thing
    }
    else {
        // do another thing
    }
    std::cout << CPP2_FORWARD(args)... << '\n';
}
```

![изображение](https://github.com/hsutter/cppfront/assets/2711898/63d7e798-0954-4124-9240-434bc72bdb05)

As an added bonus, as can be seen, the error message emitted by the compiler makes no sense because of the reordering.

**Comment by JohelEGP** [comment]
This is #773.

**Comment by hsutter** [comment]
Fixed, thanks!
