### ISSUE TITLE
[BUG] Digit separator doesn't parse

### ISSUE THREAD

**Issue by JohelEGP** [hsutter/cppfront#862]
<a id="title"/>

**[T](#title)itle**: Digit separator doesn't parse.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/Pn4zd7MeM>):

```Cpp2
niam: () = { _ = 0'1; } // Not OK.
main: () = {
  _ = 0'1; // OK
}
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -Werror=unused-value -Werror=unused-parameter -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: Both to work.

<a id="actual"/>

**[A](#actual)ctual result and error**:

```output
main.cpp2...
main.cpp2(5,0): error: end of file reached with 1 missing } to match earlier { on line 1
```

**Comment by hsutter** [comment]
Yup, that was the offending line. Thanks!
