### ISSUE TITLE
[BUG] Cppfront reports incorrect errors when a multi-statement function has no enclosing braces

### ISSUE THREAD

**Issue by bluetarpmedia** [hsutter/cppfront#946]
**Describe the bug**
Cppfront reports an incorrect error when parsing an ill-formed multi-statement function missing its enclosing braces.

**To Reproduce**
Run cppfront on this ill-formed code:
```
func: () =
    message := "Hello world\n";
    std::cout << message;
```
[Godbolt](https://cpp2.godbolt.org/z/ax3KjaMo8)

Cppfront reports: `error: local variable message is not used; consider changing its name to '_' to make it explicitly anonymous, or removing it entirely if its side effects are not needed`

Another:
```
func: () =
    std::cout << "Hello ";
    std::cout << " world\n";
```
[Godbolt](https://cpp2.godbolt.org/z/Tnnodv57a)

Cppfront reports: `error: pure-cpp2 switch disables Cpp1 syntax`

But in these cases I'd expect a syntax error indicating the block is missing.

**Comment by JohelEGP** [comment]
They both look correct to me.
The last line is Cpp1.
So in the first case, the local really is unused.
And in the second case, there is Cpp1 code.

**Comment by bluetarpmedia** [comment]
For context, I was playing with the `pure2-main-args.cpp2` regression test, which looks like this:
```
main: (args) =
    std::cout
        << "args.argc            is (args.argc)$\n"
        << "args.argv[0]         is (args.argv[0])$\n"
        ;
```
And I added a local variable at the top:
```
main: (args) =
    message:= "Hello world\n";
    std::cout << message;
    std::cout
        << "args.argc            is (args.argc)$\n"
        << "args.argv[0]         is (args.argv[0])$\n"
        ;
```
And then received the error about `message` being unused, which confused me until I realized the block was missing.

**Comment by hsutter** [comment]
Right, at the end of a top-level Cpp2 declaration, if there isn't the start of another Cpp2 declaration we assume it's Cpp1 code and switch back to Cpp1 code. To give a different error on that would require a more fundamental change to how we recognize Cpp1/Cpp2 code which is the earliest stage of processing.

However, if it's nested inside a Cpp2 region such as a namespace, you do get a better error already:

```
ns: namespace = {
    func: () =
        std::cout << "Hello";
        std::cout << "world";
}
```

This program currently gives this error, which I think is fairly decent:

```
demo.cpp2(4,9): error: a namespace scope must contain only declarations or 'using' statements, not other code
```

But with the above commit, it now gives this better message:

```
demo.cpp2(4,9): error: in this scope, a single-statement function body cannot be immediately followed by a statement - did you forget to put { } braces around a multi-statement function body?
```

Again, this only fires if it's not a global function.

**Comment by JohelEGP** [comment]
> Is there any risk to parsing one more statement to diagnose this?

Well, there was, for #907.

```Cpp2
x: ()      = y;
z: @w type = { }
```

The tentative parsing breaks the name lookup for `@w`.
It asserts to find only namespaces in `current_declarations`.
But it finds `x`, which isn't a namespace.

#907's name lookup certainly needs work.
But bugs might lurk ahead with combining this non-local state and the tentative parsing.
