### ISSUE TITLE
[DISCUSSION] Force using non-deprecated code

### ISSUE THREAD

**Issue by define-private-public** [hsutter/cppfront#95]
I've not see the [deprecated](https://en.cppreference.com/w/cpp/language/attributes/deprecated) attribute used to much in APIs, but I have seen my share of programmers who are unknowingly using deprecated code, or at least knowingly being lazy and not updating deprecated API calls.

**I'd like to discuss forcing using non-deprecated code in cppfront**.

I.e., if you used a piece of code that's marked as `deprecated`, compilation should fail.  I think this would lead to people acting better at making sure their code is up to date.

**Comment by hsutter** [comment]
Thanks for the suggestion, but it is incomplete... please [reopen this issue using the Suggestion template](https://github.com/hsutter/cppfront/issues/new?assignees=&labels=suggestion&template=suggestion.md&title=%5BSUGGESTION%5D+) and fill in all the required parts. Thanks!
