### ISSUE TITLE
[BUG] no match for operator<< and const cpp2::nonesuch_

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#961]
After pulling in 510eae80bf3b92c7e210817c329e4b417d0012ec:
<pre>
main: () = {
  a: std::any = 1;
  std::cout << a as int << std::endl;
  std::cout << a as int << std::endl;
}
</pre>
transpiles to
<pre>
#define CPP2_IMPORT_STD          Yes
#include "cpp2util.h"
auto main() -> int;
auto main() -> int{
  std::any a {1}; 
  std::cout << cpp2::as_<int>(a) << std::endl;
  std::cout << cpp2::as_<int>(std::move(a)) << std::endl;
}
</pre>
but does not compile
<pre>
anys.cpp:10:13: error: no match for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘const cpp2::nonesuch_’)
   10 |   std::cout << cpp2::as_<int>(a) << std::endl;
      |   ~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~
      |        |                     |
      |        |                     const cpp2::nonesuch_
      |        std::ostream {aka std::basic_ostream<char>}
</pre>

**Comment by soukatch** [comment]
I believe this issue can be fixed. The most recent version generates the expected c++:
```c++
std::cout << cpp2::impl::as_<int>(a) << std::endl;
std::cout << cpp2::impl::as_<int>(cpp2::move(a)) << std::endl;
```

**Comment by wolfseifert** [comment]
I can confirm that the transpiler output changed to:
<pre>
#define CPP2_IMPORT_STD          Yes
#include "cpp2util.h"
auto main() -> int;
auto main() -> int{
  std::any a {1}; 
  std::cout << cpp2::impl::as_<int>(a) << std::endl;
  std::cout << cpp2::impl::as_<int>(cpp2::move(a)) << std::endl;
}
</pre>
but trying to compile still gives:
<pre>
anys.cpp:10:13: error: no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'const cpp2::nonesuch_')
   10 |   std::cout << cpp2::impl::as_<int>(a) << std::endl;
      |   ~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~
      |        |                           |
      |        |                           const cpp2::nonesuch_
      |        std::ostream {aka std::basic_ostream<char>}
</pre>

**Comment by soukatch** [comment]
Ah, my bad. I'll see what I can do to fix it.

**Comment by hsutter** [comment]
Thanks! This should now be fixed with the above commit, please check.
