### ISSUE TITLE
[BUG] error: local variable not used after using declaration but in fact it is

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#962]
After pulling in 510eae80bf3b92c7e210817c329e4b417d0012ec:
<pre>
prntln: (s: ::std::string) = {
  using ::std;
  cout << "A: (s)$" << endl;
}
</pre>
does not transpile
<pre>
inherit.cpp2(1,10): error: local variable 's' is not used; consider changing its name to '_' to make it explicitly anonymous, or removing it entirely if its side effects are not needed
</pre>

**Comment by hsutter** [comment]
Thanks!
@JohelEGP could you take a look at this?
