### ISSUE TITLE
[BUG] error: a 'forward' return type cannot return a local variable

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#964]
Transpiling
<pre>
Size: type == size_t;
Real: type == double;
Mat: type = {
  Elem: @struct type = {
    entry: Real;
    colind: Size;
  }
  data: ::std::valarray&lt;::std::valarray&lt;Elem&gt;&gt;;
  operator[]: (inout this, row: Size, col: Size) -> forward Real = {
    (inout datarow := data[row]) {
      for datarow do(inout d)
16:     if (d.colind == col) { return d.entry; }
      s := datarow.size();
      ndatarow := ::std::valarray&lt;Elem&gt;(s + 1);
      i: Size = 0;
      while i &lt; s next i++ {
        ndatarow[i] = datarow[i];
      }
      ndatarow[s] = Elem(0.0, col);
      datarow = ndatarow;
25:   return datarow[s].entry;
    }
  }
}
</pre>
results in two errors:
<pre>
poisson.cpp2(16,32): error: a 'forward' return type cannot return a local variable
poisson.cpp2(25,7): error: a 'forward' return type cannot return a local variable
</pre>
This code transpiled without problems with earlier cpp2 versions (some weeks ago).

**Comment by JohelEGP** [comment]
I can't find Herb's comment on this.
- Must return a parameter.
- Can't analyze complex return statements (e.g., `std::identity()(param)`).
- The error message is known to not reflect the above points.

**Comment by wolfseifert** [comment]
Changing the code to
<pre>  operator[]: (inout this, row: Size, col: Size) -&gt; forward Real = {
    i: Size = 0;
    s := data[row].size();
    while i &lt; s next i++ {
      if (data[row][i].colind == col) { return data[row][i].entry; }
    }
    ndatarow := ::std::valarray&lt;Elem&gt;(s + 1);
    i = 0;
    while i &lt; s next i++ {
      ndatarow[i] = data[row][i];
    }
    ndatarow[s] = Elem(0.0, col);
    data[row] = ndatarow;
    return data[row][s].entry;
  }</pre>
makes it transpile.

But I do not regard this as general solution of the problem.
