### ISSUE TITLE
[SUGGESTION] Add release cycles

### ISSUE THREAD

**Issue by redradist** [hsutter/cppfront#994]
To increase usability of this project, please consider adding releases.

In such way people could stick to some particular version of cppfront and move to another after sometime or after adopting a new syntax

**Comment by helmesjo** [comment]
This would be great, and I would also like to suggest sticking to [semantic versioning](https://semver.org/spec/v2.0.0.html).

**Comment by hsutter** [comment]
Thanks! Done, 0.7.0 is now labeled.
